package com.dsfa.nc.web.nctest.lsf.demo.courses.DO;

import com.dsfa.nc.web.nctest.lsf.demo.courses.DO.base.BaseCourseInfo;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
        tableName = "nc_courses_info",
        pkName = "nc_courses_info_id"
)
public class CourseInfo extends BaseCourseInfo<CourseInfo> {

    public CourseInfo() {
    }
}

