package com.dsfa.nc.web.nctest.lsf.demo.courses.DO;

import com.dsfa.nc.web.nctest.lsf.demo.courses.DO.base.BaseCourseInfoSub;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "nc_courses_info_sub",
		pkName = "nc_courses_info_sub_id"
)
public class CourseInfoSub extends BaseCourseInfoSub<CourseInfoSub> {
	public CourseInfoSub() {
	}
}

