package com.dsfa.nc.web.nctest.lsf.demo.courses.DO;

import com.dsfa.nc.web.nctest.lsf.demo.courses.DO.base.BaseCourseware;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "nc_courses_courseware",
		pkName = "nc_courses_courseware_id"
)
public class Courseware extends BaseCourseware<Courseware> {
	public Courseware() {
	}
}

