package com.dsfa.nc.web.nctest.lsf.demo.courses.DO;

import com.dsfa.nc.web.nctest.lsf.demo.courses.DO.base.BaseCoursewareLog;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "nc_courses_courseware_log",
		pkName = "nc_courses_courseware_log_id"
)
public class CoursewareLog extends BaseCoursewareLog<CoursewareLog> {
	public CoursewareLog() {
	}
}

