package com.dsfa.nc.web.nctest.lsf.demo.courses.DO;

import com.dsfa.nc.web.nctest.lsf.demo.courses.DO.base.BaseCourseInfoAuth;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "nc_courses_info_auth",
		pkName = "nc_courses_info_auth_id"
)
public class CourseInfoAuth extends BaseCourseInfoAuth<CourseInfoAuth> {
	public CourseInfoAuth() {
	}
}

