package com.dsfa.nc.web.nctest.lsf.demo.courses.DO;

import com.dsfa.nc.web.nctest.lsf.demo.courses.DO.base.BaseCourseConfig;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "nc_courses_config",
		pkName = "nc_course_config_id"
)
public class CourseConfig extends BaseCourseConfig<CourseConfig> {
	public CourseConfig() {
	}
}

