package com.dsfa.nc.web.pd.course.persistence.teacher;

import com.dsfa.nc.web.pd.course.persistence.teacher.base.BaseTeacher;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(
		tableName = "nc_teacher",
		pkName = "nc_teacher_id"
)
public class TeacherDO extends BaseTeacher<TeacherDO> {
	public TeacherDO() {
	}
}

