package com.dsfa.nc.web.pd.course.persistence.lesson;

import com.dsfa.nc.web.pd.course.persistence.lesson.base.BaseCourseInfo;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
        tableName = "nc_courses_info",
        pkName = "nc_courses_info_id"
)
public class CourseInfoDO extends BaseCourseInfo<CourseInfoDO> {

    public CourseInfoDO() {
    }
}

