package com.dsfa.nc.web.pd.course.persistence.lesson;

import com.dsfa.nc.web.pd.course.persistence.lesson.base.BaseCoursewareLog;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "nc_courses_courseware_log",
		pkName = "nc_courses_courseware_log_id"
)
public class CoursewareLogDO extends BaseCoursewareLog<CoursewareLogDO> {
	public CoursewareLogDO() {
	}
}

