package com.dsfa.nc.web.nctest.lsf.demo.teacher.DO;

import com.dsfa.nc.web.nctest.lsf.demo.teacher.DO.base.BaseTeacher;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(
		tableName = "nc_teacher",
		pkName = "nc_teacher_id"
)
public class Teacher extends BaseTeacher<Teacher> {
	public Teacher() {
	}
}

