package com.dsfa.nc.pd.learn.Do;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("nc_record_courseware", "nc_record_courseware_id", RecordCourseware.class);
		arp.addMapping("nc_record_courseware_log", "nc_record_courseware_log_id", RecordCoursewareLog.class);
	}
}


