package com.dsfa.nc.pd.learn.Do;

import com.dsfa.nc.pd.learn.Do.base.BaseRecordCourseware;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordCourseware extends BaseRecordCourseware<RecordCourseware> {
	public static final RecordCourseware dao = new RecordCourseware().dao();
}

