package com.dsfa.nc.pd.learn.Do;

import com.dsfa.nc.pd.learn.Do.base.BaseRecordCoursewareLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordCoursewareLog extends BaseRecordCoursewareLog<RecordCoursewareLog> {
	public static final RecordCoursewareLog dao = new RecordCoursewareLog().dao();
}

