package com.dsfa.nc.web.pd.specialClass.persistence;

import com.dsfa.nc.web.pd.specialClass.persistence.base.BaseBjglBjwbdwedit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglBjwbdwedit extends BaseBjglBjwbdwedit<BjglBjwbdwedit> {
	public static final BjglBjwbdwedit dao = new BjglBjwbdwedit().dao();
}

