package com.dsfa.nc.web.pd.specialClass.persistence;

import com.dsfa.nc.web.pd.specialClass.persistence.base.BaseBjglBzrinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglBzrinfo extends BaseBjglBzrinfo<BjglBzrinfo> {
	public static final BjglBzrinfo dao = new BjglBzrinfo().dao();
}

