package com.dsfa.nc.web.pd.specialClass.persistence;

import com.dsfa.nc.web.pd.specialClass.persistence.base.BaseBjglXzjly;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglXzjly extends BaseBjglXzjly<BjglXzjly> {
	public static final BjglXzjly dao = new BjglXzjly().dao();
}

