package com.dsfa.nc.web.pd.specialClass.persistence;

import com.dsfa.nc.web.pd.specialClass.persistence.base.BaseBjgl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bjgl extends BaseBjgl<Bjgl> {
	public static final Bjgl dao = new Bjgl().dao();
}

