package com.dsfa.nc.web.pd.specialClass.persistence;

import com.dsfa.nc.web.pd.specialClass.persistence.base.BaseBjglFlowTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglFlowTest extends BaseBjglFlowTest<BjglFlowTest> {
	public static final BjglFlowTest dao = new BjglFlowTest().dao();
}

