package com.dsfa.nc.web.pd.specialClass.persistence;

import com.dsfa.nc.web.pd.specialClass.persistence.base.BaseBjglXjglSzsj;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglXjglSzsj extends BaseBjglXjglSzsj<BjglXjglSzsj> {
	public static final BjglXjglSzsj dao = new BjglXjglSzsj().dao();
}

