package com.dsfa.nc.web.pd.specialClass.persistence;

import com.dsfa.nc.web.pd.specialClass.persistence.base.BaseBjglBddd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglBddd extends BaseBjglBddd<BjglBddd> {
	public static final BjglBddd dao = new BjglBddd().dao();
}

