package com.dsfa.nc.web.pd.specialClass.persistence;

import com.dsfa.nc.web.pd.specialClass.persistence.base.BaseBjglSignin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglSignin extends BaseBjglSignin<BjglSignin> {
	public static final BjglSignin dao = new BjglSignin().dao();
}

