package com.dsfa.nc.web.pd.specialClass.persistence;

import com.dsfa.nc.web.pd.specialClass.persistence.base.BaseBjglLly;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglLly extends BaseBjglLly<BjglLly> {
	public static final BjglLly dao = new BjglLly().dao();
}

