package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglXyxx;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglXyxx extends BaseBjglXyxx<BjglXyxx> {
	public static final BjglXyxx dao = new BjglXyxx().dao();
}

