package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglGbjs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglGbjs extends BaseBjglGbjs<BjglGbjs> {
	public static final BjglGbjs dao = new BjglGbjs().dao();
}

