package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglBjwbdwedit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglBjwbdwedit extends BaseBjglBjwbdwedit<BjglBjwbdwedit> {
	public static final BjglBjwbdwedit dao = new BjglBjwbdwedit().dao();
}

