package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglZjswdxOutSub;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglZjswdxOutSub extends BaseBjglZjswdxOutSub<BjglZjswdxOutSub> {
	public static final BjglZjswdxOutSub dao = new BjglZjswdxOutSub().dao();
}

