package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglXjglSzsj;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglXjglSzsj extends BaseBjglXjglSzsj<BjglXjglSzsj> {
	public static final BjglXjglSzsj dao = new BjglXjglSzsj().dao();
}

