package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglBddd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglBddd extends BaseBjglBddd<BjglBddd> {
	public static final BjglBddd dao = new BjglBddd().dao();
}

