package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglOutClassFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglOutClassFlow extends BaseBjglOutClassFlow<BjglOutClassFlow> {
	public static final BjglOutClassFlow dao = new BjglOutClassFlow().dao();
}

