package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglSignin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglSignin extends BaseBjglSignin<BjglSignin> {
	public static final BjglSignin dao = new BjglSignin().dao();
}

