package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglZbgl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglZbgl extends BaseBjglZbgl<BjglZbgl> {
	public static final BjglZbgl dao = new BjglZbgl().dao();
}

