package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglBzrinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglBzrinfo extends BaseBjglBzrinfo<BjglBzrinfo> {
	public static final BjglBzrinfo dao = new BjglBzrinfo().dao();
}

