package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglMealDemand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglMealDemand extends BaseBjglMealDemand<BjglMealDemand> {
	public static final BjglMealDemand dao = new BjglMealDemand().dao();
}

