package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglTreegl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglTreegl extends BaseBjglTreegl<BjglTreegl> {
	public static final BjglTreegl dao = new BjglTreegl().dao();
}

