package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjgl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bjgl extends BaseBjgl<Bjgl> {
	public static final Bjgl dao = new Bjgl().dao();
}

