package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglZjswdxOut;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglZjswdxOut extends BaseBjglZjswdxOut<BjglZjswdxOut> {
	public static final BjglZjswdxOut dao = new BjglZjswdxOut().dao();
}

