package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglRoomOccupy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglRoomOccupy extends BaseBjglRoomOccupy<BjglRoomOccupy> {
	public static final BjglRoomOccupy dao = new BjglRoomOccupy().dao();
}

