package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglZjswdxOutAdd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglZjswdxOutAdd extends BaseBjglZjswdxOutAdd<BjglZjswdxOutAdd> {
	public static final BjglZjswdxOutAdd dao = new BjglZjswdxOutAdd().dao();
}

