package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglLly;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglLly extends BaseBjglLly<BjglLly> {
	public static final BjglLly dao = new BjglLly().dao();
}

