package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglFlowTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglFlowTest extends BaseBjglFlowTest<BjglFlowTest> {
	public static final BjglFlowTest dao = new BjglFlowTest().dao();
}

