package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglLog extends BaseBjglLog<BjglLog> {
	public static final BjglLog dao = new BjglLog().dao();
}

