package com.dsfa.nc.web.pd.domain.courses.dao;

import com.dsfa.nc.web.pd.domain.courses.dao.base.BaseBjglXzjly;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglXzjly extends BaseBjglXzjly<BjglXzjly> {
	public static final BjglXzjly dao = new BjglXzjly().dao();
}

