package com.dsfa.nc.web.nctest.lsf.demo.teacher.DO.base;

import com.dsfa.platform.starter.meta.base.DsfaBaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends DsfaBaseModel<M> implements IBean {

	public M setNcTeacherId(java.lang.String ncTeacherId) {
		set("nc_teacher_id", ncTeacherId);
		return (M)this;
	}
	
	public java.lang.String getNcTeacherId() {
		return getStr("nc_teacher_id");
	}
	
	public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsDeptId(java.lang.String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public java.lang.String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
	public M setDsCreateUserName(java.lang.String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsCreateUserId(java.lang.String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsDeleted(java.lang.String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public java.lang.String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsOrder(java.lang.Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public java.lang.Integer getDsOrder() {
		return getInt("ds_order");
	}
	
	public M setDsUnitId(java.lang.String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public java.lang.String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setAbstract(java.lang.String _abstract) {
		set("abstract", _abstract);
		return (M)this;
	}
	
	public java.lang.String getAbstract() {
		return getStr("abstract");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setPhoto(java.lang.String photo) {
		set("photo", photo);
		return (M)this;
	}
	
	public java.lang.String getPhoto() {
		return getStr("photo");
	}
	
	public M setDeptValue(java.lang.String deptValue) {
		set("dept_value", deptValue);
		return (M)this;
	}
	
	public java.lang.String getDeptValue() {
		return getStr("dept_value");
	}
	
	public M setDeptText(java.lang.String deptText) {
		set("dept_text", deptText);
		return (M)this;
	}
	
	public java.lang.String getDeptText() {
		return getStr("dept_text");
	}
	
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	public M setBirth(java.util.Date birth) {
		set("birth", birth);
		return (M)this;
	}
	
	public java.util.Date getBirth() {
		return getDate("birth");
	}
	
	public M setGenderValue(java.lang.String genderValue) {
		set("gender_value", genderValue);
		return (M)this;
	}
	
	public java.lang.String getGenderValue() {
		return getStr("gender_value");
	}
	
	public M setGenderText(java.lang.String genderText) {
		set("gender_text", genderText);
		return (M)this;
	}
	
	public java.lang.String getGenderText() {
		return getStr("gender_text");
	}
	
	public M setAwards(java.lang.String awards) {
		set("awards", awards);
		return (M)this;
	}
	
	public java.lang.String getAwards() {
		return getStr("awards");
	}
	
	public M setNativePlaceValue(java.lang.String nativePlaceValue) {
		set("native_place_value", nativePlaceValue);
		return (M)this;
	}
	
	public java.lang.String getNativePlaceValue() {
		return getStr("native_place_value");
	}
	
	public M setNativePlaceText(java.lang.String nativePlaceText) {
		set("native_place_text", nativePlaceText);
		return (M)this;
	}
	
	public java.lang.String getNativePlaceText() {
		return getStr("native_place_text");
	}
	
	public M setAdeptValue(java.lang.String adeptValue) {
		set("adept_value", adeptValue);
		return (M)this;
	}
	
	public java.lang.String getAdeptValue() {
		return getStr("adept_value");
	}
	
	public M setAdeptText(java.lang.String adeptText) {
		set("adept_text", adeptText);
		return (M)this;
	}
	
	public java.lang.String getAdeptText() {
		return getStr("adept_text");
	}
	
	public M setNationValue(java.lang.String nationValue) {
		set("nation_value", nationValue);
		return (M)this;
	}
	
	public java.lang.String getNationValue() {
		return getStr("nation_value");
	}
	
	public M setNationText(java.lang.String nationText) {
		set("nation_text", nationText);
		return (M)this;
	}
	
	public java.lang.String getNationText() {
		return getStr("nation_text");
	}
	
	public M setPosition(java.lang.String position) {
		set("position", position);
		return (M)this;
	}
	
	public java.lang.String getPosition() {
		return getStr("position");
	}
	
	public M setEnabledValue(java.lang.String enabledValue) {
		set("enabled_value", enabledValue);
		return (M)this;
	}
	
	public java.lang.String getEnabledValue() {
		return getStr("enabled_value");
	}
	
	public M setEnabledText(java.lang.String enabledText) {
		set("enabled_text", enabledText);
		return (M)this;
	}
	
	public java.lang.String getEnabledText() {
		return getStr("enabled_text");
	}
	
	public M setTopValue(java.lang.String topValue) {
		set("top_value", topValue);
		return (M)this;
	}
	
	public java.lang.String getTopValue() {
		return getStr("top_value");
	}
	
	public M setTopText(java.lang.String topText) {
		set("top_text", topText);
		return (M)this;
	}
	
	public java.lang.String getTopText() {
		return getStr("top_text");
	}
	
	public M setDsfaOuaUserId(java.lang.String dsfaOuaUserId) {
		set("dsfa_oua_user_id", dsfaOuaUserId);
		return (M)this;
	}
	
	public java.lang.String getDsfaOuaUserId() {
		return getStr("dsfa_oua_user_id");
	}
	
	public M setPinyin(java.lang.String pinyin) {
		set("pinyin", pinyin);
		return (M)this;
	}
	
	public java.lang.String getPinyin() {
		return getStr("pinyin");
	}
	
	public M setInitials(java.lang.String initials) {
		set("initials", initials);
		return (M)this;
	}
	
	public java.lang.String getInitials() {
		return getStr("initials");
	}
	
}

