package com.dsfa.nc.pd.learn.Do.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRecordCoursewareLog<M extends BaseRecordCoursewareLog<M>> extends Model<M> implements IBean {

	public M setNcRecordCoursewareLogId(java.lang.String ncRecordCoursewareLogId) {
		set("nc_record_courseware_log_id", ncRecordCoursewareLogId);
		return (M)this;
	}
	
	public java.lang.String getNcRecordCoursewareLogId() {
		return getStr("nc_record_courseware_log_id");
	}
	
	public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsDeptId(java.lang.String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public java.lang.String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
	public M setDsCreateUserName(java.lang.String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsCreateUserId(java.lang.String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsDeleted(java.lang.String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public java.lang.String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsOrder(java.lang.Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public java.lang.Integer getDsOrder() {
		return getInt("ds_order");
	}
	
	public M setDsUnitId(java.lang.String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public java.lang.String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setDsfaOuaUserId(java.lang.String dsfaOuaUserId) {
		set("dsfa_oua_user_id", dsfaOuaUserId);
		return (M)this;
	}
	
	public java.lang.String getDsfaOuaUserId() {
		return getStr("dsfa_oua_user_id");
	}
	
	public M setOnceWatchTimespan(java.lang.String onceWatchTimespan) {
		set("once_watch_timespan", onceWatchTimespan);
		return (M)this;
	}
	
	public java.lang.String getOnceWatchTimespan() {
		return getStr("once_watch_timespan");
	}
	
	public M setRelationId(java.lang.String relationId) {
		set("relation_id", relationId);
		return (M)this;
	}
	
	public java.lang.String getRelationId() {
		return getStr("relation_id");
	}
	
	public M setOnceWatchTimeSdate(java.util.Date onceWatchTimeSdate) {
		set("once_watch_time_sdate", onceWatchTimeSdate);
		return (M)this;
	}
	
	public java.util.Date getOnceWatchTimeSdate() {
		return getDate("once_watch_time_sdate");
	}
	
	public M setOnceWatchTimeEdate(java.util.Date onceWatchTimeEdate) {
		set("once_watch_time_edate", onceWatchTimeEdate);
		return (M)this;
	}
	
	public java.util.Date getOnceWatchTimeEdate() {
		return getDate("once_watch_time_edate");
	}
	
	public M setOnceWatchDuration(java.lang.String onceWatchDuration) {
		set("once_watch_duration", onceWatchDuration);
		return (M)this;
	}
	
	public java.lang.String getOnceWatchDuration() {
		return getStr("once_watch_duration");
	}
	
}

