package com.dsfa.nc.web.pd.course.persistence.lesson.base;

import com.dsfa.platform.starter.meta.base.DsfaBaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCourseConfig<M extends BaseCourseConfig<M>> extends DsfaBaseModel<M> implements IBean {

	public M setNcCoursesConfigId(java.lang.String ncCoursesConfigId) {
		set("nc_courses_config_id", ncCoursesConfigId);
		return (M)this;
	}
	
	public java.lang.String getNcCoursesConfigId() {
		return getStr("nc_courses_config_id");
	}
	
	public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsDeptId(java.lang.String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public java.lang.String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
	public M setDsCreateUserName(java.lang.String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsCreateUserId(java.lang.String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsDeleted(java.lang.String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public java.lang.String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsOrder(java.lang.Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public java.lang.Integer getDsOrder() {
		return getInt("ds_order");
	}
	
	public M setDsUnitId(java.lang.String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public java.lang.String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setIsOrderValue(java.lang.String isOrderValue) {
		set("is_order_value", isOrderValue);
		return (M)this;
	}
	
	public java.lang.String getIsOrderValue() {
		return getStr("is_order_value");
	}
	
	public M setIsOrderText(java.lang.String isOrderText) {
		set("is_order_text", isOrderText);
		return (M)this;
	}
	
	public java.lang.String getIsOrderText() {
		return getStr("is_order_text");
	}
	
	public M setIsSpeedValue(java.lang.String isSpeedValue) {
		set("is_speed_value", isSpeedValue);
		return (M)this;
	}
	
	public java.lang.String getIsSpeedValue() {
		return getStr("is_speed_value");
	}
	
	public M setIsSpeedText(java.lang.String isSpeedText) {
		set("is_speed_text", isSpeedText);
		return (M)this;
	}
	
	public java.lang.String getIsSpeedText() {
		return getStr("is_speed_text");
	}
	
	public M setIsAutoValue(java.lang.String isAutoValue) {
		set("is_auto_value", isAutoValue);
		return (M)this;
	}
	
	public java.lang.String getIsAutoValue() {
		return getStr("is_auto_value");
	}
	
	public M setIsAutoText(java.lang.String isAutoText) {
		set("is_auto_text", isAutoText);
		return (M)this;
	}
	
	public java.lang.String getIsAutoText() {
		return getStr("is_auto_text");
	}
	
	public M setRemindTime(java.lang.String remindTime) {
		set("remind_time", remindTime);
		return (M)this;
	}
	
	public java.lang.String getRemindTime() {
		return getStr("remind_time");
	}
	
	public M setIsCircleValue(java.lang.String isCircleValue) {
		set("is_circle_value", isCircleValue);
		return (M)this;
	}
	
	public java.lang.String getIsCircleValue() {
		return getStr("is_circle_value");
	}
	
	public M setIsCircleText(java.lang.String isCircleText) {
		set("is_circle_text", isCircleText);
		return (M)this;
	}
	
	public java.lang.String getIsCircleText() {
		return getStr("is_circle_text");
	}
	
	public M setIsDragValue(java.lang.String isDragValue) {
		set("is_drag_value", isDragValue);
		return (M)this;
	}
	
	public java.lang.String getIsDragValue() {
		return getStr("is_drag_value");
	}
	
	public M setIsDragText(java.lang.String isDragText) {
		set("is_drag_text", isDragText);
		return (M)this;
	}
	
	public java.lang.String getIsDragText() {
		return getStr("is_drag_text");
	}
	
}

