package com.dsfa.nc.web.pd.domain.teacher.Do;

import com.dsfa.nc.web.pd.domain.teacher.Do.base.BaseTeacher;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(
		tableName = "nc_teacher",
		pkName = "nc_teacher_id"
)
public class TeacherDO extends BaseTeacher<TeacherDO> {
	public TeacherDO() {
	}
}

