package com.dsfa.nc.web.pd.Do;

import com.dsfa.nc.web.pd.Do.base.BaseCourseConfig;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "nc_courses_config",
		pkName = "nc_course_config_id"
)
public class CourseConfigDO extends BaseCourseConfig<CourseConfigDO> {
	public CourseConfigDO() {
	}
}

