package com.dsfa.nc.web.pd.Do;

import com.dsfa.nc.web.pd.Do.base.BaseCourseware;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "nc_courses_courseware",
		pkName = "nc_courses_courseware_id"
)
public class CoursewareDO extends BaseCourseware<CoursewareDO> {
	public CoursewareDO() {
	}
}

