package com.dsfa.nc.web.pd.Do;

import com.dsfa.nc.web.pd.Do.base.BaseAppraise;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "csml_lsf_appraise",
		pkName = "csml_lsf_appraise_id"
)
public class CourseAppraiseItemDO extends BaseAppraise<CourseAppraiseItemDO> {
	public CourseAppraiseItemDO() {
	}
}

