package com.dsfa.nc.pd.temp.model.base;

import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.IBean;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.Model;
import com.dsfa.platform.starter.db.jfinal.kit.Kv;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.Db;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.SqlPara;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDsfaOuaUser<M extends BaseDsfaOuaUser<M>> extends Model<M> implements IBean {

    public M setDsfaOuaUserId(java.lang.String dsfaOuaUserId) {
        set("dsfa_oua_user_id", dsfaOuaUserId);
        return (M)this;
    }

    public java.lang.String getDsfaOuaUserId() {
        return getStr("dsfa_oua_user_id");
    }
    public M setDsCreateTime(java.util.Date dsCreateTime) {
        set("ds_create_time", dsCreateTime);
        return (M)this;
    }

    public java.util.Date getDsCreateTime() {
        return getDate("ds_create_time");
    }
    public M setDsCreateUserId(java.lang.String dsCreateUserId) {
        set("ds_create_user_id", dsCreateUserId);
        return (M)this;
    }

    public java.lang.String getDsCreateUserId() {
        return getStr("ds_create_user_id");
    }
    public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
        set("ds_update_user_id", dsUpdateUserId);
        return (M)this;
    }

    public java.lang.String getDsUpdateUserId() {
        return getStr("ds_update_user_id");
    }
    public M setDsOrder(java.math.BigDecimal dsOrder) {
        set("ds_order", dsOrder);
        return (M)this;
    }

    public java.math.BigDecimal getDsOrder() {
        return get("ds_order");
    }
    public M setDsDeleted(java.lang.String dsDeleted) {
        set("ds_deleted", dsDeleted);
        return (M)this;
    }

    public java.lang.String getDsDeleted() {
        return getStr("ds_deleted");
    }
    public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
        set("ds_update_user_name", dsUpdateUserName);
        return (M)this;
    }

    public java.lang.String getDsUpdateUserName() {
        return getStr("ds_update_user_name");
    }
    public M setDsCreateUserName(java.lang.String dsCreateUserName) {
        set("ds_create_user_name", dsCreateUserName);
        return (M)this;
    }

    public java.lang.String getDsCreateUserName() {
        return getStr("ds_create_user_name");
    }
    public M setDsUpdateTime(java.util.Date dsUpdateTime) {
        set("ds_update_time", dsUpdateTime);
        return (M)this;
    }

    public java.util.Date getDsUpdateTime() {
        return getDate("ds_update_time");
    }
    public M setIdcard(java.lang.String idcard) {
        set("idcard", idcard);
        return (M)this;
    }

    public java.lang.String getIdcard() {
        return getStr("idcard");
    }
    public M setEmail(java.lang.String email) {
        set("email", email);
        return (M)this;
    }

    public java.lang.String getEmail() {
        return getStr("email");
    }
    public M setSexText(java.lang.String sexText) {
        set("sex_text", sexText);
        return (M)this;
    }

    public java.lang.String getSexText() {
        return getStr("sex_text");
    }
    public M setSexValue(java.lang.String sexValue) {
        set("sex_value", sexValue);
        return (M)this;
    }

    public java.lang.String getSexValue() {
        return getStr("sex_value");
    }
    public M setLoginname(java.lang.String loginname) {
        set("loginname", loginname);
        return (M)this;
    }

    public java.lang.String getLoginname() {
        return getStr("loginname");
    }
    public M setName(java.lang.String name) {
        set("name", name);
        return (M)this;
    }

    public java.lang.String getName() {
        return getStr("name");
    }
    public M setPhoto(java.lang.String photo) {
        set("photo", photo);
        return (M)this;
    }

    public java.lang.String getPhoto() {
        return getStr("photo");
    }
    public M setDduserid(java.lang.String dduserid) {
        set("dduserid", dduserid);
        return (M)this;
    }

    public java.lang.String getDduserid() {
        return getStr("dduserid");
    }
    public M setInfo(java.lang.String info) {
        set("info", info);
        return (M)this;
    }

    public java.lang.String getInfo() {
        return getStr("info");
    }
    public M setPy(java.lang.String py) {
        set("py", py);
        return (M)this;
    }

    public java.lang.String getPy() {
        return getStr("py");
    }
    public M setPinyin(java.lang.String pinyin) {
        set("pinyin", pinyin);
        return (M)this;
    }

    public java.lang.String getPinyin() {
        return getStr("pinyin");
    }
    public M setLastgroupid(java.lang.String lastgroupid) {
        set("lastgroupid", lastgroupid);
        return (M)this;
    }

    public java.lang.String getLastgroupid() {
        return getStr("lastgroupid");
    }
    public M setNationText(java.lang.String nationText) {
        set("nation_text", nationText);
        return (M)this;
    }

    public java.lang.String getNationText() {
        return getStr("nation_text");
    }
    public M setNationValue(java.lang.String nationValue) {
        set("nation_value", nationValue);
        return (M)this;
    }

    public java.lang.String getNationValue() {
        return getStr("nation_value");
    }
    public M setBirthday(java.util.Date birthday) {
        set("birthday", birthday);
        return (M)this;
    }

    public java.util.Date getBirthday() {
        return getDate("birthday");
    }
    public M setPhone(java.lang.String phone) {
        set("phone", phone);
        return (M)this;
    }

    public java.lang.String getPhone() {
        return getStr("phone");
    }
    public M setDdunionid(java.lang.String ddunionid) {
        set("ddunionid", ddunionid);
        return (M)this;
    }

    public java.lang.String getDdunionid() {
        return getStr("ddunionid");
    }
    public M setStateText(java.lang.String stateText) {
        set("state_text", stateText);
        return (M)this;
    }

    public java.lang.String getStateText() {
        return getStr("state_text");
    }
    public M setStateValue(java.lang.String stateValue) {
        set("state_value", stateValue);
        return (M)this;
    }

    public java.lang.String getStateValue() {
        return getStr("state_value");
    }
    public M setDsDeptId(java.lang.String dsDeptId) {
        set("ds_dept_id", dsDeptId);
        return (M)this;
    }

    public java.lang.String getDsDeptId() {
        return getStr("ds_dept_id");
    }
    public M setDsUnitId(java.lang.String dsUnitId) {
        set("ds_unit_id", dsUnitId);
        return (M)this;
    }

    public java.lang.String getDsUnitId() {
        return getStr("ds_unit_id");
    }
    public M setFjh(java.lang.String fjh) {
        set("fjh", fjh);
        return (M)this;
    }

    public java.lang.String getFjh() {
        return getStr("fjh");
    }
    public M setZjh(java.lang.String zjh) {
        set("zjh", zjh);
        return (M)this;
    }

    public java.lang.String getZjh() {
        return getStr("zjh");
    }
    public M setCardNo(java.lang.String cardNo) {
        set("card_no", cardNo);
        return (M)this;
    }

    public java.lang.String getCardNo() {
        return getStr("card_no");
    }
    public M setXwText(java.lang.String xwText) {
        set("xw_text", xwText);
        return (M)this;
    }

    public java.lang.String getXwText() {
        return getStr("xw_text");
    }
    public M setXwValue(java.lang.String xwValue) {
        set("xw_value", xwValue);
        return (M)this;
    }

    public java.lang.String getXwValue() {
        return getStr("xw_value");
    }
    public M setXlText(java.lang.String xlText) {
        set("xl_text", xlText);
        return (M)this;
    }

    public java.lang.String getXlText() {
        return getStr("xl_text");
    }
    public M setXlValue(java.lang.String xlValue) {
        set("xl_value", xlValue);
        return (M)this;
    }

    public java.lang.String getXlValue() {
        return getStr("xl_value");
    }
    public M setZzmmText(java.lang.String zzmmText) {
        set("zzmm_text", zzmmText);
        return (M)this;
    }

    public java.lang.String getZzmmText() {
        return getStr("zzmm_text");
    }
    public M setZzmmValue(java.lang.String zzmmValue) {
        set("zzmm_value", zzmmValue);
        return (M)this;
    }

    public java.lang.String getZzmmValue() {
        return getStr("zzmm_value");
    }
    public M setRankText(java.lang.String rankText) {
        set("rank_text", rankText);
        return (M)this;
    }

    public java.lang.String getRankText() {
        return getStr("rank_text");
    }
    public M setTitleText(java.lang.String titleText) {
        set("title_text", titleText);
        return (M)this;
    }

    public java.lang.String getTitleText() {
        return getStr("title_text");
    }
    public M setTitleValue(java.lang.String titleValue) {
        set("title_value", titleValue);
        return (M)this;
    }

    public java.lang.String getTitleValue() {
        return getStr("title_value");
    }
    public M setPost(java.lang.String post) {
        set("post", post);
        return (M)this;
    }

    public java.lang.String getPost() {
        return getStr("post");
    }
    public M setWorkphone(java.lang.String workphone) {
        set("workphone", workphone);
        return (M)this;
    }

    public java.lang.String getWorkphone() {
        return getStr("workphone");
    }
    public M setYjfx(java.lang.String yjfx) {
        set("yjfx", yjfx);
        return (M)this;
    }

    public java.lang.String getYjfx() {
        return getStr("yjfx");
    }
    public M setRankValue(java.lang.String rankValue) {
        set("rank_value", rankValue);
        return (M)this;
    }

    public java.lang.String getRankValue() {
        return getStr("rank_value");
    }
    public M setRemarks(java.lang.String remarks) {
        set("remarks", remarks);
        return (M)this;
    }

    public java.lang.String getRemarks() {
        return getStr("remarks");
    }
    public M setOrder(java.lang.String order) {
        set("_order", order);
        return (M)this;
    }

    public java.lang.String getOrder() {
        return getStr("_order");
    }
    public M setCode(java.lang.String code) {
        set("code", code);
        return (M)this;
    }

    public java.lang.String getCode() {
        return getStr("code");
    }
    public M setRzrq(java.util.Date rzrq) {
        set("rzrq", rzrq);
        return (M)this;
    }

    public java.util.Date getRzrq() {
        return getDate("rzrq");
    }
    public M setFax(java.lang.String fax) {
        set("fax", fax);
        return (M)this;
    }

    public java.lang.String getFax() {
        return getStr("fax");
    }
    public M setOpenid(java.lang.String openid) {
        set("openid", openid);
        return (M)this;
    }

    public java.lang.String getOpenid() {
        return getStr("openid");
    }
    public M setExt(java.lang.String ext) {
        set("ext", ext);
        return (M)this;
    }

    public java.lang.String getExt() {
        return getStr("ext");
    }
    public M setCreditCode(java.lang.String creditCode) {
        set("credit_code", creditCode);
        return (M)this;
    }

    public java.lang.String getCreditCode() {
        return getStr("credit_code");
    }
    public M setExt1(java.lang.String ext1) {
        set("ext1", ext1);
        return (M)this;
    }

    public java.lang.String getExt1() {
        return getStr("ext1");
    }
    public M setWechatopenid(java.lang.String wechatopenid) {
        set("wechatopenid", wechatopenid);
        return (M)this;
    }

    public java.lang.String getWechatopenid() {
        return getStr("wechatopenid");
    }
    public M setPosition(java.lang.String position) {
        set("position", position);
        return (M)this;
    }

    public java.lang.String getPosition() {
        return getStr("position");
    }
    public M setFamilyphone(java.lang.String familyphone) {
        set("familyphone", familyphone);
        return (M)this;
    }

    public java.lang.String getFamilyphone() {
        return getStr("familyphone");
    }
    public M setID(java.lang.String ID) {
        set("ID", ID);
        return (M)this;
    }

    public java.lang.String getID() {
        return getStr("ID");
    }
    public M setSynopsis(java.lang.String synopsis) {
        set("synopsis", synopsis);
        return (M)this;
    }

    public java.lang.String getSynopsis() {
        return getStr("synopsis");
    }
    public M setPostcode(java.lang.String postcode) {
        set("postcode", postcode);
        return (M)this;
    }

    public java.lang.String getPostcode() {
        return getStr("postcode");
    }
    public M setAddress(java.lang.String address) {
        set("address", address);
        return (M)this;
    }

    public java.lang.String getAddress() {
        return getStr("address");
    }
    public M setPasswd(java.lang.String passwd) {
        set("passwd", passwd);
        return (M)this;
    }

    public java.lang.String getPasswd() {
        return getStr("passwd");
    }
    public M setRepasswd(java.lang.String repasswd) {
        set("repasswd", repasswd);
        return (M)this;
    }

    public java.lang.String getRepasswd() {
        return getStr("repasswd");
    }
    public M setCorpId(java.lang.String corpId) {
        set("corp_id", corpId);
        return (M)this;
    }

    public java.lang.String getCorpId() {
        return getStr("corp_id");
    }
    public M setUsertypeText(java.lang.String usertypeText) {
        set("usertype_text", usertypeText);
        return (M)this;
    }

    public java.lang.String getUsertypeText() {
        return getStr("usertype_text");
    }
    public M setUsertypeValue(java.lang.String usertypeValue) {
        set("usertype_value", usertypeValue);
        return (M)this;
    }

    public java.lang.String getUsertypeValue() {
        return getStr("usertype_value");
    }
    public M setFacedata(java.lang.String facedata) {
        set("facedata", facedata);
        return (M)this;
    }

    public java.lang.String getFacedata() {
        return getStr("facedata");
    }
    public M setImtoken(java.lang.String imtoken) {
        set("imtoken", imtoken);
        return (M)this;
    }

    public java.lang.String getImtoken() {
        return getStr("imtoken");
    }
    public M setDeviceNo(java.lang.String deviceNo) {
        set("device_no", deviceNo);
        return (M)this;
    }

    public java.lang.String getDeviceNo() {
        return getStr("device_no");
    }
    public M setAreaValue(java.lang.String areaValue) {
        set("area_value", areaValue);
        return (M)this;
    }

    public java.lang.String getAreaValue() {
        return getStr("area_value");
    }
    public M setAreaText(java.lang.String areaText) {
        set("area_text", areaText);
        return (M)this;
    }

    public java.lang.String getAreaText() {
        return getStr("area_text");
    }
    public M setPoliticsStatusValue(java.lang.String politicsStatusValue) {
        set("politics_status_value", politicsStatusValue);
        return (M)this;
    }

    public java.lang.String getPoliticsStatusValue() {
        return getStr("politics_status_value");
    }
    public M setPoliticsStatusText(java.lang.String politicsStatusText) {
        set("politics_status_text", politicsStatusText);
        return (M)this;
    }

    public java.lang.String getPoliticsStatusText() {
        return getStr("politics_status_text");
    }
    public M setEducationValue(java.lang.String educationValue) {
        set("education_value", educationValue);
        return (M)this;
    }

    public java.lang.String getEducationValue() {
        return getStr("education_value");
    }
    public M setEducationText(java.lang.String educationText) {
        set("education_text", educationText);
        return (M)this;
    }

    public java.lang.String getEducationText() {
        return getStr("education_text");
    }
    public M setEmployeeId(java.lang.String employeeId) {
        set("employee_id", employeeId);
        return (M)this;
    }

    public java.lang.String getEmployeeId() {
        return getStr("employee_id");
    }
    public M setJobTitleValue(java.lang.String jobTitleValue) {
        set("job_title_value", jobTitleValue);
        return (M)this;
    }

    public java.lang.String getJobTitleValue() {
        return getStr("job_title_value");
    }
    public M setJobTitleText(java.lang.String jobTitleText) {
        set("job_title_text", jobTitleText);
        return (M)this;
    }

    public java.lang.String getJobTitleText() {
        return getStr("job_title_text");
    }
    public M setDegreeValue(java.lang.String degreeValue) {
        set("degree_value", degreeValue);
        return (M)this;
    }

    public java.lang.String getDegreeValue() {
        return getStr("degree_value");
    }
    public M setDegreeText(java.lang.String degreeText) {
        set("degree_text", degreeText);
        return (M)this;
    }

    public java.lang.String getDegreeText() {
        return getStr("degree_text");
    }
    public M setJob(java.lang.String job) {
        set("job", job);
        return (M)this;
    }

    public java.lang.String getJob() {
        return getStr("job");
    }
    public M setJobGradeValue(java.lang.String jobGradeValue) {
        set("job_grade_value", jobGradeValue);
        return (M)this;
    }

    public java.lang.String getJobGradeValue() {
        return getStr("job_grade_value");
    }
    public M setJobGradeText(java.lang.String jobGradeText) {
        set("job_grade_text", jobGradeText);
        return (M)this;
    }

    public java.lang.String getJobGradeText() {
        return getStr("job_grade_text");
    }
    public M setHireDate(java.util.Date hireDate) {
        set("hire_date", hireDate);
        return (M)this;
    }

    public java.util.Date getHireDate() {
        return getDate("hire_date");
    }

    public List<M> findLoadColumns(String... columns) {
        Kv kv = Kv.create()
            .set("columnNames", columns)
            .set("tableName", "dsfa_oua_user");
        SqlPara sqlPara = Db.getSqlPara("base.sql." + "findLoadColumns", kv);
        List<M> res = find(sqlPara);
        return res;
    }
}