package com.dsfa.nc.pd.temp.model.base;

import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.IBean;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.Model;
import com.dsfa.platform.starter.db.jfinal.kit.Kv;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.Db;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.SqlPara;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSdkToken<M extends BaseSdkToken<M>> extends Model<M> implements IBean {

    public M setSdkTokenId(java.lang.String sdkTokenId) {
        set("sdk_token_id", sdkTokenId);
        return (M)this;
    }

    public java.lang.String getSdkTokenId() {
        return getStr("sdk_token_id");
    }
    public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
        set("ds_update_user_id", dsUpdateUserId);
        return (M)this;
    }

    public java.lang.String getDsUpdateUserId() {
        return getStr("ds_update_user_id");
    }
    public M setDsDeptId(java.lang.String dsDeptId) {
        set("ds_dept_id", dsDeptId);
        return (M)this;
    }

    public java.lang.String getDsDeptId() {
        return getStr("ds_dept_id");
    }
    public M setDsCreateUserName(java.lang.String dsCreateUserName) {
        set("ds_create_user_name", dsCreateUserName);
        return (M)this;
    }

    public java.lang.String getDsCreateUserName() {
        return getStr("ds_create_user_name");
    }
    public M setDsCreateUserId(java.lang.String dsCreateUserId) {
        set("ds_create_user_id", dsCreateUserId);
        return (M)this;
    }

    public java.lang.String getDsCreateUserId() {
        return getStr("ds_create_user_id");
    }
    public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
        set("ds_update_user_name", dsUpdateUserName);
        return (M)this;
    }

    public java.lang.String getDsUpdateUserName() {
        return getStr("ds_update_user_name");
    }
    public M setDsDeleted(java.lang.String dsDeleted) {
        set("ds_deleted", dsDeleted);
        return (M)this;
    }

    public java.lang.String getDsDeleted() {
        return getStr("ds_deleted");
    }
    public M setDsOrder(java.lang.String dsOrder) {
        set("ds_order", dsOrder);
        return (M)this;
    }

    public java.lang.String getDsOrder() {
        return getStr("ds_order");
    }
    public M setDsUnitId(java.lang.String dsUnitId) {
        set("ds_unit_id", dsUnitId);
        return (M)this;
    }

    public java.lang.String getDsUnitId() {
        return getStr("ds_unit_id");
    }
    public M setDsCreateTime(java.lang.String dsCreateTime) {
        set("ds_create_time", dsCreateTime);
        return (M)this;
    }

    public java.lang.String getDsCreateTime() {
        return getStr("ds_create_time");
    }
    public M setDsUpdateTime(java.lang.String dsUpdateTime) {
        set("ds_update_time", dsUpdateTime);
        return (M)this;
    }

    public java.lang.String getDsUpdateTime() {
        return getStr("ds_update_time");
    }
    public M setNAME(java.lang.String NAME) {
        set("NAME", NAME);
        return (M)this;
    }

    public java.lang.String getNAME() {
        return getStr("NAME");
    }
    public M setOauthRootValue(java.lang.String oauthRootValue) {
        set("oauth_root_value", oauthRootValue);
        return (M)this;
    }

    public java.lang.String getOauthRootValue() {
        return getStr("oauth_root_value");
    }
    public M setOauthRootText(java.lang.String oauthRootText) {
        set("oauth_root_text", oauthRootText);
        return (M)this;
    }

    public java.lang.String getOauthRootText() {
        return getStr("oauth_root_text");
    }
    public M setAppKey(java.lang.String appKey) {
        set("app_key", appKey);
        return (M)this;
    }

    public java.lang.String getAppKey() {
        return getStr("app_key");
    }
    public M setAppSecret(java.lang.String appSecret) {
        set("app_secret", appSecret);
        return (M)this;
    }

    public java.lang.String getAppSecret() {
        return getStr("app_secret");
    }

    public List<M> findLoadColumns(String... columns) {
        Kv kv = Kv.create()
            .set("columnNames", columns)
            .set("tableName", "sdk_token");
        SqlPara sqlPara = Db.getSqlPara("base.sql." + "findLoadColumns", kv);
        List<M> res = find(sqlPara);
        return res;
    }
}