package com.dsfa.nc.pd.temp.model.base;

import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.IBean;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.Model;
import com.dsfa.platform.starter.db.jfinal.kit.Kv;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.Db;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.SqlPara;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNcCoursesInfo<M extends BaseNcCoursesInfo<M>> extends Model<M> implements IBean {

    public M setNcCoursesInfoId(java.lang.String ncCoursesInfoId) {
        set("nc_courses_info_id", ncCoursesInfoId);
        return (M)this;
    }

    public java.lang.String getNcCoursesInfoId() {
        return getStr("nc_courses_info_id");
    }
    public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
        set("ds_update_user_id", dsUpdateUserId);
        return (M)this;
    }

    public java.lang.String getDsUpdateUserId() {
        return getStr("ds_update_user_id");
    }
    public M setDsDeptId(java.lang.String dsDeptId) {
        set("ds_dept_id", dsDeptId);
        return (M)this;
    }

    public java.lang.String getDsDeptId() {
        return getStr("ds_dept_id");
    }
    public M setDsCreateUserName(java.lang.String dsCreateUserName) {
        set("ds_create_user_name", dsCreateUserName);
        return (M)this;
    }

    public java.lang.String getDsCreateUserName() {
        return getStr("ds_create_user_name");
    }
    public M setDsCreateUserId(java.lang.String dsCreateUserId) {
        set("ds_create_user_id", dsCreateUserId);
        return (M)this;
    }

    public java.lang.String getDsCreateUserId() {
        return getStr("ds_create_user_id");
    }
    public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
        set("ds_update_user_name", dsUpdateUserName);
        return (M)this;
    }

    public java.lang.String getDsUpdateUserName() {
        return getStr("ds_update_user_name");
    }
    public M setDsDeleted(java.lang.String dsDeleted) {
        set("ds_deleted", dsDeleted);
        return (M)this;
    }

    public java.lang.String getDsDeleted() {
        return getStr("ds_deleted");
    }
    public M setDsOrder(java.lang.Integer dsOrder) {
        set("ds_order", dsOrder);
        return (M)this;
    }

    public java.lang.Integer getDsOrder() {
        return getInt("ds_order");
    }
    public M setDsUnitId(java.lang.String dsUnitId) {
        set("ds_unit_id", dsUnitId);
        return (M)this;
    }

    public java.lang.String getDsUnitId() {
        return getStr("ds_unit_id");
    }
    public M setDsCreateTime(java.util.Date dsCreateTime) {
        set("ds_create_time", dsCreateTime);
        return (M)this;
    }

    public java.util.Date getDsCreateTime() {
        return getDate("ds_create_time");
    }
    public M setDsUpdateTime(java.util.Date dsUpdateTime) {
        set("ds_update_time", dsUpdateTime);
        return (M)this;
    }

    public java.util.Date getDsUpdateTime() {
        return getDate("ds_update_time");
    }
    public M setTeacherValue(java.lang.String teacherValue) {
        set("teacher_value", teacherValue);
        return (M)this;
    }

    public java.lang.String getTeacherValue() {
        return getStr("teacher_value");
    }
    public M setTeacherText(java.lang.String teacherText) {
        set("teacher_text", teacherText);
        return (M)this;
    }

    public java.lang.String getTeacherText() {
        return getStr("teacher_text");
    }
    public M setCover(java.lang.String cover) {
        set("cover", cover);
        return (M)this;
    }

    public java.lang.String getCover() {
        return getStr("cover");
    }
    public M setClassificationValue(java.lang.String classificationValue) {
        set("classification_value", classificationValue);
        return (M)this;
    }

    public java.lang.String getClassificationValue() {
        return getStr("classification_value");
    }
    public M setClassificationText(java.lang.String classificationText) {
        set("classification_text", classificationText);
        return (M)this;
    }

    public java.lang.String getClassificationText() {
        return getStr("classification_text");
    }
    public M setTitle(java.lang.String title) {
        set("title", title);
        return (M)this;
    }

    public java.lang.String getTitle() {
        return getStr("title");
    }
    public M setContent(java.lang.String content) {
        set("content", content);
        return (M)this;
    }

    public java.lang.String getContent() {
        return getStr("content");
    }
    public M setRemark(java.lang.String remark) {
        set("remark", remark);
        return (M)this;
    }

    public java.lang.String getRemark() {
        return getStr("remark");
    }
    public M setDuration(java.lang.String duration) {
        set("duration", duration);
        return (M)this;
    }

    public java.lang.String getDuration() {
        return getStr("duration");
    }
    public M setPeriod(java.lang.String period) {
        set("period", period);
        return (M)this;
    }

    public java.lang.String getPeriod() {
        return getStr("period");
    }
    public M setRCode(java.lang.String rCode) {
        set("r_code", rCode);
        return (M)this;
    }

    public java.lang.String getRCode() {
        return getStr("r_code");
    }
    public M setIsPublicValue(java.lang.String isPublicValue) {
        set("is_public_value", isPublicValue);
        return (M)this;
    }

    public java.lang.String getIsPublicValue() {
        return getStr("is_public_value");
    }
    public M setIsPublicText(java.lang.String isPublicText) {
        set("is_public_text", isPublicText);
        return (M)this;
    }

    public java.lang.String getIsPublicText() {
        return getStr("is_public_text");
    }
    public M setRLabelValue(java.lang.String rLabelValue) {
        set("r_label_value", rLabelValue);
        return (M)this;
    }

    public java.lang.String getRLabelValue() {
        return getStr("r_label_value");
    }
    public M setRLabelText(java.lang.String rLabelText) {
        set("r_label_text", rLabelText);
        return (M)this;
    }

    public java.lang.String getRLabelText() {
        return getStr("r_label_text");
    }
    public M setStateValue(java.lang.String stateValue) {
        set("state_value", stateValue);
        return (M)this;
    }

    public java.lang.String getStateValue() {
        return getStr("state_value");
    }
    public M setStateText(java.lang.String stateText) {
        set("state_text", stateText);
        return (M)this;
    }

    public java.lang.String getStateText() {
        return getStr("state_text");
    }
    public M setIsPublishValue(java.lang.String isPublishValue) {
        set("is_publish_value", isPublishValue);
        return (M)this;
    }

    public java.lang.String getIsPublishValue() {
        return getStr("is_publish_value");
    }
    public M setIsPublishText(java.lang.String isPublishText) {
        set("is_publish_text", isPublishText);
        return (M)this;
    }

    public java.lang.String getIsPublishText() {
        return getStr("is_publish_text");
    }
    public M setIsTopValue(java.lang.String isTopValue) {
        set("is_top_value", isTopValue);
        return (M)this;
    }

    public java.lang.String getIsTopValue() {
        return getStr("is_top_value");
    }
    public M setIsTopText(java.lang.String isTopText) {
        set("is_top_text", isTopText);
        return (M)this;
    }

    public java.lang.String getIsTopText() {
        return getStr("is_top_text");
    }
    public M setRTypeValue(java.lang.String rTypeValue) {
        set("r_type_value", rTypeValue);
        return (M)this;
    }

    public java.lang.String getRTypeValue() {
        return getStr("r_type_value");
    }
    public M setRTypeText(java.lang.String rTypeText) {
        set("r_type_text", rTypeText);
        return (M)this;
    }

    public java.lang.String getRTypeText() {
        return getStr("r_type_text");
    }
    public M setTeacherAuto(java.lang.String teacherAuto) {
        set("teacher_auto", teacherAuto);
        return (M)this;
    }

    public java.lang.String getTeacherAuto() {
        return getStr("teacher_auto");
    }
    public M setTeacherShowUnitJob(java.lang.String teacherShowUnitJob) {
        set("teacher_show_unit_job", teacherShowUnitJob);
        return (M)this;
    }

    public java.lang.String getTeacherShowUnitJob() {
        return getStr("teacher_show_unit_job");
    }
    public M setTeacherShowValue(java.lang.String teacherShowValue) {
        set("teacher_show_value", teacherShowValue);
        return (M)this;
    }

    public java.lang.String getTeacherShowValue() {
        return getStr("teacher_show_value");
    }
    public M setTeacherShowText(java.lang.String teacherShowText) {
        set("teacher_show_text", teacherShowText);
        return (M)this;
    }

    public java.lang.String getTeacherShowText() {
        return getStr("teacher_show_text");
    }
    public M setViewTotle(java.lang.String viewTotle) {
        set("view_totle", viewTotle);
        return (M)this;
    }

    public java.lang.String getViewTotle() {
        return getStr("view_totle");
    }

    public List<M> findLoadColumns(String... columns) {
        Kv kv = Kv.create()
            .set("columnNames", columns)
            .set("tableName", "nc_courses_info");
        SqlPara sqlPara = Db.getSqlPara("base.sql." + "findLoadColumns", kv);
        List<M> res = find(sqlPara);
        return res;
    }
}