package com.dsfa.nc.pd.temp.model.base;

import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.IBean;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.Model;
import com.dsfa.platform.starter.db.jfinal.kit.Kv;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.Db;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.SqlPara;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNcAuthoInfo<M extends BaseNcAuthoInfo<M>> extends Model<M> implements IBean {

    public M setNcAuthoInfoId(java.lang.String ncAuthoInfoId) {
        set("nc_autho_info_id", ncAuthoInfoId);
        return (M)this;
    }

    public java.lang.String getNcAuthoInfoId() {
        return getStr("nc_autho_info_id");
    }
    public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
        set("ds_update_user_id", dsUpdateUserId);
        return (M)this;
    }

    public java.lang.String getDsUpdateUserId() {
        return getStr("ds_update_user_id");
    }
    public M setDsDeptId(java.lang.String dsDeptId) {
        set("ds_dept_id", dsDeptId);
        return (M)this;
    }

    public java.lang.String getDsDeptId() {
        return getStr("ds_dept_id");
    }
    public M setDsCreateUserName(java.lang.String dsCreateUserName) {
        set("ds_create_user_name", dsCreateUserName);
        return (M)this;
    }

    public java.lang.String getDsCreateUserName() {
        return getStr("ds_create_user_name");
    }
    public M setDsCreateUserId(java.lang.String dsCreateUserId) {
        set("ds_create_user_id", dsCreateUserId);
        return (M)this;
    }

    public java.lang.String getDsCreateUserId() {
        return getStr("ds_create_user_id");
    }
    public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
        set("ds_update_user_name", dsUpdateUserName);
        return (M)this;
    }

    public java.lang.String getDsUpdateUserName() {
        return getStr("ds_update_user_name");
    }
    public M setDsDeleted(java.lang.String dsDeleted) {
        set("ds_deleted", dsDeleted);
        return (M)this;
    }

    public java.lang.String getDsDeleted() {
        return getStr("ds_deleted");
    }
    public M setDsOrder(java.lang.Integer dsOrder) {
        set("ds_order", dsOrder);
        return (M)this;
    }

    public java.lang.Integer getDsOrder() {
        return getInt("ds_order");
    }
    public M setDsUnitId(java.lang.String dsUnitId) {
        set("ds_unit_id", dsUnitId);
        return (M)this;
    }

    public java.lang.String getDsUnitId() {
        return getStr("ds_unit_id");
    }
    public M setDsCreateTime(java.util.Date dsCreateTime) {
        set("ds_create_time", dsCreateTime);
        return (M)this;
    }

    public java.util.Date getDsCreateTime() {
        return getDate("ds_create_time");
    }
    public M setDsUpdateTime(java.util.Date dsUpdateTime) {
        set("ds_update_time", dsUpdateTime);
        return (M)this;
    }

    public java.util.Date getDsUpdateTime() {
        return getDate("ds_update_time");
    }
    public M setUnitsValue(java.lang.String unitsValue) {
        set("units_value", unitsValue);
        return (M)this;
    }

    public java.lang.String getUnitsValue() {
        return getStr("units_value");
    }
    public M setUnitsText(java.lang.String unitsText) {
        set("units_text", unitsText);
        return (M)this;
    }

    public java.lang.String getUnitsText() {
        return getStr("units_text");
    }
    public M setBusinessTypeValue(java.lang.String businessTypeValue) {
        set("business_type_value", businessTypeValue);
        return (M)this;
    }

    public java.lang.String getBusinessTypeValue() {
        return getStr("business_type_value");
    }
    public M setBusinessTypeText(java.lang.String businessTypeText) {
        set("business_type_text", businessTypeText);
        return (M)this;
    }

    public java.lang.String getBusinessTypeText() {
        return getStr("business_type_text");
    }
    public M setBusinessId(java.lang.String businessId) {
        set("business_id", businessId);
        return (M)this;
    }

    public java.lang.String getBusinessId() {
        return getStr("business_id");
    }
    public M setScopeValue(java.lang.String scopeValue) {
        set("scope_value", scopeValue);
        return (M)this;
    }

    public java.lang.String getScopeValue() {
        return getStr("scope_value");
    }
    public M setScopeText(java.lang.String scopeText) {
        set("scope_text", scopeText);
        return (M)this;
    }

    public java.lang.String getScopeText() {
        return getStr("scope_text");
    }
    public M setUsersValue(java.lang.String usersValue) {
        set("users_value", usersValue);
        return (M)this;
    }

    public java.lang.String getUsersValue() {
        return getStr("users_value");
    }
    public M setUsersText(java.lang.String usersText) {
        set("users_text", usersText);
        return (M)this;
    }

    public java.lang.String getUsersText() {
        return getStr("users_text");
    }

    public List<M> findLoadColumns(String... columns) {
        Kv kv = Kv.create()
            .set("columnNames", columns)
            .set("tableName", "nc_autho_info");
        SqlPara sqlPara = Db.getSqlPara("base.sql." + "findLoadColumns", kv);
        List<M> res = find(sqlPara);
        return res;
    }
}