package com.dsfa.nc.pd.temp.model.base;

import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.IBean;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.Model;
import com.dsfa.platform.starter.db.jfinal.kit.Kv;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.Db;
import com.dsfa.platform.starter.db.jfinal.plugin.activerecord.SqlPara;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDsfaOuaUserUserdept<M extends BaseDsfaOuaUserUserdept<M>> extends Model<M> implements IBean {

    public M setDsfaOuaUserUserdeptId(java.lang.String dsfaOuaUserUserdeptId) {
        set("dsfa_oua_user_userdept_id", dsfaOuaUserUserdeptId);
        return (M)this;
    }

    public java.lang.String getDsfaOuaUserUserdeptId() {
        return getStr("dsfa_oua_user_userdept_id");
    }
    public M setDsCreateTime(java.util.Date dsCreateTime) {
        set("ds_create_time", dsCreateTime);
        return (M)this;
    }

    public java.util.Date getDsCreateTime() {
        return getDate("ds_create_time");
    }
    public M setDsCreateUserId(java.lang.String dsCreateUserId) {
        set("ds_create_user_id", dsCreateUserId);
        return (M)this;
    }

    public java.lang.String getDsCreateUserId() {
        return getStr("ds_create_user_id");
    }
    public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
        set("ds_update_user_id", dsUpdateUserId);
        return (M)this;
    }

    public java.lang.String getDsUpdateUserId() {
        return getStr("ds_update_user_id");
    }
    public M setDsOrder(java.math.BigDecimal dsOrder) {
        set("ds_order", dsOrder);
        return (M)this;
    }

    public java.math.BigDecimal getDsOrder() {
        return get("ds_order");
    }
    public M setDsDeleted(java.lang.String dsDeleted) {
        set("ds_deleted", dsDeleted);
        return (M)this;
    }

    public java.lang.String getDsDeleted() {
        return getStr("ds_deleted");
    }
    public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
        set("ds_update_user_name", dsUpdateUserName);
        return (M)this;
    }

    public java.lang.String getDsUpdateUserName() {
        return getStr("ds_update_user_name");
    }
    public M setDsCreateUserName(java.lang.String dsCreateUserName) {
        set("ds_create_user_name", dsCreateUserName);
        return (M)this;
    }

    public java.lang.String getDsCreateUserName() {
        return getStr("ds_create_user_name");
    }
    public M setDsUpdateTime(java.util.Date dsUpdateTime) {
        set("ds_update_time", dsUpdateTime);
        return (M)this;
    }

    public java.util.Date getDsUpdateTime() {
        return getDate("ds_update_time");
    }
    public M setDsUnitId(java.lang.String dsUnitId) {
        set("ds_unit_id", dsUnitId);
        return (M)this;
    }

    public java.lang.String getDsUnitId() {
        return getStr("ds_unit_id");
    }
    public M setDsfaOuaUserId(java.lang.String dsfaOuaUserId) {
        set("dsfa_oua_user_id", dsfaOuaUserId);
        return (M)this;
    }

    public java.lang.String getDsfaOuaUserId() {
        return getStr("dsfa_oua_user_id");
    }
    public M setUserrank(java.lang.String userrank) {
        set("userrank", userrank);
        return (M)this;
    }

    public java.lang.String getUserrank() {
        return getStr("userrank");
    }
    public M setDsfaOuaUnitId(java.lang.String dsfaOuaUnitId) {
        set("dsfa_oua_unit_id", dsfaOuaUnitId);
        return (M)this;
    }

    public java.lang.String getDsfaOuaUnitId() {
        return getStr("dsfa_oua_unit_id");
    }
    public M setUserstatus(java.lang.String userstatus) {
        set("userstatus", userstatus);
        return (M)this;
    }

    public java.lang.String getUserstatus() {
        return getStr("userstatus");
    }
    public M setDeptname(java.lang.String deptname) {
        set("deptname", deptname);
        return (M)this;
    }

    public java.lang.String getDeptname() {
        return getStr("deptname");
    }
    public M setUsername(java.lang.String username) {
        set("username", username);
        return (M)this;
    }

    public java.lang.String getUsername() {
        return getStr("username");
    }
    public M setIsmainText(java.lang.String ismainText) {
        set("ismain_text", ismainText);
        return (M)this;
    }

    public java.lang.String getIsmainText() {
        return getStr("ismain_text");
    }
    public M setIsmainValue(java.lang.String ismainValue) {
        set("ismain_value", ismainValue);
        return (M)this;
    }

    public java.lang.String getIsmainValue() {
        return getStr("ismain_value");
    }
    public M setDsDeptId(java.lang.String dsDeptId) {
        set("ds_dept_id", dsDeptId);
        return (M)this;
    }

    public java.lang.String getDsDeptId() {
        return getStr("ds_dept_id");
    }
    public M setNl(java.lang.String nl) {
        set("nl", nl);
        return (M)this;
    }

    public java.lang.String getNl() {
        return getStr("nl");
    }

    public List<M> findLoadColumns(String... columns) {
        Kv kv = Kv.create()
            .set("columnNames", columns)
            .set("tableName", "dsfa_oua_user_userdept");
        SqlPara sqlPara = Db.getSqlPara("base.sql." + "findLoadColumns", kv);
        List<M> res = find(sqlPara);
        return res;
    }
}