package com.dsfa.nc.pd.lesson.specialClass.persistence.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBjgl<M extends BaseBjgl<M>> extends Model<M> implements IBean {

	public M setTeasJwglBjglId(String teasJwglBjglId) {
		set("teas_jwgl_bjgl_id", teasJwglBjglId);
		return (M)this;
	}

	public String getTeasJwglBjglId() {
		return getStr("teas_jwgl_bjgl_id");
	}

	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}

	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}

	public M setDsCreateUserId(String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}

	public String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}

	public M setDsUpdateUserId(String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}

	public String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}

	public M setDsOrder(java.math.BigDecimal dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}

	public java.math.BigDecimal getDsOrder() {
		return get("ds_order");
	}

	public M setDsDeleted(String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}

	public String getDsDeleted() {
		return getStr("ds_deleted");
	}

	public M setDsUpdateUserName(String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}

	public String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}

	public M setDsCreateUserName(String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}

	public String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}

	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}

	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}

	public M setDsUnitId(String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}

	public String getDsUnitId() {
		return getStr("ds_unit_id");
	}

	public M setXnText(String xnText) {
		set("xn_text", xnText);
		return (M)this;
	}

	public String getXnText() {
		return getStr("xn_text");
	}

	public M setXnValue(String xnValue) {
		set("xn_value", xnValue);
		return (M)this;
	}

	public String getXnValue() {
		return getStr("xn_value");
	}

	public M setXqText(String xqText) {
		set("xq_text", xqText);
		return (M)this;
	}

	public String getXqText() {
		return getStr("xq_text");
	}

	public M setXqValue(String xqValue) {
		set("xq_value", xqValue);
		return (M)this;
	}

	public String getXqValue() {
		return getStr("xq_value");
	}

	public M setPxsjSdate(java.util.Date pxsjSdate) {
		set("pxsj_sdate", pxsjSdate);
		return (M)this;
	}

	public java.util.Date getPxsjSdate() {
		return getDate("pxsj_sdate");
	}

	public M setPxsjEdate(java.util.Date pxsjEdate) {
		set("pxsj_edate", pxsjEdate);
		return (M)this;
	}

	public java.util.Date getPxsjEdate() {
		return getDate("pxsj_edate");
	}

	public M setRxtz(String rxtz) {
		set("rxtz", rxtz);
		return (M)this;
	}

	public String getRxtz() {
		return getStr("rxtz");
	}

	public M setKcpjText(String kcpjText) {
		set("kcpj_text", kcpjText);
		return (M)this;
	}

	public String getKcpjText() {
		return getStr("kcpj_text");
	}

	public M setKcpjValue(String kcpjValue) {
		set("kcpj_value", kcpjValue);
		return (M)this;
	}

	public String getKcpjValue() {
		return getStr("kcpj_value");
	}

	public M setBjxzText(String bjxzText) {
		set("bjxz_text", bjxzText);
		return (M)this;
	}

	public String getBjxzText() {
		return getStr("bjxz_text");
	}

	public M setBjxzValue(String bjxzValue) {
		set("bjxz_value", bjxzValue);
		return (M)this;
	}

	public String getBjxzValue() {
		return getStr("bjxz_value");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setBzrText(String bzrText) {
		set("bzr_text", bzrText);
		return (M)this;
	}

	public String getBzrText() {
		return getStr("bzr_text");
	}

	public M setBzrValue(String bzrValue) {
		set("bzr_value", bzrValue);
		return (M)this;
	}

	public String getBzrValue() {
		return getStr("bzr_value");
	}

	public M setBclxText(String bclxText) {
		set("bclx_text", bclxText);
		return (M)this;
	}

	public String getBclxText() {
		return getStr("bclx_text");
	}

	public M setBclxValue(String bclxValue) {
		set("bclx_value", bclxValue);
		return (M)this;
	}

	public String getBclxValue() {
		return getStr("bclx_value");
	}

	public M setSkddText(String skddText) {
		set("skdd_text", skddText);
		return (M)this;
	}

	public String getSkddText() {
		return getStr("skdd_text");
	}

	public M setSkddValue(String skddValue) {
		set("skdd_value", skddValue);
		return (M)this;
	}

	public String getSkddValue() {
		return getStr("skdd_value");
	}

	public M setHqpjText(String hqpjText) {
		set("hqpj_text", hqpjText);
		return (M)this;
	}

	public String getHqpjText() {
		return getStr("hqpj_text");
	}

	public M setHqpjValue(String hqpjValue) {
		set("hqpj_value", hqpjValue);
		return (M)this;
	}

	public String getHqpjValue() {
		return getStr("hqpj_value");
	}

	public M setBcbh(String bcbh) {
		set("bcbh", bcbh);
		return (M)this;
	}

	public String getBcbh() {
		return getStr("bcbh");
	}

	public M setBjlbText(String bjlbText) {
		set("bjlb_text", bjlbText);
		return (M)this;
	}

	public String getBjlbText() {
		return getStr("bjlb_text");
	}

	public M setBjlbValue(String bjlbValue) {
		set("bjlb_value", bjlbValue);
		return (M)this;
	}

	public String getBjlbValue() {
		return getStr("bjlb_value");
	}

	public M setPjbzrText(String pjbzrText) {
		set("pjbzr_text", pjbzrText);
		return (M)this;
	}

	public String getPjbzrText() {
		return getStr("pjbzr_text");
	}

	public M setPjbzrValue(String pjbzrValue) {
		set("pjbzr_value", pjbzrValue);
		return (M)this;
	}

	public String getPjbzrValue() {
		return getStr("pjbzr_value");
	}

	public M setBczpText(String bczpText) {
		set("bczp_text", bczpText);
		return (M)this;
	}

	public String getBczpText() {
		return getStr("bczp_text");
	}

	public M setBczpValue(String bczpValue) {
		set("bczp_value", bczpValue);
		return (M)this;
	}

	public String getBczpValue() {
		return getStr("bczp_value");
	}

	public M setWspkText(String wspkText) {
		set("wspk_text", wspkText);
		return (M)this;
	}

	public String getWspkText() {
		return getStr("wspk_text");
	}

	public M setWspkValue(String wspkValue) {
		set("wspk_value", wspkValue);
		return (M)this;
	}

	public String getWspkValue() {
		return getStr("wspk_value");
	}

	public M setFjh(String fjh) {
		set("fjh", fjh);
		return (M)this;
	}

	public String getFjh() {
		return getStr("fjh");
	}

	public M setKcsffbText(String kcsffbText) {
		set("kcsffb_text", kcsffbText);
		return (M)this;
	}

	public String getKcsffbText() {
		return getStr("kcsffb_text");
	}

	public M setKcsffbValue(String kcsffbValue) {
		set("kcsffb_value", kcsffbValue);
		return (M)this;
	}

	public String getKcsffbValue() {
		return getStr("kcsffb_value");
	}

	public M setFbstatusText(String fbstatusText) {
		set("fbstatus_text", fbstatusText);
		return (M)this;
	}

	public String getFbstatusText() {
		return getStr("fbstatus_text");
	}

	public M setFbstatusValue(String fbstatusValue) {
		set("fbstatus_value", fbstatusValue);
		return (M)this;
	}

	public String getFbstatusValue() {
		return getStr("fbstatus_value");
	}

	public M setKcsffb(java.math.BigDecimal kcsffb) {
		set("kcsffb", kcsffb);
		return (M)this;
	}

	public java.math.BigDecimal getKcsffb() {
		return get("kcsffb");
	}

	public M setZwl(String zwl) {
		set("zwl", zwl);
		return (M)this;
	}

	public String getZwl() {
		return getStr("zwl");
	}

	public M setZwh(String zwh) {
		set("zwh", zwh);
		return (M)this;
	}

	public String getZwh() {
		return getStr("zwh");
	}

	public M setTspjdbText(String tspjdbText) {
		set("tspjdb_text", tspjdbText);
		return (M)this;
	}

	public String getTspjdbText() {
		return getStr("tspjdb_text");
	}

	public M setTspjdbValue(String tspjdbValue) {
		set("tspjdb_value", tspjdbValue);
		return (M)this;
	}

	public String getTspjdbValue() {
		return getStr("tspjdb_value");
	}

	public M setRxdcText(String rxdcText) {
		set("rxdc_text", rxdcText);
		return (M)this;
	}

	public String getRxdcText() {
		return getStr("rxdc_text");
	}

	public M setRxdcValue(String rxdcValue) {
		set("rxdc_value", rxdcValue);
		return (M)this;
	}

	public String getRxdcValue() {
		return getStr("rxdc_value");
	}

	public M setSjlyText(String sjlyText) {
		set("sjly_text", sjlyText);
		return (M)this;
	}

	public String getSjlyText() {
		return getStr("sjly_text");
	}

	public M setSjlyValue(String sjlyValue) {
		set("sjly_value", sjlyValue);
		return (M)this;
	}

	public String getSjlyValue() {
		return getStr("sjly_value");
	}

	public M setQyztText(String qyztText) {
		set("qyzt_text", qyztText);
		return (M)this;
	}

	public String getQyztText() {
		return getStr("qyzt_text");
	}

	public M setQyztValue(String qyztValue) {
		set("qyzt_value", qyztValue);
		return (M)this;
	}

	public String getQyztValue() {
		return getStr("qyzt_value");
	}

	public M setDsDeptId(String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}

	public String getDsDeptId() {
		return getStr("ds_dept_id");
	}

	public M setFzsl(java.math.BigDecimal fzsl) {
		set("fzsl", fzsl);
		return (M)this;
	}

	public java.math.BigDecimal getFzsl() {
		return get("fzsl");
	}

	public M setXs(String xs) {
		set("xs", xs);
		return (M)this;
	}

	public String getXs() {
		return getStr("xs");
	}

	public M setBmsjSdate(java.util.Date bmsjSdate) {
		set("bmsj_sdate", bmsjSdate);
		return (M)this;
	}

	public java.util.Date getBmsjSdate() {
		return getDate("bmsj_sdate");
	}

	public M setBmsjEdate(java.util.Date bmsjEdate) {
		set("bmsj_edate", bmsjEdate);
		return (M)this;
	}

	public java.util.Date getBmsjEdate() {
		return getDate("bmsj_edate");
	}

	public M setXz(String xz) {
		set("xz", xz);
		return (M)this;
	}

	public String getXz() {
		return getStr("xz");
	}

	public M setTxrs(String txrs) {
		set("txrs", txrs);
		return (M)this;
	}

	public String getTxrs() {
		return getStr("txrs");
	}

	public M setLxxldText(String lxxldText) {
		set("lxxld_text", lxxldText);
		return (M)this;
	}

	public String getLxxldText() {
		return getStr("lxxld_text");
	}

	public M setLxxldValue(String lxxldValue) {
		set("lxxld_value", lxxldValue);
		return (M)this;
	}

	public String getLxxldValue() {
		return getStr("lxxld_value");
	}

	public M setBddd(String bddd) {
		set("bddd", bddd);
		return (M)this;
	}

	public String getBddd() {
		return getStr("bddd");
	}

	public M setWbfy(String wbfy) {
		set("wbfy", wbfy);
		return (M)this;
	}

	public String getWbfy() {
		return getStr("wbfy");
	}

	public M setWbsjSdate(java.util.Date wbsjSdate) {
		set("wbsj_sdate", wbsjSdate);
		return (M)this;
	}

	public java.util.Date getWbsjSdate() {
		return getDate("wbsj_sdate");
	}

	public M setWbsjEdate(java.util.Date wbsjEdate) {
		set("wbsj_edate", wbsjEdate);
		return (M)this;
	}

	public java.util.Date getWbsjEdate() {
		return getDate("wbsj_edate");
	}

	public M setSxrs(java.math.BigDecimal sxrs) {
		set("sxrs", sxrs);
		return (M)this;
	}

	public java.math.BigDecimal getSxrs() {
		return get("sxrs");
	}

	public M setBjgnText(String bjgnText) {
		set("bjgn_text", bjgnText);
		return (M)this;
	}

	public String getBjgnText() {
		return getStr("bjgn_text");
	}

	public M setBjgnValue(String bjgnValue) {
		set("bjgn_value", bjgnValue);
		return (M)this;
	}

	public String getBjgnValue() {
		return getStr("bjgn_value");
	}

	public M setClassid(String classid) {
		set("classid", classid);
		return (M)this;
	}

	public String getClassid() {
		return getStr("classid");
	}

	public M setBcxgztText(String bcxgztText) {
		set("bcxgzt_text", bcxgztText);
		return (M)this;
	}

	public String getBcxgztText() {
		return getStr("bcxgzt_text");
	}

	public M setBcxgztValue(String bcxgztValue) {
		set("bcxgzt_value", bcxgztValue);
		return (M)this;
	}

	public String getBcxgztValue() {
		return getStr("bcxgzt_value");
	}

	public M setZbmc(String zbmc) {
		set("zbmc", zbmc);
		return (M)this;
	}

	public String getZbmc() {
		return getStr("zbmc");
	}

	public M setZbbh(java.math.BigDecimal zbbh) {
		set("zbbh", zbbh);
		return (M)this;
	}

	public java.math.BigDecimal getZbbh() {
		return get("zbbh");
	}

	public M setWbtaskstatusText(String wbtaskstatusText) {
		set("wbTaskStatus_text", wbtaskstatusText);
		return (M)this;
	}

	public String getWbtaskstatusText() {
		return getStr("wbTaskStatus_text");
	}

	public M setWbtaskstatusValue(String wbtaskstatusValue) {
		set("wbTaskStatus_value", wbtaskstatusValue);
		return (M)this;
	}

	public String getWbtaskstatusValue() {
		return getStr("wbTaskStatus_value");
	}

	public M setZsbh(String zsbh) {
		set("zsbh", zsbh);
		return (M)this;
	}

	public String getZsbh() {
		return getStr("zsbh");
	}

	public M setTreeinfoPid(String treeinfoPid) {
		set("treeinfo_pid", treeinfoPid);
		return (M)this;
	}

	public String getTreeinfoPid() {
		return getStr("treeinfo_pid");
	}

	public M setTreeinfoIcon(String treeinfoIcon) {
		set("treeinfo_icon", treeinfoIcon);
		return (M)this;
	}

	public String getTreeinfoIcon() {
		return getStr("treeinfo_icon");
	}

	public M setTreeinfoGlobalid(String treeinfoGlobalid) {
		set("treeinfo_globalid", treeinfoGlobalid);
		return (M)this;
	}

	public String getTreeinfoGlobalid() {
		return getStr("treeinfo_globalid");
	}

	public M setTreeinfoLevel(java.math.BigDecimal treeinfoLevel) {
		set("treeinfo_level", treeinfoLevel);
		return (M)this;
	}

	public java.math.BigDecimal getTreeinfoLevel() {
		return get("treeinfo_level");
	}

	public M setTreeinfoType(String treeinfoType) {
		set("treeinfo_type", treeinfoType);
		return (M)this;
	}

	public String getTreeinfoType() {
		return getStr("treeinfo_type");
	}

	public M setBranchid(String branchid) {
		set("branchid", branchid);
		return (M)this;
	}

	public String getBranchid() {
		return getStr("branchid");
	}

	public M setZmc(String zmc) {
		set("zmc", zmc);
		return (M)this;
	}

	public String getZmc() {
		return getStr("zmc");
	}

	public M setZbh(java.math.BigDecimal zbh) {
		set("zbh", zbh);
		return (M)this;
	}

	public java.math.BigDecimal getZbh() {
		return get("zbh");
	}

	public M setRelname(String relname) {
		set("relname", relname);
		return (M)this;
	}

	public String getRelname() {
		return getStr("relname");
	}

	public M setWbimorder(String wbimorder) {
		set("wbimorder", wbimorder);
		return (M)this;
	}

	public String getWbimorder() {
		return getStr("wbimorder");
	}

	public M setHrjzsj(java.util.Date hrjzsj) {
		set("hrjzsj", hrjzsj);
		return (M)this;
	}

	public java.util.Date getHrjzsj() {
		return getDate("hrjzsj");
	}

	public M setIsxzxsText(String isxzxsText) {
		set("isxzxs_text", isxzxsText);
		return (M)this;
	}

	public String getIsxzxsText() {
		return getStr("isxzxs_text");
	}

	public M setIsxzxsValue(String isxzxsValue) {
		set("isxzxs_value", isxzxsValue);
		return (M)this;
	}

	public String getIsxzxsValue() {
		return getStr("isxzxs_value");
	}

	public M setCampusText(String campusText) {
		set("campus_text", campusText);
		return (M)this;
	}

	public String getCampusText() {
		return getStr("campus_text");
	}

	public M setCampusValue(String campusValue) {
		set("campus_value", campusValue);
		return (M)this;
	}

	public String getCampusValue() {
		return getStr("campus_value");
	}

	public M setJfjzsj(java.util.Date jfjzsj) {
		set("jfjzsj", jfjzsj);
		return (M)this;
	}

	public java.util.Date getJfjzsj() {
		return getDate("jfjzsj");
	}

	public M setPersonSignupQrcode(String personSignupQrcode) {
		set("person_signup_qrcode", personSignupQrcode);
		return (M)this;
	}

	public String getPersonSignupQrcode() {
		return getStr("person_signup_qrcode");
	}

	public M setBz(String bz) {
		set("bz", bz);
		return (M)this;
	}

	public String getBz() {
		return getStr("bz");
	}

	public M setWbTypeText(String wbTypeText) {
		set("wb_type_text", wbTypeText);
		return (M)this;
	}

	public String getWbTypeText() {
		return getStr("wb_type_text");
	}

	public M setWbTypeValue(String wbTypeValue) {
		set("wb_type_value", wbTypeValue);
		return (M)this;
	}

	public String getWbTypeValue() {
		return getStr("wb_type_value");
	}

	public M setMealAttendQrcode(String mealAttendQrcode) {
		set("meal_attend_qrcode", mealAttendQrcode);
		return (M)this;
	}

	public String getMealAttendQrcode() {
		return getStr("meal_attend_qrcode");
	}

	public M setRegDate(java.util.Date regDate) {
		set("reg_date", regDate);
		return (M)this;
	}

	public java.util.Date getRegDate() {
		return getDate("reg_date");
	}

	public M setBefroeapplytimeSdate(java.util.Date befroeapplytimeSdate) {
		set("befroeapplytime_sdate", befroeapplytimeSdate);
		return (M)this;
	}

	public java.util.Date getBefroeapplytimeSdate() {
		return getDate("befroeapplytime_sdate");
	}

	public M setBefroeapplytimeEdate(java.util.Date befroeapplytimeEdate) {
		set("befroeapplytime_edate", befroeapplytimeEdate);
		return (M)this;
	}

	public java.util.Date getBefroeapplytimeEdate() {
		return getDate("befroeapplytime_edate");
	}

	public M setHsf(String hsf) {
		set("hsf", hsf);
		return (M)this;
	}

	public String getHsf() {
		return getStr("hsf");
	}

	public M setShsjSdate(java.util.Date shsjSdate) {
		set("shsj_sdate", shsjSdate);
		return (M)this;
	}

	public java.util.Date getShsjSdate() {
		return getDate("shsj_sdate");
	}

	public M setShsjEdate(java.util.Date shsjEdate) {
		set("shsj_edate", shsjEdate);
		return (M)this;
	}

	public java.util.Date getShsjEdate() {
		return getDate("shsj_edate");
	}

	public M setBdddText(String bdddText) {
		set("bddd_text", bdddText);
		return (M)this;
	}

	public String getBdddText() {
		return getStr("bddd_text");
	}

	public M setBdddValue(String bdddValue) {
		set("bddd_value", bdddValue);
		return (M)this;
	}

	public String getBdddValue() {
		return getStr("bddd_value");
	}

	public M setRxtzStatusText(String rxtzStatusText) {
		set("rxtz_status_text", rxtzStatusText);
		return (M)this;
	}

	public String getRxtzStatusText() {
		return getStr("rxtz_status_text");
	}

	public M setRxtzStatusValue(String rxtzStatusValue) {
		set("rxtz_status_value", rxtzStatusValue);
		return (M)this;
	}

	public String getRxtzStatusValue() {
		return getStr("rxtz_status_value");
	}

	public M setGxzh(String gxzh) {
		set("gxzh", gxzh);
		return (M)this;
	}

	public String getGxzh() {
		return getStr("gxzh");
	}

	public M setZzyText(String zzyText) {
		set("zzy_text", zzyText);
		return (M)this;
	}

	public String getZzyText() {
		return getStr("zzy_text");
	}

	public M setZzyValue(String zzyValue) {
		set("zzy_value", zzyValue);
		return (M)this;
	}

	public String getZzyValue() {
		return getStr("zzy_value");
	}

	public M setPxf(String pxf) {
		set("pxf", pxf);
		return (M)this;
	}

	public String getPxf() {
		return getStr("pxf");
	}

	public M setStatusText(String statusText) {
		set("status_text", statusText);
		return (M)this;
	}

	public String getStatusText() {
		return getStr("status_text");
	}

	public M setStatusValue(String statusValue) {
		set("status_value", statusValue);
		return (M)this;
	}

	public String getStatusValue() {
		return getStr("status_value");
	}

	public M setPxnr(String pxnr) {
		set("pxnr", pxnr);
		return (M)this;
	}

	public String getPxnr() {
		return getStr("pxnr");
	}

	public M setXjdabh(String xjdabh) {
		set("xjdabh", xjdabh);
		return (M)this;
	}

	public String getXjdabh() {
		return getStr("xjdabh");
	}

	public M setJhrs(String jhrs) {
		set("jhrs", jhrs);
		return (M)this;
	}

	public String getJhrs() {
		return getStr("jhrs");
	}

	public M setPxbz(String pxbz) {
		set("pxbz", pxbz);
		return (M)this;
	}

	public String getPxbz() {
		return getStr("pxbz");
	}

	public M setSjrsm(String sjrsm) {
		set("sjrsm", sjrsm);
		return (M)this;
	}

	public String getSjrsm() {
		return getStr("sjrsm");
	}

	public M setSjrsw(String sjrsw) {
		set("sjrsw", sjrsw);
		return (M)this;
	}

	public String getSjrsw() {
		return getStr("sjrsw");
	}

	public M setBcxzText(String bcxzText) {
		set("bcxz_text", bcxzText);
		return (M)this;
	}

	public String getBcxzText() {
		return getStr("bcxz_text");
	}

	public M setBcxzValue(String bcxzValue) {
		set("bcxz_value", bcxzValue);
		return (M)this;
	}

	public String getBcxzValue() {
		return getStr("bcxz_value");
	}

	public M setKcszrText(String kcszrText) {
		set("kcszr_text", kcszrText);
		return (M)this;
	}

	public String getKcszrText() {
		return getStr("kcszr_text");
	}

	public M setKcszrValue(String kcszrValue) {
		set("kcszr_value", kcszrValue);
		return (M)this;
	}

	public String getKcszrValue() {
		return getStr("kcszr_value");
	}

	public M setXzllyText(String xzllyText) {
		set("xzlly_text", xzllyText);
		return (M)this;
	}

	public String getXzllyText() {
		return getStr("xzlly_text");
	}

	public M setXzllyValue(String xzllyValue) {
		set("xzlly_value", xzllyValue);
		return (M)this;
	}

	public String getXzllyValue() {
		return getStr("xzlly_value");
	}

	public M setUpxzfile(String upxzfile) {
		set("upxzfile", upxzfile);
		return (M)this;
	}

	public String getUpxzfile() {
		return getStr("upxzfile");
	}

	public M setXzyts(String xzyts) {
		set("xzyts", xzyts);
		return (M)this;
	}

	public String getXzyts() {
		return getStr("xzyts");
	}

	public M setZzyzlText(String zzyzlText) {
		set("zzyzl_text", zzyzlText);
		return (M)this;
	}

	public String getZzyzlText() {
		return getStr("zzyzl_text");
	}

	public M setZzyzlValue(String zzyzlValue) {
		set("zzyzl_value", zzyzlValue);
		return (M)this;
	}

	public String getZzyzlValue() {
		return getStr("zzyzl_value");
	}

	public M setGroupLeaderText(String groupLeaderText) {
		set("group_leader_text", groupLeaderText);
		return (M)this;
	}

	public String getGroupLeaderText() {
		return getStr("group_leader_text");
	}

	public M setGroupLeaderValue(String groupLeaderValue) {
		set("group_leader_value", groupLeaderValue);
		return (M)this;
	}

	public String getGroupLeaderValue() {
		return getStr("group_leader_value");
	}

	public M setBjjc(String bjjc) {
		set("bjjc", bjjc);
		return (M)this;
	}

	public String getBjjc() {
		return getStr("bjjc");
	}

	public M setAdmissionNotice(String admissionNotice) {
		set("admissionNotice", admissionNotice);
		return (M)this;
	}

	public String getAdmissionNotice() {
		return getStr("admissionNotice");
	}

	public M setZq(String zq) {
		set("zq", zq);
		return (M)this;
	}

	public String getZq() {
		return getStr("zq");
	}

	public M setGzrys(String gzrys) {
		set("gzrys", gzrys);
		return (M)this;
	}

	public String getGzrys() {
		return getStr("gzrys");
	}

	public M setBoxNumber(String boxNumber) {
		set("boxNumber", boxNumber);
		return (M)this;
	}

	public String getBoxNumber() {
		return getStr("boxNumber");
	}

	public M setXbryText(String xbryText) {
		set("xbry_text", xbryText);
		return (M)this;
	}

	public String getXbryText() {
		return getStr("xbry_text");
	}

	public M setXbryValue(String xbryValue) {
		set("xbry_value", xbryValue);
		return (M)this;
	}

	public String getXbryValue() {
		return getStr("xbry_value");
	}

	public M setPxdx(String pxdx) {
		set("pxdx", pxdx);
		return (M)this;
	}

	public String getPxdx() {
		return getStr("pxdx");
	}

	public M setUpjxdg(String upjxdg) {
		set("upjxdg", upjxdg);
		return (M)this;
	}

	public String getUpjxdg() {
		return getStr("upjxdg");
	}

	public M setXgcl(String xgcl) {
		set("xgcl", xgcl);
		return (M)this;
	}

	public String getXgcl() {
		return getStr("xgcl");
	}

	public M setLogFlag(String logFlag) {
		set("logFlag", logFlag);
		return (M)this;
	}

	public String getLogFlag() {
		return getStr("logFlag");
	}

	public M setOutFlag(String outFlag) {
		set("outFlag", outFlag);
		return (M)this;
	}

	public String getOutFlag() {
		return getStr("outFlag");
	}

	public M setBm(String bm) {
		set("bm", bm);
		return (M)this;
	}

	public String getBm() {
		return getStr("bm");
	}

	public M setLxr(String lxr) {
		set("lxr", lxr);
		return (M)this;
	}

	public String getLxr() {
		return getStr("lxr");
	}

	public M setWtzjdwText(String wtzjdwText) {
		set("wtzjdw_text", wtzjdwText);
		return (M)this;
	}

	public String getWtzjdwText() {
		return getStr("wtzjdw_text");
	}

	public M setWtzjdwValue(String wtzjdwValue) {
		set("wtzjdw_value", wtzjdwValue);
		return (M)this;
	}

	public String getWtzjdwValue() {
		return getStr("wtzjdw_value");
	}

	public M setZw(String zw) {
		set("zw", zw);
		return (M)this;
	}

	public String getZw() {
		return getStr("zw");
	}

	public M setFzbmText(String fzbmText) {
		set("fzbm_text", fzbmText);
		return (M)this;
	}

	public String getFzbmText() {
		return getStr("fzbm_text");
	}

	public M setFzbmValue(String fzbmValue) {
		set("fzbm_value", fzbmValue);
		return (M)this;
	}

	public String getFzbmValue() {
		return getStr("fzbm_value");
	}

	public M setXyjbText(String xyjbText) {
		set("xyjb_text", xyjbText);
		return (M)this;
	}

	public String getXyjbText() {
		return getStr("xyjb_text");
	}

	public M setXyjbValue(String xyjbValue) {
		set("xyjb_value", xyjbValue);
		return (M)this;
	}

	public String getXyjbValue() {
		return getStr("xyjb_value");
	}

	public M setLxdh(String lxdh) {
		set("lxdh", lxdh);
		return (M)this;
	}

	public String getLxdh() {
		return getStr("lxdh");
	}

	public M setBjtxlText(String bjtxlText) {
		set("bjtxl_text", bjtxlText);
		return (M)this;
	}

	public String getBjtxlText() {
		return getStr("bjtxl_text");
	}

	public M setBjtxlValue(String bjtxlValue) {
		set("bjtxl_value", bjtxlValue);
		return (M)this;
	}

	public String getBjtxlValue() {
		return getStr("bjtxl_value");
	}

	public M setHoldLocationText(String holdLocationText) {
		set("hold_location_text", holdLocationText);
		return (M)this;
	}

	public String getHoldLocationText() {
		return getStr("hold_location_text");
	}

	public M setHoldLocationValue(String holdLocationValue) {
		set("hold_location_value", holdLocationValue);
		return (M)this;
	}

	public String getHoldLocationValue() {
		return getStr("hold_location_value");
	}

	public M setAddItemSum(java.math.BigDecimal addItemSum) {
		set("add_item_sum", addItemSum);
		return (M)this;
	}

	public java.math.BigDecimal getAddItemSum() {
		return get("add_item_sum");
	}

	public M setPerCostText(String perCostText) {
		set("per_cost_text", perCostText);
		return (M)this;
	}

	public String getPerCostText() {
		return getStr("per_cost_text");
	}

	public M setPerCostValue(String perCostValue) {
		set("per_cost_value", perCostValue);
		return (M)this;
	}

	public String getPerCostValue() {
		return getStr("per_cost_value");
	}

	public M setCostExplain(String costExplain) {
		set("cost_explain", costExplain);
		return (M)this;
	}

	public String getCostExplain() {
		return getStr("cost_explain");
	}

	public M setCostSum(java.math.BigDecimal costSum) {
		set("cost_sum", costSum);
		return (M)this;
	}

	public java.math.BigDecimal getCostSum() {
		return get("cost_sum");
	}

	public M setOtherExplain(String otherExplain) {
		set("other_explain", otherExplain);
		return (M)this;
	}

	public String getOtherExplain() {
		return getStr("other_explain");
	}

	public M setXyjb(String xyjb) {
		set("xyjb", xyjb);
		return (M)this;
	}

	public String getXyjb() {
		return getStr("xyjb");
	}

	public M setSjts(String sjts) {
		set("sjts", sjts);
		return (M)this;
	}

	public String getSjts() {
		return getStr("sjts");
	}

	public M setDzflText(String dzflText) {
		set("dzfl_text", dzflText);
		return (M)this;
	}

	public String getDzflText() {
		return getStr("dzfl_text");
	}

	public M setDzflValue(String dzflValue) {
		set("dzfl_value", dzflValue);
		return (M)this;
	}

	public String getDzflValue() {
		return getStr("dzfl_value");
	}

	public M setFyjsbid(String fyjsbid) {
		set("fyjsbid", fyjsbid);
		return (M)this;
	}

	public String getFyjsbid() {
		return getStr("fyjsbid");
	}

	public M setWfinfoWfId(String wfinfoWfId) {
		set("wfinfo_wf_id", wfinfoWfId);
		return (M)this;
	}

	public String getWfinfoWfId() {
		return getStr("wfinfo_wf_id");
	}

	public M setWfinfoWfName(String wfinfoWfName) {
		set("wfinfo_wf_name", wfinfoWfName);
		return (M)this;
	}

	public String getWfinfoWfName() {
		return getStr("wfinfo_wf_name");
	}

	public M setWfinfoWfPid(String wfinfoWfPid) {
		set("wfinfo_wf_pid", wfinfoWfPid);
		return (M)this;
	}

	public String getWfinfoWfPid() {
		return getStr("wfinfo_wf_pid");
	}

	public M setWfinfoWfDeptid(String wfinfoWfDeptid) {
		set("wfinfo_wf_deptid", wfinfoWfDeptid);
		return (M)this;
	}

	public String getWfinfoWfDeptid() {
		return getStr("wfinfo_wf_deptid");
	}

	public M setWfinfoWfDeptname(String wfinfoWfDeptname) {
		set("wfinfo_wf_deptname", wfinfoWfDeptname);
		return (M)this;
	}

	public String getWfinfoWfDeptname() {
		return getStr("wfinfo_wf_deptname");
	}

	public M setWfinfoWfUserid(String wfinfoWfUserid) {
		set("wfinfo_wf_userid", wfinfoWfUserid);
		return (M)this;
	}

	public String getWfinfoWfUserid() {
		return getStr("wfinfo_wf_userid");
	}

	public M setWfinfoWfUsername(String wfinfoWfUsername) {
		set("wfinfo_wf_username", wfinfoWfUsername);
		return (M)this;
	}

	public String getWfinfoWfUsername() {
		return getStr("wfinfo_wf_username");
	}

	public M setWfinfoWfCreatetime(java.util.Date wfinfoWfCreatetime) {
		set("wfinfo_wf_createtime", wfinfoWfCreatetime);
		return (M)this;
	}

	public java.util.Date getWfinfoWfCreatetime() {
		return getDate("wfinfo_wf_createtime");
	}

	public M setWfinfoWfStatus(java.math.BigDecimal wfinfoWfStatus) {
		set("wfinfo_wf_status", wfinfoWfStatus);
		return (M)this;
	}

	public java.math.BigDecimal getWfinfoWfStatus() {
		return get("wfinfo_wf_status");
	}

	public M setWfinfoWfDeadline(java.util.Date wfinfoWfDeadline) {
		set("wfinfo_wf_deadLine", wfinfoWfDeadline);
		return (M)this;
	}

	public java.util.Date getWfinfoWfDeadline() {
		return getDate("wfinfo_wf_deadLine");
	}

	public M setJxjhFile(String jxjhFile) {
		set("jxjh_file", jxjhFile);
		return (M)this;
	}

	public String getJxjhFile() {
		return getStr("jxjh_file");
	}

	public M setSeatpdf(String seatpdf) {
		set("seatpdf", seatpdf);
		return (M)this;
	}

	public String getSeatpdf() {
		return getStr("seatpdf");
	}

	public M setAbstract(String _abstract) {
		set("abstract", _abstract);
		return (M)this;
	}

	public String getAbstract() {
		return getStr("abstract");
	}

	public M setLabelsText(String labelsText) {
		set("labels_text", labelsText);
		return (M)this;
	}

	public String getLabelsText() {
		return getStr("labels_text");
	}

	public M setLabelsValue(String labelsValue) {
		set("labels_value", labelsValue);
		return (M)this;
	}

	public String getLabelsValue() {
		return getStr("labels_value");
	}

	public M setTypeText(String typeText) {
		set("type_text", typeText);
		return (M)this;
	}

	public String getTypeText() {
		return getStr("type_text");
	}

	public M setTypeValue(String typeValue) {
		set("type_value", typeValue);
		return (M)this;
	}

	public String getTypeValue() {
		return getStr("type_value");
	}

	public M setContent(String content) {
		set("content", content);
		return (M)this;
	}

	public String getContent() {
		return getStr("content");
	}

	public M setCover(String cover) {
		set("cover", cover);
		return (M)this;
	}

	public String getCover() {
		return getStr("cover");
	}

	public M setDingIsgroupchatText(String dingIsgroupchatText) {
		set("ding_isgroupchat_text", dingIsgroupchatText);
		return (M)this;
	}

	public String getDingIsgroupchatText() {
		return getStr("ding_isgroupchat_text");
	}

	public M setDingIsgroupchatValue(String dingIsgroupchatValue) {
		set("ding_isgroupchat_value", dingIsgroupchatValue);
		return (M)this;
	}

	public String getDingIsgroupchatValue() {
		return getStr("ding_isgroupchat_value");
	}

	public M setDingIsscheduleText(String dingIsscheduleText) {
		set("ding_isschedule_text", dingIsscheduleText);
		return (M)this;
	}

	public String getDingIsscheduleText() {
		return getStr("ding_isschedule_text");
	}

	public M setDingIsscheduleValue(String dingIsscheduleValue) {
		set("ding_isschedule_value", dingIsscheduleValue);
		return (M)this;
	}

	public String getDingIsscheduleValue() {
		return getStr("ding_isschedule_value");
	}

	public M setDingIsbacklogText(String dingIsbacklogText) {
		set("ding_isbacklog_text", dingIsbacklogText);
		return (M)this;
	}

	public String getDingIsbacklogText() {
		return getStr("ding_isbacklog_text");
	}

	public M setDingChatname(String dingChatname) {
		set("ding_chatName", dingChatname);
		return (M)this;
	}

	public String getDingChatname() {
		return getStr("ding_chatName");
	}

	public M setDingIsbacklogValue(String dingIsbacklogValue) {
		set("ding_isbacklog_value", dingIsbacklogValue);
		return (M)this;
	}

	public String getDingIsbacklogValue() {
		return getStr("ding_isbacklog_value");
	}

	public M setBxryxs(String bxryxs) {
		set("bxryxs", bxryxs);
		return (M)this;
	}

	public String getBxryxs() {
		return getStr("bxryxs");
	}

	public M setXxryms(String xxryms) {
		set("xxryms", xxryms);
		return (M)this;
	}

	public String getXxryms() {
		return getStr("xxryms");
	}

	public M setXxryxs(String xxryxs) {
		set("xxryxs", xxryxs);
		return (M)this;
	}

	public String getXxryxs() {
		return getStr("xxryxs");
	}

	public M setBxryms(String bxryms) {
		set("bxryms", bxryms);
		return (M)this;
	}

	public String getBxryms() {
		return getStr("bxryms");
	}

	public M setCdpkText(String cdpkText) {
		set("cdpk_text", cdpkText);
		return (M)this;
	}

	public String getCdpkText() {
		return getStr("cdpk_text");
	}

	public M setCdpkValue(String cdpkValue) {
		set("cdpk_value", cdpkValue);
		return (M)this;
	}

	public String getCdpkValue() {
		return getStr("cdpk_value");
	}

	public M setJcapText(String jcapText) {
		set("jcap_text", jcapText);
		return (M)this;
	}

	public String getJcapText() {
		return getStr("jcap_text");
	}

	public M setJcapValue(String jcapValue) {
		set("jcap_value", jcapValue);
		return (M)this;
	}

	public String getJcapValue() {
		return getStr("jcap_value");
	}

	public M setJtlx(String jtlx) {
		set("jtlx", jtlx);
		return (M)this;
	}

	public String getJtlx() {
		return getStr("jtlx");
	}

	public M setZsapText(String zsapText) {
		set("zsap_text", zsapText);
		return (M)this;
	}

	public String getZsapText() {
		return getStr("zsap_text");
	}

	public M setZsapValue(String zsapValue) {
		set("zsap_value", zsapValue);
		return (M)this;
	}

	public String getZsapValue() {
		return getStr("zsap_value");
	}

	public M setSszcbm(String sszcbm) {
		set("sszcbm", sszcbm);
		return (M)this;
	}

	public String getSszcbm() {
		return getStr("sszcbm");
	}

	public M setCoverPhoto(String coverPhoto) {
		set("cover_photo", coverPhoto);
		return (M)this;
	}

	public String getCoverPhoto() {
		return getStr("cover_photo");
	}

	public M setCoverConver(String coverConver) {
		set("cover_conver", coverConver);
		return (M)this;
	}

	public String getCoverConver() {
		return getStr("cover_conver");
	}

	public M setApplyAuditValue(String applyAuditValue) {
		set("apply_audit_value", applyAuditValue);
		return (M)this;
	}

	public String getApplyAuditValue() {
		return getStr("apply_audit_value");
	}

	public M setApplyAuditText(String applyAuditText) {
		set("apply_audit_text", applyAuditText);
		return (M)this;
	}

	public String getApplyAuditText() {
		return getStr("apply_audit_text");
	}

	public M setSxBj(java.math.BigDecimal sxBj) {
		set("sx_bj", sxBj);
		return (M)this;
	}

	public java.math.BigDecimal getSxBj() {
		return get("sx_bj");
	}

	public M setSkdd2Text(String skdd2Text) {
		set("skdd2_text", skdd2Text);
		return (M)this;
	}

	public String getSkdd2Text() {
		return getStr("skdd2_text");
	}
	
	public M setFilledDate(java.util.Date filledDate) {
		set("filled_date", filledDate);
		return (M)this;
	}
	
	public java.util.Date getFilledDate() {
		return getDate("filled_date");
	}
	
	public M setSxHhtf(java.math.BigDecimal sxHhtf) {
		set("sx_hhtf", sxHhtf);
		return (M)this;
	}
	
	public java.math.BigDecimal getSxHhtf() {
		return get("sx_hhtf");
	}
	
	public M setPmStart(java.sql.Time pmStart) {
		set("pm_start", pmStart);
		return (M)this;
	}
	
	public java.sql.Time getPmStart() {
		return get("pm_start");
	}
	
	public M setWsNlbj(java.math.BigDecimal wsNlbj) {
		set("ws_nlbj", wsNlbj);
		return (M)this;
	}
	
	public java.math.BigDecimal getWsNlbj() {
		return get("ws_nlbj");
	}
	
	public M setWsTj(java.math.BigDecimal wsTj) {
		set("ws_tj", wsTj);
		return (M)this;
	}
	
	public java.math.BigDecimal getWsTj() {
		return get("ws_tj");
	}
	
	public M setBaseCost(java.math.BigDecimal baseCost) {
		set("base_cost", baseCost);
		return (M)this;
	}
	
	public java.math.BigDecimal getBaseCost() {
		return get("base_cost");
	}
	
	public M setWsDj(java.math.BigDecimal wsDj) {
		set("ws_dj", wsDj);
		return (M)this;
	}
	
	public java.math.BigDecimal getWsDj() {
		return get("ws_dj");
	}
	
	public M setWxTjone(java.math.BigDecimal wxTjone) {
		set("wx_tjone", wxTjone);
		return (M)this;
	}
	
	public java.math.BigDecimal getWxTjone() {
		return get("wx_tjone");
	}
	
	public M setWxBjtwo(java.math.BigDecimal wxBjtwo) {
		set("wx_bjtwo", wxBjtwo);
		return (M)this;
	}
	
	public java.math.BigDecimal getWxBjtwo() {
		return get("wx_bjtwo");
	}
	
	public M setAmStart(java.sql.Time amStart) {
		set("am_start", amStart);
		return (M)this;
	}
	
	public java.sql.Time getAmStart() {
		return get("am_start");
	}
	
	public M setXsBj(java.math.BigDecimal xsBj) {
		set("xs_bj", xsBj);
		return (M)this;
	}
	
	public java.math.BigDecimal getXsBj() {
		return get("xs_bj");
	}
	
	public M setWxDjone(java.math.BigDecimal wxDjone) {
		set("wx_djone", wxDjone);
		return (M)this;
	}
	
	public java.math.BigDecimal getWxDjone() {
		return get("wx_djone");
	}
	
	public M setSxDj(java.math.BigDecimal sxDj) {
		set("sx_dj", sxDj);
		return (M)this;
	}
	
	public java.math.BigDecimal getSxDj() {
		return get("sx_dj");
	}
	
}

