package com.dsfa.nc.pd.lesson.specialClass.persistence.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBjglFlowTest<M extends BaseBjglFlowTest<M>> extends Model<M> implements IBean {

	public M setTeasJwglBjglFlowTestId(String teasJwglBjglFlowTestId) {
		set("teas_jwgl_bjgl_flow_test_id", teasJwglBjglFlowTestId);
		return (M)this;
	}

	public String getTeasJwglBjglFlowTestId() {
		return getStr("teas_jwgl_bjgl_flow_test_id");
	}

	public M setDsUpdateUserId(String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}

	public String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}

	public M setDsDeptId(String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}

	public String getDsDeptId() {
		return getStr("ds_dept_id");
	}

	public M setDsCreateUserName(String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}

	public String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}

	public M setDsCreateUserId(String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}

	public String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}

	public M setDsUpdateUserName(String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}

	public String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}

	public M setDsDeleted(String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}

	public String getDsDeleted() {
		return getStr("ds_deleted");
	}

	public M setDsOrder(Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}

	public Integer getDsOrder() {
		return getInt("ds_order");
	}

	public M setDsUnitId(String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}

	public String getDsUnitId() {
		return getStr("ds_unit_id");
	}

	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}

	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}

	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}

	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}

	public M setWfinfoWfId(String wfinfoWfId) {
		set("wfinfo_wf_id", wfinfoWfId);
		return (M)this;
	}

	public String getWfinfoWfId() {
		return getStr("wfinfo_wf_id");
	}

	public M setWfinfoWfName(String wfinfoWfName) {
		set("wfinfo_wf_name", wfinfoWfName);
		return (M)this;
	}

	public String getWfinfoWfName() {
		return getStr("wfinfo_wf_name");
	}

	public M setObjectname(String objectname) {
		set("objectname", objectname);
		return (M)this;
	}

	public String getObjectname() {
		return getStr("objectname");
	}

	public M setPoint(String point) {
		set("point", point);
		return (M)this;
	}

	public String getPoint() {
		return getStr("point");
	}
	
}

