package com.dsfa.nc.pd.lesson.specialClass.persistence.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBjglBzrinfo<M extends BaseBjglBzrinfo<M>> extends Model<M> implements IBean {

	public M setTeasJwglBjglBzrinfoId(String teasJwglBjglBzrinfoId) {
		set("teas_jwgl_bjgl_bzrinfo_id", teasJwglBjglBzrinfoId);
		return (M)this;
	}

	public String getTeasJwglBjglBzrinfoId() {
		return getStr("teas_jwgl_bjgl_bzrinfo_id");
	}

	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}

	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}

	public M setDsCreateUserId(String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}

	public String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}

	public M setDsUpdateUserId(String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}

	public String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}

	public M setDsOrder(java.math.BigDecimal dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}

	public java.math.BigDecimal getDsOrder() {
		return get("ds_order");
	}

	public M setDsDeleted(String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}

	public String getDsDeleted() {
		return getStr("ds_deleted");
	}

	public M setDsUpdateUserName(String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}

	public String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}

	public M setDsCreateUserName(String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}

	public String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}

	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}

	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}

	public M setDsUnitId(String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}

	public String getDsUnitId() {
		return getStr("ds_unit_id");
	}

	public M setTeasJwglBjglId(String teasJwglBjglId) {
		set("teas_jwgl_bjgl_id", teasJwglBjglId);
		return (M)this;
	}

	public String getTeasJwglBjglId() {
		return getStr("teas_jwgl_bjgl_id");
	}

	public M setBzrname(String bzrname) {
		set("bzrname", bzrname);
		return (M)this;
	}

	public String getBzrname() {
		return getStr("bzrname");
	}

	public M setBzrid(String bzrid) {
		set("bzrid", bzrid);
		return (M)this;
	}

	public String getBzrid() {
		return getStr("bzrid");
	}

	public M setBzrdh(String bzrdh) {
		set("bzrdh", bzrdh);
		return (M)this;
	}

	public String getBzrdh() {
		return getStr("bzrdh");
	}

	public M setBcmc(String bcmc) {
		set("bcmc", bcmc);
		return (M)this;
	}

	public String getBcmc() {
		return getStr("bcmc");
	}

	public M setDsDeptId(String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}

	public String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
}

