package com.dsfa.nc.pd.lesson.specialClass.persistence.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBjglMealDemand<M extends BaseBjglMealDemand<M>> extends Model<M> implements IBean {

	public M setTeasJwglBjglMealDemandId(String teasJwglBjglMealDemandId) {
		set("teas_jwgl_bjgl_meal_demand_id", teasJwglBjglMealDemandId);
		return (M)this;
	}

	public String getTeasJwglBjglMealDemandId() {
		return getStr("teas_jwgl_bjgl_meal_demand_id");
	}

	public M setDsUpdateUserId(String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}

	public String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}

	public M setDsDeptId(String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}

	public String getDsDeptId() {
		return getStr("ds_dept_id");
	}

	public M setDsCreateUserName(String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}

	public String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}

	public M setDsCreateUserId(String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}

	public String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}

	public M setDsUpdateUserName(String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}

	public String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}

	public M setDsDeleted(String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}

	public String getDsDeleted() {
		return getStr("ds_deleted");
	}

	public M setDsOrder(Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}

	public Integer getDsOrder() {
		return getInt("ds_order");
	}

	public M setDsUnitId(String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}

	public String getDsUnitId() {
		return getStr("ds_unit_id");
	}

	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}

	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}

	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}

	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}

	public M setTeasJwglBjglId(String teasJwglBjglId) {
		set("teas_jwgl_bjgl_id", teasJwglBjglId);
		return (M)this;
	}

	public String getTeasJwglBjglId() {
		return getStr("teas_jwgl_bjgl_id");
	}

	public M setDinnerText(String dinnerText) {
		set("dinner_text", dinnerText);
		return (M)this;
	}

	public String getDinnerText() {
		return getStr("dinner_text");
	}

	public M setDinnerValue(String dinnerValue) {
		set("dinner_value", dinnerValue);
		return (M)this;
	}

	public String getDinnerValue() {
		return getStr("dinner_value");
	}

	public M setLunchSelfStandardText(String lunchSelfStandardText) {
		set("lunch_self_standard_text", lunchSelfStandardText);
		return (M)this;
	}

	public String getLunchSelfStandardText() {
		return getStr("lunch_self_standard_text");
	}

	public M setLunchSelfStandardValue(String lunchSelfStandardValue) {
		set("lunch_self_standard_value", lunchSelfStandardValue);
		return (M)this;
	}

	public String getLunchSelfStandardValue() {
		return getStr("lunch_self_standard_value");
	}

	public M setLunchTableStandard(String lunchTableStandard) {
		set("lunch_table_standard", lunchTableStandard);
		return (M)this;
	}

	public String getLunchTableStandard() {
		return getStr("lunch_table_standard");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}

	public java.util.Date getDate() {
		return getDate("date");
	}

	public M setLunchTypeText(String lunchTypeText) {
		set("lunch_type_text", lunchTypeText);
		return (M)this;
	}

	public String getLunchTypeText() {
		return getStr("lunch_type_text");
	}

	public M setLunchTypeValue(String lunchTypeValue) {
		set("lunch_type_value", lunchTypeValue);
		return (M)this;
	}

	public String getLunchTypeValue() {
		return getStr("lunch_type_value");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

	public M setLunchText(String lunchText) {
		set("lunch_text", lunchText);
		return (M)this;
	}

	public String getLunchText() {
		return getStr("lunch_text");
	}

	public M setLunchValue(String lunchValue) {
		set("lunch_value", lunchValue);
		return (M)this;
	}

	public String getLunchValue() {
		return getStr("lunch_value");
	}

	public M setDinnerTypeText(String dinnerTypeText) {
		set("dinner_type_text", dinnerTypeText);
		return (M)this;
	}

	public String getDinnerTypeText() {
		return getStr("dinner_type_text");
	}

	public M setDinnerTypeValue(String dinnerTypeValue) {
		set("dinner_type_value", dinnerTypeValue);
		return (M)this;
	}

	public String getDinnerTypeValue() {
		return getStr("dinner_type_value");
	}

	public M setDinnerTableNum(String dinnerTableNum) {
		set("dinner_table_num", dinnerTableNum);
		return (M)this;
	}

	public String getDinnerTableNum() {
		return getStr("dinner_table_num");
	}

	public M setDinnerTableStandard(String dinnerTableStandard) {
		set("dinner_table_standard", dinnerTableStandard);
		return (M)this;
	}

	public String getDinnerTableStandard() {
		return getStr("dinner_table_standard");
	}

	public M setDinnerSelfStandardText(String dinnerSelfStandardText) {
		set("dinner_self_standard_text", dinnerSelfStandardText);
		return (M)this;
	}

	public String getDinnerSelfStandardText() {
		return getStr("dinner_self_standard_text");
	}

	public M setDinnerSelfStandardValue(String dinnerSelfStandardValue) {
		set("dinner_self_standard_value", dinnerSelfStandardValue);
		return (M)this;
	}

	public String getDinnerSelfStandardValue() {
		return getStr("dinner_self_standard_value");
	}

	public M setLunchTableNum(String lunchTableNum) {
		set("lunch_table_num", lunchTableNum);
		return (M)this;
	}

	public String getLunchTableNum() {
		return getStr("lunch_table_num");
	}
	
}

