package com.dsfa.nc.pd.lesson.specialClass.persistence.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBjglXyxx<M extends BaseBjglXyxx<M>> extends Model<M> implements IBean {

	public M setTeasJwglBjglXyxxId(String teasJwglBjglXyxxId) {
		set("teas_jwgl_bjgl_xyxx_id", teasJwglBjglXyxxId);
		return (M)this;
	}

	public String getTeasJwglBjglXyxxId() {
		return getStr("teas_jwgl_bjgl_xyxx_id");
	}

	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}

	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}

	public M setDsCreateUserId(String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}

	public String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}

	public M setDsUpdateUserId(String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}

	public String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}

	public M setDsOrder(java.math.BigDecimal dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}

	public java.math.BigDecimal getDsOrder() {
		return get("ds_order");
	}

	public M setDsDeleted(String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}

	public String getDsDeleted() {
		return getStr("ds_deleted");
	}

	public M setDsUpdateUserName(String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}

	public String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}

	public M setDsCreateUserName(String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}

	public String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}

	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}

	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}

	public M setDsUnitId(String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}

	public String getDsUnitId() {
		return getStr("ds_unit_id");
	}

	public M setTeasJwglBjglId(String teasJwglBjglId) {
		set("teas_jwgl_bjgl_id", teasJwglBjglId);
		return (M)this;
	}

	public String getTeasJwglBjglId() {
		return getStr("teas_jwgl_bjgl_id");
	}

	public M setZb(String zb) {
		set("zb", zb);
		return (M)this;
	}

	public String getZb() {
		return getStr("zb");
	}

	public M setXh(String xh) {
		set("xh", xh);
		return (M)this;
	}

	public String getXh() {
		return getStr("xh");
	}

	public M setSzdwzw(String szdwzw) {
		set("szdwzw", szdwzw);
		return (M)this;
	}

	public String getSzdwzw() {
		return getStr("szdwzw");
	}

	public M setSexText(String sexText) {
		set("sex_text", sexText);
		return (M)this;
	}

	public String getSexText() {
		return getStr("sex_text");
	}

	public M setSexValue(String sexValue) {
		set("sex_value", sexValue);
		return (M)this;
	}

	public String getSexValue() {
		return getStr("sex_value");
	}

	public M setPhone(String phone) {
		set("phone", phone);
		return (M)this;
	}

	public String getPhone() {
		return getStr("phone");
	}

	public M setBjzwText(String bjzwText) {
		set("bjzw_text", bjzwText);
		return (M)this;
	}

	public String getBjzwText() {
		return getStr("bjzw_text");
	}

	public M setBjzwValue(String bjzwValue) {
		set("bjzw_value", bjzwValue);
		return (M)this;
	}

	public String getBjzwValue() {
		return getStr("bjzw_value");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setSfzh(String sfzh) {
		set("sfzh", sfzh);
		return (M)this;
	}

	public String getSfzh() {
		return getStr("sfzh");
	}

	public M setPhoto(String photo) {
		set("photo", photo);
		return (M)this;
	}

	public String getPhoto() {
		return getStr("photo");
	}

	public M setHwzh(String hwzh) {
		set("hwzh", hwzh);
		return (M)this;
	}

	public String getHwzh() {
		return getStr("hwzh");
	}

	public M setMzText(String mzText) {
		set("mz_text", mzText);
		return (M)this;
	}

	public String getMzText() {
		return getStr("mz_text");
	}

	public M setMzValue(String mzValue) {
		set("mz_value", mzValue);
		return (M)this;
	}

	public String getMzValue() {
		return getStr("mz_value");
	}

	public M setDwdz(String dwdz) {
		set("dwdz", dwdz);
		return (M)this;
	}

	public String getDwdz() {
		return getStr("dwdz");
	}

	public M setDwyb(String dwyb) {
		set("dwyb", dwyb);
		return (M)this;
	}

	public String getDwyb() {
		return getStr("dwyb");
	}

	public M setDpText(String dpText) {
		set("dp_text", dpText);
		return (M)this;
	}

	public String getDpText() {
		return getStr("dp_text");
	}

	public M setDpValue(String dpValue) {
		set("dp_value", dpValue);
		return (M)this;
	}

	public String getDpValue() {
		return getStr("dp_value");
	}

	public M setBgdh(String bgdh) {
		set("bgdh", bgdh);
		return (M)this;
	}

	public String getBgdh() {
		return getStr("bgdh");
	}

	public M setCptwo(String cptwo) {
		set("cptwo", cptwo);
		return (M)this;
	}

	public String getCptwo() {
		return getStr("cptwo");
	}

	public M setCpone(String cpone) {
		set("cpone", cpone);
		return (M)this;
	}

	public String getCpone() {
		return getStr("cpone");
	}

	public M setZcText(String zcText) {
		set("zc_text", zcText);
		return (M)this;
	}

	public String getZcText() {
		return getStr("zc_text");
	}

	public M setZcValue(String zcValue) {
		set("zc_value", zcValue);
		return (M)this;
	}

	public String getZcValue() {
		return getStr("zc_value");
	}

	public M setJbText(String jbText) {
		set("jb_text", jbText);
		return (M)this;
	}

	public String getJbText() {
		return getStr("jb_text");
	}

	public M setJbValue(String jbValue) {
		set("jb_value", jbValue);
		return (M)this;
	}

	public String getJbValue() {
		return getStr("jb_value");
	}

	public M setJgText(String jgText) {
		set("jg_text", jgText);
		return (M)this;
	}

	public String getJgText() {
		return getStr("jg_text");
	}

	public M setJgValue(String jgValue) {
		set("jg_value", jgValue);
		return (M)this;
	}

	public String getJgValue() {
		return getStr("jg_value");
	}

	public M setRzsj(java.util.Date rzsj) {
		set("rzsj", rzsj);
		return (M)this;
	}

	public java.util.Date getRzsj() {
		return getDate("rzsj");
	}

	public M setWhcdText(String whcdText) {
		set("whcd_text", whcdText);
		return (M)this;
	}

	public String getWhcdText() {
		return getStr("whcd_text");
	}

	public M setWhcdValue(String whcdValue) {
		set("whcd_value", whcdValue);
		return (M)this;
	}

	public String getWhcdValue() {
		return getStr("whcd_value");
	}

	public M setRdrq(java.util.Date rdrq) {
		set("rdrq", rdrq);
		return (M)this;
	}

	public java.util.Date getRdrq() {
		return getDate("rdrq");
	}

	public M setGbText(String gbText) {
		set("gb_text", gbText);
		return (M)this;
	}

	public String getGbText() {
		return getStr("gb_text");
	}

	public M setGbValue(String gbValue) {
		set("gb_value", gbValue);
		return (M)this;
	}

	public String getGbValue() {
		return getStr("gb_value");
	}

	public M setDesj(String desj) {
		set("desj", desj);
		return (M)this;
	}

	public String getDesj() {
		return getStr("desj");
	}

	public M setQq(String qq) {
		set("qq", qq);
		return (M)this;
	}

	public String getQq() {
		return getStr("qq");
	}

	public M setLxr(String lxr) {
		set("lxr", lxr);
		return (M)this;
	}

	public String getLxr() {
		return getStr("lxr");
	}

	public M setCz(String cz) {
		set("cz", cz);
		return (M)this;
	}

	public String getCz() {
		return getStr("cz");
	}

	public M setLxdh(String lxdh) {
		set("lxdh", lxdh);
		return (M)this;
	}

	public String getLxdh() {
		return getStr("lxdh");
	}

	public M setEmail(String email) {
		set("email", email);
		return (M)this;
	}

	public String getEmail() {
		return getStr("email");
	}

	public M setFjh(String fjh) {
		set("fjh", fjh);
		return (M)this;
	}

	public String getFjh() {
		return getStr("fjh");
	}

	public M setYxxyText(String yxxyText) {
		set("yxxy_text", yxxyText);
		return (M)this;
	}

	public String getYxxyText() {
		return getStr("yxxy_text");
	}

	public M setYxxyValue(String yxxyValue) {
		set("yxxy_value", yxxyValue);
		return (M)this;
	}

	public String getYxxyValue() {
		return getStr("yxxy_value");
	}

	public M setZbText(String zbText) {
		set("zb_text", zbText);
		return (M)this;
	}

	public String getZbText() {
		return getStr("zb_text");
	}

	public M setZbValue(String zbValue) {
		set("zb_value", zbValue);
		return (M)this;
	}

	public String getZbValue() {
		return getStr("zb_value");
	}

	public M setDwjzw(String dwjzw) {
		set("dwjzw", dwjzw);
		return (M)this;
	}

	public String getDwjzw() {
		return getStr("dwjzw");
	}

	public M setDsDeptId(String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}

	public String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
}

