package com.dsfa.nc.pd.temp.model;

import com.dsfa.nc.pd.temp.model.base.BaseDsfaOuaUserUserdept;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
    tableName = "dsfa_oua_user_userdept",
    pkName = "dsfa_oua_user_userdept_id"
)
public class DsfaOuaUserUserdept extends BaseDsfaOuaUserUserdept<DsfaOuaUserUserdept> {
	public static final DsfaOuaUserUserdept dao = new DsfaOuaUserUserdept().dao();
}