package com.dsfa.nc.pd.temp.model;

import com.dsfa.nc.pd.temp.model.base.BaseDsfaOuaUser;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
    tableName = "dsfa_oua_user",
    pkName = "dsfa_oua_user_id"
)
public class DsfaOuaUser extends BaseDsfaOuaUser<DsfaOuaUser> {
	public static final DsfaOuaUser dao = new DsfaOuaUser().dao();
}