package com.dsfa.nc.pd.temp.model;

import com.dsfa.nc.pd.temp.model.base.BaseNcAuthoInfo;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
    tableName = "nc_autho_info",
    pkName = "nc_autho_info_id"
)
public class NcAuthoInfo extends BaseNcAuthoInfo<NcAuthoInfo> {
	public static final NcAuthoInfo dao = new NcAuthoInfo().dao();
}