package com.dsfa.nc.pd.temp.model;

import com.dsfa.nc.pd.temp.model.base.BaseNcRecordCourseware;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
    tableName = "nc_record_courseware",
    pkName = "nc_record_courseware_id"
)
public class NcRecordCourseware extends BaseNcRecordCourseware<NcRecordCourseware> {
	public static final NcRecordCourseware dao = new NcRecordCourseware().dao();
}