package com.dsfa.nc.pd.temp.model;

import com.dsfa.nc.pd.temp.model.base.BaseSdkToken;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
    tableName = "sdk_token",
    pkName = "sdk_token_id"
)
public class SdkToken extends BaseSdkToken<SdkToken> {
	public static final SdkToken dao = new SdkToken().dao();
}