package com.dsfa.nc.web.pd.domain.courses.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBjglBzrinfo<M extends BaseBjglBzrinfo<M>> extends Model<M> implements IBean {

	public M setTeasJwglBjglBzrinfoId(java.lang.String teasJwglBjglBzrinfoId) {
		set("teas_jwgl_bjgl_bzrinfo_id", teasJwglBjglBzrinfoId);
		return (M)this;
	}
	
	public java.lang.String getTeasJwglBjglBzrinfoId() {
		return getStr("teas_jwgl_bjgl_bzrinfo_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsCreateUserId(java.lang.String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsOrder(java.math.BigDecimal dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public java.math.BigDecimal getDsOrder() {
		return get("ds_order");
	}
	
	public M setDsDeleted(java.lang.String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public java.lang.String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsCreateUserName(java.lang.String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setDsUnitId(java.lang.String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public java.lang.String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setTeasJwglBjglId(java.lang.String teasJwglBjglId) {
		set("teas_jwgl_bjgl_id", teasJwglBjglId);
		return (M)this;
	}
	
	public java.lang.String getTeasJwglBjglId() {
		return getStr("teas_jwgl_bjgl_id");
	}
	
	public M setBzrname(java.lang.String bzrname) {
		set("bzrname", bzrname);
		return (M)this;
	}
	
	public java.lang.String getBzrname() {
		return getStr("bzrname");
	}
	
	public M setBzrid(java.lang.String bzrid) {
		set("bzrid", bzrid);
		return (M)this;
	}
	
	public java.lang.String getBzrid() {
		return getStr("bzrid");
	}
	
	public M setBzrdh(java.lang.String bzrdh) {
		set("bzrdh", bzrdh);
		return (M)this;
	}
	
	public java.lang.String getBzrdh() {
		return getStr("bzrdh");
	}
	
	public M setBcmc(java.lang.String bcmc) {
		set("bcmc", bcmc);
		return (M)this;
	}
	
	public java.lang.String getBcmc() {
		return getStr("bcmc");
	}
	
	public M setDsDeptId(java.lang.String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public java.lang.String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
}

