package com.dsfa.nc.web.pd.domain.courses.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBjglZjswdxOut<M extends BaseBjglZjswdxOut<M>> extends Model<M> implements IBean {

	public M setTeasJwglBjglZjswdxOutId(java.lang.String teasJwglBjglZjswdxOutId) {
		set("teas_jwgl_bjgl_zjswdx_out_id", teasJwglBjglZjswdxOutId);
		return (M)this;
	}
	
	public java.lang.String getTeasJwglBjglZjswdxOutId() {
		return getStr("teas_jwgl_bjgl_zjswdx_out_id");
	}
	
	public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsDeptId(java.lang.String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public java.lang.String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
	public M setDsCreateUserName(java.lang.String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsCreateUserId(java.lang.String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsDeleted(java.lang.String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public java.lang.String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsOrder(java.lang.Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public java.lang.Integer getDsOrder() {
		return getInt("ds_order");
	}
	
	public M setDsUnitId(java.lang.String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public java.lang.String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setAddItemSum(java.math.BigDecimal addItemSum) {
		set("add_item_sum", addItemSum);
		return (M)this;
	}
	
	public java.math.BigDecimal getAddItemSum() {
		return get("add_item_sum");
	}
	
	public M setSjts(java.lang.String sjts) {
		set("sjts", sjts);
		return (M)this;
	}
	
	public java.lang.String getSjts() {
		return getStr("sjts");
	}
	
	public M setCostSum(java.math.BigDecimal costSum) {
		set("cost_sum", costSum);
		return (M)this;
	}
	
	public java.math.BigDecimal getCostSum() {
		return get("cost_sum");
	}
	
	public M setSubItemSum(java.math.BigDecimal subItemSum) {
		set("sub_item_sum", subItemSum);
		return (M)this;
	}
	
	public java.math.BigDecimal getSubItemSum() {
		return get("sub_item_sum");
	}
	
	public M setBaseCost(java.math.BigDecimal baseCost) {
		set("base_cost", baseCost);
		return (M)this;
	}
	
	public java.math.BigDecimal getBaseCost() {
		return get("base_cost");
	}
	
	public M setCostExplain(java.lang.String costExplain) {
		set("cost_explain", costExplain);
		return (M)this;
	}
	
	public java.lang.String getCostExplain() {
		return getStr("cost_explain");
	}
	
	public M setPerCostText(java.lang.String perCostText) {
		set("per_cost_text", perCostText);
		return (M)this;
	}
	
	public java.lang.String getPerCostText() {
		return getStr("per_cost_text");
	}
	
	public M setPerCostValue(java.lang.String perCostValue) {
		set("per_cost_value", perCostValue);
		return (M)this;
	}
	
	public java.lang.String getPerCostValue() {
		return getStr("per_cost_value");
	}
	
	public M setFyjsbid(java.lang.String fyjsbid) {
		set("fyjsbid", fyjsbid);
		return (M)this;
	}
	
	public java.lang.String getFyjsbid() {
		return getStr("fyjsbid");
	}
	
}

