package com.dsfa.nc.web.pd.domain.courses.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBjglXyxx<M extends BaseBjglXyxx<M>> extends Model<M> implements IBean {

	public M setTeasJwglBjglXyxxId(java.lang.String teasJwglBjglXyxxId) {
		set("teas_jwgl_bjgl_xyxx_id", teasJwglBjglXyxxId);
		return (M)this;
	}
	
	public java.lang.String getTeasJwglBjglXyxxId() {
		return getStr("teas_jwgl_bjgl_xyxx_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsCreateUserId(java.lang.String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsOrder(java.math.BigDecimal dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public java.math.BigDecimal getDsOrder() {
		return get("ds_order");
	}
	
	public M setDsDeleted(java.lang.String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public java.lang.String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsCreateUserName(java.lang.String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setDsUnitId(java.lang.String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public java.lang.String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setTeasJwglBjglId(java.lang.String teasJwglBjglId) {
		set("teas_jwgl_bjgl_id", teasJwglBjglId);
		return (M)this;
	}
	
	public java.lang.String getTeasJwglBjglId() {
		return getStr("teas_jwgl_bjgl_id");
	}
	
	public M setZb(java.lang.String zb) {
		set("zb", zb);
		return (M)this;
	}
	
	public java.lang.String getZb() {
		return getStr("zb");
	}
	
	public M setXh(java.lang.String xh) {
		set("xh", xh);
		return (M)this;
	}
	
	public java.lang.String getXh() {
		return getStr("xh");
	}
	
	public M setSzdwzw(java.lang.String szdwzw) {
		set("szdwzw", szdwzw);
		return (M)this;
	}
	
	public java.lang.String getSzdwzw() {
		return getStr("szdwzw");
	}
	
	public M setSexText(java.lang.String sexText) {
		set("sex_text", sexText);
		return (M)this;
	}
	
	public java.lang.String getSexText() {
		return getStr("sex_text");
	}
	
	public M setSexValue(java.lang.String sexValue) {
		set("sex_value", sexValue);
		return (M)this;
	}
	
	public java.lang.String getSexValue() {
		return getStr("sex_value");
	}
	
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	public M setBjzwText(java.lang.String bjzwText) {
		set("bjzw_text", bjzwText);
		return (M)this;
	}
	
	public java.lang.String getBjzwText() {
		return getStr("bjzw_text");
	}
	
	public M setBjzwValue(java.lang.String bjzwValue) {
		set("bjzw_value", bjzwValue);
		return (M)this;
	}
	
	public java.lang.String getBjzwValue() {
		return getStr("bjzw_value");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setSfzh(java.lang.String sfzh) {
		set("sfzh", sfzh);
		return (M)this;
	}
	
	public java.lang.String getSfzh() {
		return getStr("sfzh");
	}
	
	public M setPhoto(java.lang.String photo) {
		set("photo", photo);
		return (M)this;
	}
	
	public java.lang.String getPhoto() {
		return getStr("photo");
	}
	
	public M setHwzh(java.lang.String hwzh) {
		set("hwzh", hwzh);
		return (M)this;
	}
	
	public java.lang.String getHwzh() {
		return getStr("hwzh");
	}
	
	public M setMzText(java.lang.String mzText) {
		set("mz_text", mzText);
		return (M)this;
	}
	
	public java.lang.String getMzText() {
		return getStr("mz_text");
	}
	
	public M setMzValue(java.lang.String mzValue) {
		set("mz_value", mzValue);
		return (M)this;
	}
	
	public java.lang.String getMzValue() {
		return getStr("mz_value");
	}
	
	public M setDwdz(java.lang.String dwdz) {
		set("dwdz", dwdz);
		return (M)this;
	}
	
	public java.lang.String getDwdz() {
		return getStr("dwdz");
	}
	
	public M setDwyb(java.lang.String dwyb) {
		set("dwyb", dwyb);
		return (M)this;
	}
	
	public java.lang.String getDwyb() {
		return getStr("dwyb");
	}
	
	public M setDpText(java.lang.String dpText) {
		set("dp_text", dpText);
		return (M)this;
	}
	
	public java.lang.String getDpText() {
		return getStr("dp_text");
	}
	
	public M setDpValue(java.lang.String dpValue) {
		set("dp_value", dpValue);
		return (M)this;
	}
	
	public java.lang.String getDpValue() {
		return getStr("dp_value");
	}
	
	public M setBgdh(java.lang.String bgdh) {
		set("bgdh", bgdh);
		return (M)this;
	}
	
	public java.lang.String getBgdh() {
		return getStr("bgdh");
	}
	
	public M setCptwo(java.lang.String cptwo) {
		set("cptwo", cptwo);
		return (M)this;
	}
	
	public java.lang.String getCptwo() {
		return getStr("cptwo");
	}
	
	public M setCpone(java.lang.String cpone) {
		set("cpone", cpone);
		return (M)this;
	}
	
	public java.lang.String getCpone() {
		return getStr("cpone");
	}
	
	public M setZcText(java.lang.String zcText) {
		set("zc_text", zcText);
		return (M)this;
	}
	
	public java.lang.String getZcText() {
		return getStr("zc_text");
	}
	
	public M setZcValue(java.lang.String zcValue) {
		set("zc_value", zcValue);
		return (M)this;
	}
	
	public java.lang.String getZcValue() {
		return getStr("zc_value");
	}
	
	public M setJbText(java.lang.String jbText) {
		set("jb_text", jbText);
		return (M)this;
	}
	
	public java.lang.String getJbText() {
		return getStr("jb_text");
	}
	
	public M setJbValue(java.lang.String jbValue) {
		set("jb_value", jbValue);
		return (M)this;
	}
	
	public java.lang.String getJbValue() {
		return getStr("jb_value");
	}
	
	public M setJgText(java.lang.String jgText) {
		set("jg_text", jgText);
		return (M)this;
	}
	
	public java.lang.String getJgText() {
		return getStr("jg_text");
	}
	
	public M setJgValue(java.lang.String jgValue) {
		set("jg_value", jgValue);
		return (M)this;
	}
	
	public java.lang.String getJgValue() {
		return getStr("jg_value");
	}
	
	public M setRzsj(java.util.Date rzsj) {
		set("rzsj", rzsj);
		return (M)this;
	}
	
	public java.util.Date getRzsj() {
		return getDate("rzsj");
	}
	
	public M setWhcdText(java.lang.String whcdText) {
		set("whcd_text", whcdText);
		return (M)this;
	}
	
	public java.lang.String getWhcdText() {
		return getStr("whcd_text");
	}
	
	public M setWhcdValue(java.lang.String whcdValue) {
		set("whcd_value", whcdValue);
		return (M)this;
	}
	
	public java.lang.String getWhcdValue() {
		return getStr("whcd_value");
	}
	
	public M setRdrq(java.util.Date rdrq) {
		set("rdrq", rdrq);
		return (M)this;
	}
	
	public java.util.Date getRdrq() {
		return getDate("rdrq");
	}
	
	public M setGbText(java.lang.String gbText) {
		set("gb_text", gbText);
		return (M)this;
	}
	
	public java.lang.String getGbText() {
		return getStr("gb_text");
	}
	
	public M setGbValue(java.lang.String gbValue) {
		set("gb_value", gbValue);
		return (M)this;
	}
	
	public java.lang.String getGbValue() {
		return getStr("gb_value");
	}
	
	public M setDesj(java.lang.String desj) {
		set("desj", desj);
		return (M)this;
	}
	
	public java.lang.String getDesj() {
		return getStr("desj");
	}
	
	public M setQq(java.lang.String qq) {
		set("qq", qq);
		return (M)this;
	}
	
	public java.lang.String getQq() {
		return getStr("qq");
	}
	
	public M setLxr(java.lang.String lxr) {
		set("lxr", lxr);
		return (M)this;
	}
	
	public java.lang.String getLxr() {
		return getStr("lxr");
	}
	
	public M setCz(java.lang.String cz) {
		set("cz", cz);
		return (M)this;
	}
	
	public java.lang.String getCz() {
		return getStr("cz");
	}
	
	public M setLxdh(java.lang.String lxdh) {
		set("lxdh", lxdh);
		return (M)this;
	}
	
	public java.lang.String getLxdh() {
		return getStr("lxdh");
	}
	
	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	public M setFjh(java.lang.String fjh) {
		set("fjh", fjh);
		return (M)this;
	}
	
	public java.lang.String getFjh() {
		return getStr("fjh");
	}
	
	public M setYxxyText(java.lang.String yxxyText) {
		set("yxxy_text", yxxyText);
		return (M)this;
	}
	
	public java.lang.String getYxxyText() {
		return getStr("yxxy_text");
	}
	
	public M setYxxyValue(java.lang.String yxxyValue) {
		set("yxxy_value", yxxyValue);
		return (M)this;
	}
	
	public java.lang.String getYxxyValue() {
		return getStr("yxxy_value");
	}
	
	public M setZbText(java.lang.String zbText) {
		set("zb_text", zbText);
		return (M)this;
	}
	
	public java.lang.String getZbText() {
		return getStr("zb_text");
	}
	
	public M setZbValue(java.lang.String zbValue) {
		set("zb_value", zbValue);
		return (M)this;
	}
	
	public java.lang.String getZbValue() {
		return getStr("zb_value");
	}
	
	public M setDwjzw(java.lang.String dwjzw) {
		set("dwjzw", dwjzw);
		return (M)this;
	}
	
	public java.lang.String getDwjzw() {
		return getStr("dwjzw");
	}
	
	public M setDsDeptId(java.lang.String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public java.lang.String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
}

