package com.dsfa.nc.web.pd.domain.courses.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBjglBjwbdwedit<M extends BaseBjglBjwbdwedit<M>> extends Model<M> implements IBean {

	public M setTeasJwglBjglBjwbdweditId(java.lang.String teasJwglBjglBjwbdweditId) {
		set("teas_jwgl_bjgl_bjwbdwEdit_id", teasJwglBjglBjwbdweditId);
		return (M)this;
	}
	
	public java.lang.String getTeasJwglBjglBjwbdweditId() {
		return getStr("teas_jwgl_bjgl_bjwbdwEdit_id");
	}
	
	public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsCreateUserName(java.lang.String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsCreateUserId(java.lang.String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsDeleted(java.lang.String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public java.lang.String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsOrder(java.lang.Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public java.lang.Integer getDsOrder() {
		return getInt("ds_order");
	}
	
	public M setDsUnitId(java.lang.String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public java.lang.String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setTeasJwglBjglId(java.lang.String teasJwglBjglId) {
		set("teas_jwgl_bjgl_id", teasJwglBjglId);
		return (M)this;
	}
	
	public java.lang.String getTeasJwglBjglId() {
		return getStr("teas_jwgl_bjgl_id");
	}
	
	public M setWbdwryText(java.lang.String wbdwryText) {
		set("wbdwry_text", wbdwryText);
		return (M)this;
	}
	
	public java.lang.String getWbdwryText() {
		return getStr("wbdwry_text");
	}
	
	public M setWbdwryValue(java.lang.String wbdwryValue) {
		set("wbdwry_value", wbdwryValue);
		return (M)this;
	}
	
	public java.lang.String getWbdwryValue() {
		return getStr("wbdwry_value");
	}
	
	public M setWbdwrysl(java.lang.String wbdwrysl) {
		set("wbdwrysl", wbdwrysl);
		return (M)this;
	}
	
	public java.lang.String getWbdwrysl() {
		return getStr("wbdwrysl");
	}
	
	public M setBz(java.lang.String bz) {
		set("bz", bz);
		return (M)this;
	}
	
	public java.lang.String getBz() {
		return getStr("bz");
	}
	
	public M setDsDeptId(java.lang.String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public java.lang.String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
}

