package com.dsfa.nc.web.pd.domain.courses.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBjglMealDemand<M extends BaseBjglMealDemand<M>> extends Model<M> implements IBean {

	public M setTeasJwglBjglMealDemandId(java.lang.String teasJwglBjglMealDemandId) {
		set("teas_jwgl_bjgl_meal_demand_id", teasJwglBjglMealDemandId);
		return (M)this;
	}
	
	public java.lang.String getTeasJwglBjglMealDemandId() {
		return getStr("teas_jwgl_bjgl_meal_demand_id");
	}
	
	public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsDeptId(java.lang.String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public java.lang.String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
	public M setDsCreateUserName(java.lang.String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsCreateUserId(java.lang.String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsDeleted(java.lang.String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public java.lang.String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsOrder(java.lang.Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public java.lang.Integer getDsOrder() {
		return getInt("ds_order");
	}
	
	public M setDsUnitId(java.lang.String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public java.lang.String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setTeasJwglBjglId(java.lang.String teasJwglBjglId) {
		set("teas_jwgl_bjgl_id", teasJwglBjglId);
		return (M)this;
	}
	
	public java.lang.String getTeasJwglBjglId() {
		return getStr("teas_jwgl_bjgl_id");
	}
	
	public M setDinnerText(java.lang.String dinnerText) {
		set("dinner_text", dinnerText);
		return (M)this;
	}
	
	public java.lang.String getDinnerText() {
		return getStr("dinner_text");
	}
	
	public M setDinnerValue(java.lang.String dinnerValue) {
		set("dinner_value", dinnerValue);
		return (M)this;
	}
	
	public java.lang.String getDinnerValue() {
		return getStr("dinner_value");
	}
	
	public M setLunchSelfStandardText(java.lang.String lunchSelfStandardText) {
		set("lunch_self_standard_text", lunchSelfStandardText);
		return (M)this;
	}
	
	public java.lang.String getLunchSelfStandardText() {
		return getStr("lunch_self_standard_text");
	}
	
	public M setLunchSelfStandardValue(java.lang.String lunchSelfStandardValue) {
		set("lunch_self_standard_value", lunchSelfStandardValue);
		return (M)this;
	}
	
	public java.lang.String getLunchSelfStandardValue() {
		return getStr("lunch_self_standard_value");
	}
	
	public M setLunchTableStandard(java.lang.String lunchTableStandard) {
		set("lunch_table_standard", lunchTableStandard);
		return (M)this;
	}
	
	public java.lang.String getLunchTableStandard() {
		return getStr("lunch_table_standard");
	}
	
	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}
	
	public java.util.Date getDate() {
		return getDate("date");
	}
	
	public M setLunchTypeText(java.lang.String lunchTypeText) {
		set("lunch_type_text", lunchTypeText);
		return (M)this;
	}
	
	public java.lang.String getLunchTypeText() {
		return getStr("lunch_type_text");
	}
	
	public M setLunchTypeValue(java.lang.String lunchTypeValue) {
		set("lunch_type_value", lunchTypeValue);
		return (M)this;
	}
	
	public java.lang.String getLunchTypeValue() {
		return getStr("lunch_type_value");
	}
	
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public M setLunchText(java.lang.String lunchText) {
		set("lunch_text", lunchText);
		return (M)this;
	}
	
	public java.lang.String getLunchText() {
		return getStr("lunch_text");
	}
	
	public M setLunchValue(java.lang.String lunchValue) {
		set("lunch_value", lunchValue);
		return (M)this;
	}
	
	public java.lang.String getLunchValue() {
		return getStr("lunch_value");
	}
	
	public M setDinnerTypeText(java.lang.String dinnerTypeText) {
		set("dinner_type_text", dinnerTypeText);
		return (M)this;
	}
	
	public java.lang.String getDinnerTypeText() {
		return getStr("dinner_type_text");
	}
	
	public M setDinnerTypeValue(java.lang.String dinnerTypeValue) {
		set("dinner_type_value", dinnerTypeValue);
		return (M)this;
	}
	
	public java.lang.String getDinnerTypeValue() {
		return getStr("dinner_type_value");
	}
	
	public M setDinnerTableNum(java.lang.String dinnerTableNum) {
		set("dinner_table_num", dinnerTableNum);
		return (M)this;
	}
	
	public java.lang.String getDinnerTableNum() {
		return getStr("dinner_table_num");
	}
	
	public M setDinnerTableStandard(java.lang.String dinnerTableStandard) {
		set("dinner_table_standard", dinnerTableStandard);
		return (M)this;
	}
	
	public java.lang.String getDinnerTableStandard() {
		return getStr("dinner_table_standard");
	}
	
	public M setDinnerSelfStandardText(java.lang.String dinnerSelfStandardText) {
		set("dinner_self_standard_text", dinnerSelfStandardText);
		return (M)this;
	}
	
	public java.lang.String getDinnerSelfStandardText() {
		return getStr("dinner_self_standard_text");
	}
	
	public M setDinnerSelfStandardValue(java.lang.String dinnerSelfStandardValue) {
		set("dinner_self_standard_value", dinnerSelfStandardValue);
		return (M)this;
	}
	
	public java.lang.String getDinnerSelfStandardValue() {
		return getStr("dinner_self_standard_value");
	}
	
	public M setLunchTableNum(java.lang.String lunchTableNum) {
		set("lunch_table_num", lunchTableNum);
		return (M)this;
	}
	
	public java.lang.String getLunchTableNum() {
		return getStr("lunch_table_num");
	}
	
}

