package com.dsfa.nc.web.pd.domain.courses.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBjgl<M extends BaseBjgl<M>> extends Model<M> implements IBean {

	public M setTeasJwglBjglId(java.lang.String teasJwglBjglId) {
		set("teas_jwgl_bjgl_id", teasJwglBjglId);
		return (M)this;
	}
	
	public java.lang.String getTeasJwglBjglId() {
		return getStr("teas_jwgl_bjgl_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsCreateUserId(java.lang.String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsOrder(java.math.BigDecimal dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public java.math.BigDecimal getDsOrder() {
		return get("ds_order");
	}
	
	public M setDsDeleted(java.lang.String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public java.lang.String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsCreateUserName(java.lang.String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setDsUnitId(java.lang.String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public java.lang.String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setXnText(java.lang.String xnText) {
		set("xn_text", xnText);
		return (M)this;
	}
	
	public java.lang.String getXnText() {
		return getStr("xn_text");
	}
	
	public M setXnValue(java.lang.String xnValue) {
		set("xn_value", xnValue);
		return (M)this;
	}
	
	public java.lang.String getXnValue() {
		return getStr("xn_value");
	}
	
	public M setXqText(java.lang.String xqText) {
		set("xq_text", xqText);
		return (M)this;
	}
	
	public java.lang.String getXqText() {
		return getStr("xq_text");
	}
	
	public M setXqValue(java.lang.String xqValue) {
		set("xq_value", xqValue);
		return (M)this;
	}
	
	public java.lang.String getXqValue() {
		return getStr("xq_value");
	}
	
	public M setPxsjSdate(java.util.Date pxsjSdate) {
		set("pxsj_sdate", pxsjSdate);
		return (M)this;
	}
	
	public java.util.Date getPxsjSdate() {
		return getDate("pxsj_sdate");
	}
	
	public M setPxsjEdate(java.util.Date pxsjEdate) {
		set("pxsj_edate", pxsjEdate);
		return (M)this;
	}
	
	public java.util.Date getPxsjEdate() {
		return getDate("pxsj_edate");
	}
	
	public M setRxtz(java.lang.String rxtz) {
		set("rxtz", rxtz);
		return (M)this;
	}
	
	public java.lang.String getRxtz() {
		return getStr("rxtz");
	}
	
	public M setKcpjText(java.lang.String kcpjText) {
		set("kcpj_text", kcpjText);
		return (M)this;
	}
	
	public java.lang.String getKcpjText() {
		return getStr("kcpj_text");
	}
	
	public M setKcpjValue(java.lang.String kcpjValue) {
		set("kcpj_value", kcpjValue);
		return (M)this;
	}
	
	public java.lang.String getKcpjValue() {
		return getStr("kcpj_value");
	}
	
	public M setBjxzText(java.lang.String bjxzText) {
		set("bjxz_text", bjxzText);
		return (M)this;
	}
	
	public java.lang.String getBjxzText() {
		return getStr("bjxz_text");
	}
	
	public M setBjxzValue(java.lang.String bjxzValue) {
		set("bjxz_value", bjxzValue);
		return (M)this;
	}
	
	public java.lang.String getBjxzValue() {
		return getStr("bjxz_value");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setBzrText(java.lang.String bzrText) {
		set("bzr_text", bzrText);
		return (M)this;
	}
	
	public java.lang.String getBzrText() {
		return getStr("bzr_text");
	}
	
	public M setBzrValue(java.lang.String bzrValue) {
		set("bzr_value", bzrValue);
		return (M)this;
	}
	
	public java.lang.String getBzrValue() {
		return getStr("bzr_value");
	}
	
	public M setBclxText(java.lang.String bclxText) {
		set("bclx_text", bclxText);
		return (M)this;
	}
	
	public java.lang.String getBclxText() {
		return getStr("bclx_text");
	}
	
	public M setBclxValue(java.lang.String bclxValue) {
		set("bclx_value", bclxValue);
		return (M)this;
	}
	
	public java.lang.String getBclxValue() {
		return getStr("bclx_value");
	}
	
	public M setSkddText(java.lang.String skddText) {
		set("skdd_text", skddText);
		return (M)this;
	}
	
	public java.lang.String getSkddText() {
		return getStr("skdd_text");
	}
	
	public M setSkddValue(java.lang.String skddValue) {
		set("skdd_value", skddValue);
		return (M)this;
	}
	
	public java.lang.String getSkddValue() {
		return getStr("skdd_value");
	}
	
	public M setHqpjText(java.lang.String hqpjText) {
		set("hqpj_text", hqpjText);
		return (M)this;
	}
	
	public java.lang.String getHqpjText() {
		return getStr("hqpj_text");
	}
	
	public M setHqpjValue(java.lang.String hqpjValue) {
		set("hqpj_value", hqpjValue);
		return (M)this;
	}
	
	public java.lang.String getHqpjValue() {
		return getStr("hqpj_value");
	}
	
	public M setBcbh(java.lang.String bcbh) {
		set("bcbh", bcbh);
		return (M)this;
	}
	
	public java.lang.String getBcbh() {
		return getStr("bcbh");
	}
	
	public M setBjlbText(java.lang.String bjlbText) {
		set("bjlb_text", bjlbText);
		return (M)this;
	}
	
	public java.lang.String getBjlbText() {
		return getStr("bjlb_text");
	}
	
	public M setBjlbValue(java.lang.String bjlbValue) {
		set("bjlb_value", bjlbValue);
		return (M)this;
	}
	
	public java.lang.String getBjlbValue() {
		return getStr("bjlb_value");
	}
	
	public M setPjbzrText(java.lang.String pjbzrText) {
		set("pjbzr_text", pjbzrText);
		return (M)this;
	}
	
	public java.lang.String getPjbzrText() {
		return getStr("pjbzr_text");
	}
	
	public M setPjbzrValue(java.lang.String pjbzrValue) {
		set("pjbzr_value", pjbzrValue);
		return (M)this;
	}
	
	public java.lang.String getPjbzrValue() {
		return getStr("pjbzr_value");
	}
	
	public M setBczpText(java.lang.String bczpText) {
		set("bczp_text", bczpText);
		return (M)this;
	}
	
	public java.lang.String getBczpText() {
		return getStr("bczp_text");
	}
	
	public M setBczpValue(java.lang.String bczpValue) {
		set("bczp_value", bczpValue);
		return (M)this;
	}
	
	public java.lang.String getBczpValue() {
		return getStr("bczp_value");
	}
	
	public M setWspkText(java.lang.String wspkText) {
		set("wspk_text", wspkText);
		return (M)this;
	}
	
	public java.lang.String getWspkText() {
		return getStr("wspk_text");
	}
	
	public M setWspkValue(java.lang.String wspkValue) {
		set("wspk_value", wspkValue);
		return (M)this;
	}
	
	public java.lang.String getWspkValue() {
		return getStr("wspk_value");
	}
	
	public M setFjh(java.lang.String fjh) {
		set("fjh", fjh);
		return (M)this;
	}
	
	public java.lang.String getFjh() {
		return getStr("fjh");
	}
	
	public M setKcsffbText(java.lang.String kcsffbText) {
		set("kcsffb_text", kcsffbText);
		return (M)this;
	}
	
	public java.lang.String getKcsffbText() {
		return getStr("kcsffb_text");
	}
	
	public M setKcsffbValue(java.lang.String kcsffbValue) {
		set("kcsffb_value", kcsffbValue);
		return (M)this;
	}
	
	public java.lang.String getKcsffbValue() {
		return getStr("kcsffb_value");
	}
	
	public M setFbstatusText(java.lang.String fbstatusText) {
		set("fbstatus_text", fbstatusText);
		return (M)this;
	}
	
	public java.lang.String getFbstatusText() {
		return getStr("fbstatus_text");
	}
	
	public M setFbstatusValue(java.lang.String fbstatusValue) {
		set("fbstatus_value", fbstatusValue);
		return (M)this;
	}
	
	public java.lang.String getFbstatusValue() {
		return getStr("fbstatus_value");
	}
	
	public M setKcsffb(java.math.BigDecimal kcsffb) {
		set("kcsffb", kcsffb);
		return (M)this;
	}
	
	public java.math.BigDecimal getKcsffb() {
		return get("kcsffb");
	}
	
	public M setZwl(java.lang.String zwl) {
		set("zwl", zwl);
		return (M)this;
	}
	
	public java.lang.String getZwl() {
		return getStr("zwl");
	}
	
	public M setZwh(java.lang.String zwh) {
		set("zwh", zwh);
		return (M)this;
	}
	
	public java.lang.String getZwh() {
		return getStr("zwh");
	}
	
	public M setTspjdbText(java.lang.String tspjdbText) {
		set("tspjdb_text", tspjdbText);
		return (M)this;
	}
	
	public java.lang.String getTspjdbText() {
		return getStr("tspjdb_text");
	}
	
	public M setTspjdbValue(java.lang.String tspjdbValue) {
		set("tspjdb_value", tspjdbValue);
		return (M)this;
	}
	
	public java.lang.String getTspjdbValue() {
		return getStr("tspjdb_value");
	}
	
	public M setRxdcText(java.lang.String rxdcText) {
		set("rxdc_text", rxdcText);
		return (M)this;
	}
	
	public java.lang.String getRxdcText() {
		return getStr("rxdc_text");
	}
	
	public M setRxdcValue(java.lang.String rxdcValue) {
		set("rxdc_value", rxdcValue);
		return (M)this;
	}
	
	public java.lang.String getRxdcValue() {
		return getStr("rxdc_value");
	}
	
	public M setSjlyText(java.lang.String sjlyText) {
		set("sjly_text", sjlyText);
		return (M)this;
	}
	
	public java.lang.String getSjlyText() {
		return getStr("sjly_text");
	}
	
	public M setSjlyValue(java.lang.String sjlyValue) {
		set("sjly_value", sjlyValue);
		return (M)this;
	}
	
	public java.lang.String getSjlyValue() {
		return getStr("sjly_value");
	}
	
	public M setQyztText(java.lang.String qyztText) {
		set("qyzt_text", qyztText);
		return (M)this;
	}
	
	public java.lang.String getQyztText() {
		return getStr("qyzt_text");
	}
	
	public M setQyztValue(java.lang.String qyztValue) {
		set("qyzt_value", qyztValue);
		return (M)this;
	}
	
	public java.lang.String getQyztValue() {
		return getStr("qyzt_value");
	}
	
	public M setDsDeptId(java.lang.String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public java.lang.String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
	public M setFzsl(java.math.BigDecimal fzsl) {
		set("fzsl", fzsl);
		return (M)this;
	}
	
	public java.math.BigDecimal getFzsl() {
		return get("fzsl");
	}
	
	public M setXs(java.lang.String xs) {
		set("xs", xs);
		return (M)this;
	}
	
	public java.lang.String getXs() {
		return getStr("xs");
	}
	
	public M setBmsjSdate(java.util.Date bmsjSdate) {
		set("bmsj_sdate", bmsjSdate);
		return (M)this;
	}
	
	public java.util.Date getBmsjSdate() {
		return getDate("bmsj_sdate");
	}
	
	public M setBmsjEdate(java.util.Date bmsjEdate) {
		set("bmsj_edate", bmsjEdate);
		return (M)this;
	}
	
	public java.util.Date getBmsjEdate() {
		return getDate("bmsj_edate");
	}
	
	public M setXz(java.lang.String xz) {
		set("xz", xz);
		return (M)this;
	}
	
	public java.lang.String getXz() {
		return getStr("xz");
	}
	
	public M setTxrs(java.lang.String txrs) {
		set("txrs", txrs);
		return (M)this;
	}
	
	public java.lang.String getTxrs() {
		return getStr("txrs");
	}
	
	public M setLxxldText(java.lang.String lxxldText) {
		set("lxxld_text", lxxldText);
		return (M)this;
	}
	
	public java.lang.String getLxxldText() {
		return getStr("lxxld_text");
	}
	
	public M setLxxldValue(java.lang.String lxxldValue) {
		set("lxxld_value", lxxldValue);
		return (M)this;
	}
	
	public java.lang.String getLxxldValue() {
		return getStr("lxxld_value");
	}
	
	public M setBddd(java.lang.String bddd) {
		set("bddd", bddd);
		return (M)this;
	}
	
	public java.lang.String getBddd() {
		return getStr("bddd");
	}
	
	public M setWbfy(java.lang.String wbfy) {
		set("wbfy", wbfy);
		return (M)this;
	}
	
	public java.lang.String getWbfy() {
		return getStr("wbfy");
	}
	
	public M setWbsjSdate(java.util.Date wbsjSdate) {
		set("wbsj_sdate", wbsjSdate);
		return (M)this;
	}
	
	public java.util.Date getWbsjSdate() {
		return getDate("wbsj_sdate");
	}
	
	public M setWbsjEdate(java.util.Date wbsjEdate) {
		set("wbsj_edate", wbsjEdate);
		return (M)this;
	}
	
	public java.util.Date getWbsjEdate() {
		return getDate("wbsj_edate");
	}
	
	public M setSxrs(java.math.BigDecimal sxrs) {
		set("sxrs", sxrs);
		return (M)this;
	}
	
	public java.math.BigDecimal getSxrs() {
		return get("sxrs");
	}
	
	public M setBjgnText(java.lang.String bjgnText) {
		set("bjgn_text", bjgnText);
		return (M)this;
	}
	
	public java.lang.String getBjgnText() {
		return getStr("bjgn_text");
	}
	
	public M setBjgnValue(java.lang.String bjgnValue) {
		set("bjgn_value", bjgnValue);
		return (M)this;
	}
	
	public java.lang.String getBjgnValue() {
		return getStr("bjgn_value");
	}
	
	public M setClassid(java.lang.String classid) {
		set("classid", classid);
		return (M)this;
	}
	
	public java.lang.String getClassid() {
		return getStr("classid");
	}
	
	public M setBcxgztText(java.lang.String bcxgztText) {
		set("bcxgzt_text", bcxgztText);
		return (M)this;
	}
	
	public java.lang.String getBcxgztText() {
		return getStr("bcxgzt_text");
	}
	
	public M setBcxgztValue(java.lang.String bcxgztValue) {
		set("bcxgzt_value", bcxgztValue);
		return (M)this;
	}
	
	public java.lang.String getBcxgztValue() {
		return getStr("bcxgzt_value");
	}
	
	public M setZbmc(java.lang.String zbmc) {
		set("zbmc", zbmc);
		return (M)this;
	}
	
	public java.lang.String getZbmc() {
		return getStr("zbmc");
	}
	
	public M setZbbh(java.math.BigDecimal zbbh) {
		set("zbbh", zbbh);
		return (M)this;
	}
	
	public java.math.BigDecimal getZbbh() {
		return get("zbbh");
	}
	
	public M setWbtaskstatusText(java.lang.String wbtaskstatusText) {
		set("wbTaskStatus_text", wbtaskstatusText);
		return (M)this;
	}
	
	public java.lang.String getWbtaskstatusText() {
		return getStr("wbTaskStatus_text");
	}
	
	public M setWbtaskstatusValue(java.lang.String wbtaskstatusValue) {
		set("wbTaskStatus_value", wbtaskstatusValue);
		return (M)this;
	}
	
	public java.lang.String getWbtaskstatusValue() {
		return getStr("wbTaskStatus_value");
	}
	
	public M setZsbh(java.lang.String zsbh) {
		set("zsbh", zsbh);
		return (M)this;
	}
	
	public java.lang.String getZsbh() {
		return getStr("zsbh");
	}
	
	public M setTreeinfoPid(java.lang.String treeinfoPid) {
		set("treeinfo_pid", treeinfoPid);
		return (M)this;
	}
	
	public java.lang.String getTreeinfoPid() {
		return getStr("treeinfo_pid");
	}
	
	public M setTreeinfoIcon(java.lang.String treeinfoIcon) {
		set("treeinfo_icon", treeinfoIcon);
		return (M)this;
	}
	
	public java.lang.String getTreeinfoIcon() {
		return getStr("treeinfo_icon");
	}
	
	public M setTreeinfoGlobalid(java.lang.String treeinfoGlobalid) {
		set("treeinfo_globalid", treeinfoGlobalid);
		return (M)this;
	}
	
	public java.lang.String getTreeinfoGlobalid() {
		return getStr("treeinfo_globalid");
	}
	
	public M setTreeinfoLevel(java.math.BigDecimal treeinfoLevel) {
		set("treeinfo_level", treeinfoLevel);
		return (M)this;
	}
	
	public java.math.BigDecimal getTreeinfoLevel() {
		return get("treeinfo_level");
	}
	
	public M setTreeinfoType(java.lang.String treeinfoType) {
		set("treeinfo_type", treeinfoType);
		return (M)this;
	}
	
	public java.lang.String getTreeinfoType() {
		return getStr("treeinfo_type");
	}
	
	public M setBranchid(java.lang.String branchid) {
		set("branchid", branchid);
		return (M)this;
	}
	
	public java.lang.String getBranchid() {
		return getStr("branchid");
	}
	
	public M setZmc(java.lang.String zmc) {
		set("zmc", zmc);
		return (M)this;
	}
	
	public java.lang.String getZmc() {
		return getStr("zmc");
	}
	
	public M setZbh(java.math.BigDecimal zbh) {
		set("zbh", zbh);
		return (M)this;
	}
	
	public java.math.BigDecimal getZbh() {
		return get("zbh");
	}
	
	public M setRelname(java.lang.String relname) {
		set("relname", relname);
		return (M)this;
	}
	
	public java.lang.String getRelname() {
		return getStr("relname");
	}
	
	public M setWbimorder(java.lang.String wbimorder) {
		set("wbimorder", wbimorder);
		return (M)this;
	}
	
	public java.lang.String getWbimorder() {
		return getStr("wbimorder");
	}
	
	public M setHrjzsj(java.util.Date hrjzsj) {
		set("hrjzsj", hrjzsj);
		return (M)this;
	}
	
	public java.util.Date getHrjzsj() {
		return getDate("hrjzsj");
	}
	
	public M setIsxzxsText(java.lang.String isxzxsText) {
		set("isxzxs_text", isxzxsText);
		return (M)this;
	}
	
	public java.lang.String getIsxzxsText() {
		return getStr("isxzxs_text");
	}
	
	public M setIsxzxsValue(java.lang.String isxzxsValue) {
		set("isxzxs_value", isxzxsValue);
		return (M)this;
	}
	
	public java.lang.String getIsxzxsValue() {
		return getStr("isxzxs_value");
	}
	
	public M setCampusText(java.lang.String campusText) {
		set("campus_text", campusText);
		return (M)this;
	}
	
	public java.lang.String getCampusText() {
		return getStr("campus_text");
	}
	
	public M setCampusValue(java.lang.String campusValue) {
		set("campus_value", campusValue);
		return (M)this;
	}
	
	public java.lang.String getCampusValue() {
		return getStr("campus_value");
	}
	
	public M setJfjzsj(java.util.Date jfjzsj) {
		set("jfjzsj", jfjzsj);
		return (M)this;
	}
	
	public java.util.Date getJfjzsj() {
		return getDate("jfjzsj");
	}
	
	public M setPersonSignupQrcode(java.lang.String personSignupQrcode) {
		set("person_signup_qrcode", personSignupQrcode);
		return (M)this;
	}
	
	public java.lang.String getPersonSignupQrcode() {
		return getStr("person_signup_qrcode");
	}
	
	public M setBz(java.lang.String bz) {
		set("bz", bz);
		return (M)this;
	}
	
	public java.lang.String getBz() {
		return getStr("bz");
	}
	
	public M setWbTypeText(java.lang.String wbTypeText) {
		set("wb_type_text", wbTypeText);
		return (M)this;
	}
	
	public java.lang.String getWbTypeText() {
		return getStr("wb_type_text");
	}
	
	public M setWbTypeValue(java.lang.String wbTypeValue) {
		set("wb_type_value", wbTypeValue);
		return (M)this;
	}
	
	public java.lang.String getWbTypeValue() {
		return getStr("wb_type_value");
	}
	
	public M setMealAttendQrcode(java.lang.String mealAttendQrcode) {
		set("meal_attend_qrcode", mealAttendQrcode);
		return (M)this;
	}
	
	public java.lang.String getMealAttendQrcode() {
		return getStr("meal_attend_qrcode");
	}
	
	public M setRegDate(java.util.Date regDate) {
		set("reg_date", regDate);
		return (M)this;
	}
	
	public java.util.Date getRegDate() {
		return getDate("reg_date");
	}
	
	public M setBefroeapplytimeSdate(java.util.Date befroeapplytimeSdate) {
		set("befroeapplytime_sdate", befroeapplytimeSdate);
		return (M)this;
	}
	
	public java.util.Date getBefroeapplytimeSdate() {
		return getDate("befroeapplytime_sdate");
	}
	
	public M setBefroeapplytimeEdate(java.util.Date befroeapplytimeEdate) {
		set("befroeapplytime_edate", befroeapplytimeEdate);
		return (M)this;
	}
	
	public java.util.Date getBefroeapplytimeEdate() {
		return getDate("befroeapplytime_edate");
	}
	
	public M setHsf(java.lang.String hsf) {
		set("hsf", hsf);
		return (M)this;
	}
	
	public java.lang.String getHsf() {
		return getStr("hsf");
	}
	
	public M setShsjSdate(java.util.Date shsjSdate) {
		set("shsj_sdate", shsjSdate);
		return (M)this;
	}
	
	public java.util.Date getShsjSdate() {
		return getDate("shsj_sdate");
	}
	
	public M setShsjEdate(java.util.Date shsjEdate) {
		set("shsj_edate", shsjEdate);
		return (M)this;
	}
	
	public java.util.Date getShsjEdate() {
		return getDate("shsj_edate");
	}
	
	public M setBdddText(java.lang.String bdddText) {
		set("bddd_text", bdddText);
		return (M)this;
	}
	
	public java.lang.String getBdddText() {
		return getStr("bddd_text");
	}
	
	public M setBdddValue(java.lang.String bdddValue) {
		set("bddd_value", bdddValue);
		return (M)this;
	}
	
	public java.lang.String getBdddValue() {
		return getStr("bddd_value");
	}
	
	public M setRxtzStatusText(java.lang.String rxtzStatusText) {
		set("rxtz_status_text", rxtzStatusText);
		return (M)this;
	}
	
	public java.lang.String getRxtzStatusText() {
		return getStr("rxtz_status_text");
	}
	
	public M setRxtzStatusValue(java.lang.String rxtzStatusValue) {
		set("rxtz_status_value", rxtzStatusValue);
		return (M)this;
	}
	
	public java.lang.String getRxtzStatusValue() {
		return getStr("rxtz_status_value");
	}
	
	public M setGxzh(java.lang.String gxzh) {
		set("gxzh", gxzh);
		return (M)this;
	}
	
	public java.lang.String getGxzh() {
		return getStr("gxzh");
	}
	
	public M setZzyText(java.lang.String zzyText) {
		set("zzy_text", zzyText);
		return (M)this;
	}
	
	public java.lang.String getZzyText() {
		return getStr("zzy_text");
	}
	
	public M setZzyValue(java.lang.String zzyValue) {
		set("zzy_value", zzyValue);
		return (M)this;
	}
	
	public java.lang.String getZzyValue() {
		return getStr("zzy_value");
	}
	
	public M setPxf(java.lang.String pxf) {
		set("pxf", pxf);
		return (M)this;
	}
	
	public java.lang.String getPxf() {
		return getStr("pxf");
	}
	
	public M setStatusText(java.lang.String statusText) {
		set("status_text", statusText);
		return (M)this;
	}
	
	public java.lang.String getStatusText() {
		return getStr("status_text");
	}
	
	public M setStatusValue(java.lang.String statusValue) {
		set("status_value", statusValue);
		return (M)this;
	}
	
	public java.lang.String getStatusValue() {
		return getStr("status_value");
	}
	
	public M setPxnr(java.lang.String pxnr) {
		set("pxnr", pxnr);
		return (M)this;
	}
	
	public java.lang.String getPxnr() {
		return getStr("pxnr");
	}
	
	public M setXjdabh(java.lang.String xjdabh) {
		set("xjdabh", xjdabh);
		return (M)this;
	}
	
	public java.lang.String getXjdabh() {
		return getStr("xjdabh");
	}
	
	public M setJhrs(java.lang.String jhrs) {
		set("jhrs", jhrs);
		return (M)this;
	}
	
	public java.lang.String getJhrs() {
		return getStr("jhrs");
	}
	
	public M setPxbz(java.lang.String pxbz) {
		set("pxbz", pxbz);
		return (M)this;
	}
	
	public java.lang.String getPxbz() {
		return getStr("pxbz");
	}
	
	public M setSjrsm(java.lang.String sjrsm) {
		set("sjrsm", sjrsm);
		return (M)this;
	}
	
	public java.lang.String getSjrsm() {
		return getStr("sjrsm");
	}
	
	public M setSjrsw(java.lang.String sjrsw) {
		set("sjrsw", sjrsw);
		return (M)this;
	}
	
	public java.lang.String getSjrsw() {
		return getStr("sjrsw");
	}
	
	public M setBcxzText(java.lang.String bcxzText) {
		set("bcxz_text", bcxzText);
		return (M)this;
	}
	
	public java.lang.String getBcxzText() {
		return getStr("bcxz_text");
	}
	
	public M setBcxzValue(java.lang.String bcxzValue) {
		set("bcxz_value", bcxzValue);
		return (M)this;
	}
	
	public java.lang.String getBcxzValue() {
		return getStr("bcxz_value");
	}
	
	public M setKcszrText(java.lang.String kcszrText) {
		set("kcszr_text", kcszrText);
		return (M)this;
	}
	
	public java.lang.String getKcszrText() {
		return getStr("kcszr_text");
	}
	
	public M setKcszrValue(java.lang.String kcszrValue) {
		set("kcszr_value", kcszrValue);
		return (M)this;
	}
	
	public java.lang.String getKcszrValue() {
		return getStr("kcszr_value");
	}
	
	public M setXzllyText(java.lang.String xzllyText) {
		set("xzlly_text", xzllyText);
		return (M)this;
	}
	
	public java.lang.String getXzllyText() {
		return getStr("xzlly_text");
	}
	
	public M setXzllyValue(java.lang.String xzllyValue) {
		set("xzlly_value", xzllyValue);
		return (M)this;
	}
	
	public java.lang.String getXzllyValue() {
		return getStr("xzlly_value");
	}
	
	public M setUpxzfile(java.lang.String upxzfile) {
		set("upxzfile", upxzfile);
		return (M)this;
	}
	
	public java.lang.String getUpxzfile() {
		return getStr("upxzfile");
	}
	
	public M setXzyts(java.lang.String xzyts) {
		set("xzyts", xzyts);
		return (M)this;
	}
	
	public java.lang.String getXzyts() {
		return getStr("xzyts");
	}
	
	public M setZzyzlText(java.lang.String zzyzlText) {
		set("zzyzl_text", zzyzlText);
		return (M)this;
	}
	
	public java.lang.String getZzyzlText() {
		return getStr("zzyzl_text");
	}
	
	public M setZzyzlValue(java.lang.String zzyzlValue) {
		set("zzyzl_value", zzyzlValue);
		return (M)this;
	}
	
	public java.lang.String getZzyzlValue() {
		return getStr("zzyzl_value");
	}
	
	public M setGroupLeaderText(java.lang.String groupLeaderText) {
		set("group_leader_text", groupLeaderText);
		return (M)this;
	}
	
	public java.lang.String getGroupLeaderText() {
		return getStr("group_leader_text");
	}
	
	public M setGroupLeaderValue(java.lang.String groupLeaderValue) {
		set("group_leader_value", groupLeaderValue);
		return (M)this;
	}
	
	public java.lang.String getGroupLeaderValue() {
		return getStr("group_leader_value");
	}
	
	public M setBjjc(java.lang.String bjjc) {
		set("bjjc", bjjc);
		return (M)this;
	}
	
	public java.lang.String getBjjc() {
		return getStr("bjjc");
	}
	
	public M setAdmissionNotice(java.lang.String admissionNotice) {
		set("admissionNotice", admissionNotice);
		return (M)this;
	}
	
	public java.lang.String getAdmissionNotice() {
		return getStr("admissionNotice");
	}
	
	public M setZq(java.lang.String zq) {
		set("zq", zq);
		return (M)this;
	}
	
	public java.lang.String getZq() {
		return getStr("zq");
	}
	
	public M setGzrys(java.lang.String gzrys) {
		set("gzrys", gzrys);
		return (M)this;
	}
	
	public java.lang.String getGzrys() {
		return getStr("gzrys");
	}
	
	public M setBoxNumber(java.lang.String boxNumber) {
		set("boxNumber", boxNumber);
		return (M)this;
	}
	
	public java.lang.String getBoxNumber() {
		return getStr("boxNumber");
	}
	
	public M setXbryText(java.lang.String xbryText) {
		set("xbry_text", xbryText);
		return (M)this;
	}
	
	public java.lang.String getXbryText() {
		return getStr("xbry_text");
	}
	
	public M setXbryValue(java.lang.String xbryValue) {
		set("xbry_value", xbryValue);
		return (M)this;
	}
	
	public java.lang.String getXbryValue() {
		return getStr("xbry_value");
	}
	
	public M setPxdx(java.lang.String pxdx) {
		set("pxdx", pxdx);
		return (M)this;
	}
	
	public java.lang.String getPxdx() {
		return getStr("pxdx");
	}
	
	public M setUpjxdg(java.lang.String upjxdg) {
		set("upjxdg", upjxdg);
		return (M)this;
	}
	
	public java.lang.String getUpjxdg() {
		return getStr("upjxdg");
	}
	
	public M setXgcl(java.lang.String xgcl) {
		set("xgcl", xgcl);
		return (M)this;
	}
	
	public java.lang.String getXgcl() {
		return getStr("xgcl");
	}
	
	public M setLogFlag(java.lang.String logFlag) {
		set("logFlag", logFlag);
		return (M)this;
	}
	
	public java.lang.String getLogFlag() {
		return getStr("logFlag");
	}
	
	public M setOutFlag(java.lang.String outFlag) {
		set("outFlag", outFlag);
		return (M)this;
	}
	
	public java.lang.String getOutFlag() {
		return getStr("outFlag");
	}
	
	public M setBm(java.lang.String bm) {
		set("bm", bm);
		return (M)this;
	}
	
	public java.lang.String getBm() {
		return getStr("bm");
	}
	
	public M setLxr(java.lang.String lxr) {
		set("lxr", lxr);
		return (M)this;
	}
	
	public java.lang.String getLxr() {
		return getStr("lxr");
	}
	
	public M setWtzjdwText(java.lang.String wtzjdwText) {
		set("wtzjdw_text", wtzjdwText);
		return (M)this;
	}
	
	public java.lang.String getWtzjdwText() {
		return getStr("wtzjdw_text");
	}
	
	public M setWtzjdwValue(java.lang.String wtzjdwValue) {
		set("wtzjdw_value", wtzjdwValue);
		return (M)this;
	}
	
	public java.lang.String getWtzjdwValue() {
		return getStr("wtzjdw_value");
	}
	
	public M setZw(java.lang.String zw) {
		set("zw", zw);
		return (M)this;
	}
	
	public java.lang.String getZw() {
		return getStr("zw");
	}
	
	public M setFzbmText(java.lang.String fzbmText) {
		set("fzbm_text", fzbmText);
		return (M)this;
	}
	
	public java.lang.String getFzbmText() {
		return getStr("fzbm_text");
	}
	
	public M setFzbmValue(java.lang.String fzbmValue) {
		set("fzbm_value", fzbmValue);
		return (M)this;
	}
	
	public java.lang.String getFzbmValue() {
		return getStr("fzbm_value");
	}
	
	public M setXyjbText(java.lang.String xyjbText) {
		set("xyjb_text", xyjbText);
		return (M)this;
	}
	
	public java.lang.String getXyjbText() {
		return getStr("xyjb_text");
	}
	
	public M setXyjbValue(java.lang.String xyjbValue) {
		set("xyjb_value", xyjbValue);
		return (M)this;
	}
	
	public java.lang.String getXyjbValue() {
		return getStr("xyjb_value");
	}
	
	public M setLxdh(java.lang.String lxdh) {
		set("lxdh", lxdh);
		return (M)this;
	}
	
	public java.lang.String getLxdh() {
		return getStr("lxdh");
	}
	
	public M setBjtxlText(java.lang.String bjtxlText) {
		set("bjtxl_text", bjtxlText);
		return (M)this;
	}
	
	public java.lang.String getBjtxlText() {
		return getStr("bjtxl_text");
	}
	
	public M setBjtxlValue(java.lang.String bjtxlValue) {
		set("bjtxl_value", bjtxlValue);
		return (M)this;
	}
	
	public java.lang.String getBjtxlValue() {
		return getStr("bjtxl_value");
	}
	
	public M setHoldLocationText(java.lang.String holdLocationText) {
		set("hold_location_text", holdLocationText);
		return (M)this;
	}
	
	public java.lang.String getHoldLocationText() {
		return getStr("hold_location_text");
	}
	
	public M setHoldLocationValue(java.lang.String holdLocationValue) {
		set("hold_location_value", holdLocationValue);
		return (M)this;
	}
	
	public java.lang.String getHoldLocationValue() {
		return getStr("hold_location_value");
	}
	
	public M setAddItemSum(java.math.BigDecimal addItemSum) {
		set("add_item_sum", addItemSum);
		return (M)this;
	}
	
	public java.math.BigDecimal getAddItemSum() {
		return get("add_item_sum");
	}
	
	public M setPerCostText(java.lang.String perCostText) {
		set("per_cost_text", perCostText);
		return (M)this;
	}
	
	public java.lang.String getPerCostText() {
		return getStr("per_cost_text");
	}
	
	public M setPerCostValue(java.lang.String perCostValue) {
		set("per_cost_value", perCostValue);
		return (M)this;
	}
	
	public java.lang.String getPerCostValue() {
		return getStr("per_cost_value");
	}
	
	public M setCostExplain(java.lang.String costExplain) {
		set("cost_explain", costExplain);
		return (M)this;
	}
	
	public java.lang.String getCostExplain() {
		return getStr("cost_explain");
	}
	
	public M setCostSum(java.math.BigDecimal costSum) {
		set("cost_sum", costSum);
		return (M)this;
	}
	
	public java.math.BigDecimal getCostSum() {
		return get("cost_sum");
	}
	
	public M setOtherExplain(java.lang.String otherExplain) {
		set("other_explain", otherExplain);
		return (M)this;
	}
	
	public java.lang.String getOtherExplain() {
		return getStr("other_explain");
	}
	
	public M setXyjb(java.lang.String xyjb) {
		set("xyjb", xyjb);
		return (M)this;
	}
	
	public java.lang.String getXyjb() {
		return getStr("xyjb");
	}
	
	public M setSjts(java.lang.String sjts) {
		set("sjts", sjts);
		return (M)this;
	}
	
	public java.lang.String getSjts() {
		return getStr("sjts");
	}
	
	public M setDzflText(java.lang.String dzflText) {
		set("dzfl_text", dzflText);
		return (M)this;
	}
	
	public java.lang.String getDzflText() {
		return getStr("dzfl_text");
	}
	
	public M setDzflValue(java.lang.String dzflValue) {
		set("dzfl_value", dzflValue);
		return (M)this;
	}
	
	public java.lang.String getDzflValue() {
		return getStr("dzfl_value");
	}
	
	public M setFyjsbid(java.lang.String fyjsbid) {
		set("fyjsbid", fyjsbid);
		return (M)this;
	}
	
	public java.lang.String getFyjsbid() {
		return getStr("fyjsbid");
	}
	
	public M setWfinfoWfId(java.lang.String wfinfoWfId) {
		set("wfinfo_wf_id", wfinfoWfId);
		return (M)this;
	}
	
	public java.lang.String getWfinfoWfId() {
		return getStr("wfinfo_wf_id");
	}
	
	public M setWfinfoWfName(java.lang.String wfinfoWfName) {
		set("wfinfo_wf_name", wfinfoWfName);
		return (M)this;
	}
	
	public java.lang.String getWfinfoWfName() {
		return getStr("wfinfo_wf_name");
	}
	
	public M setWfinfoWfPid(java.lang.String wfinfoWfPid) {
		set("wfinfo_wf_pid", wfinfoWfPid);
		return (M)this;
	}
	
	public java.lang.String getWfinfoWfPid() {
		return getStr("wfinfo_wf_pid");
	}
	
	public M setWfinfoWfDeptid(java.lang.String wfinfoWfDeptid) {
		set("wfinfo_wf_deptid", wfinfoWfDeptid);
		return (M)this;
	}
	
	public java.lang.String getWfinfoWfDeptid() {
		return getStr("wfinfo_wf_deptid");
	}
	
	public M setWfinfoWfDeptname(java.lang.String wfinfoWfDeptname) {
		set("wfinfo_wf_deptname", wfinfoWfDeptname);
		return (M)this;
	}
	
	public java.lang.String getWfinfoWfDeptname() {
		return getStr("wfinfo_wf_deptname");
	}
	
	public M setWfinfoWfUserid(java.lang.String wfinfoWfUserid) {
		set("wfinfo_wf_userid", wfinfoWfUserid);
		return (M)this;
	}
	
	public java.lang.String getWfinfoWfUserid() {
		return getStr("wfinfo_wf_userid");
	}
	
	public M setWfinfoWfUsername(java.lang.String wfinfoWfUsername) {
		set("wfinfo_wf_username", wfinfoWfUsername);
		return (M)this;
	}
	
	public java.lang.String getWfinfoWfUsername() {
		return getStr("wfinfo_wf_username");
	}
	
	public M setWfinfoWfCreatetime(java.util.Date wfinfoWfCreatetime) {
		set("wfinfo_wf_createtime", wfinfoWfCreatetime);
		return (M)this;
	}
	
	public java.util.Date getWfinfoWfCreatetime() {
		return getDate("wfinfo_wf_createtime");
	}
	
	public M setWfinfoWfStatus(java.math.BigDecimal wfinfoWfStatus) {
		set("wfinfo_wf_status", wfinfoWfStatus);
		return (M)this;
	}
	
	public java.math.BigDecimal getWfinfoWfStatus() {
		return get("wfinfo_wf_status");
	}
	
	public M setWfinfoWfDeadline(java.util.Date wfinfoWfDeadline) {
		set("wfinfo_wf_deadLine", wfinfoWfDeadline);
		return (M)this;
	}
	
	public java.util.Date getWfinfoWfDeadline() {
		return getDate("wfinfo_wf_deadLine");
	}
	
	public M setJxjhFile(java.lang.String jxjhFile) {
		set("jxjh_file", jxjhFile);
		return (M)this;
	}
	
	public java.lang.String getJxjhFile() {
		return getStr("jxjh_file");
	}
	
	public M setSeatpdf(java.lang.String seatpdf) {
		set("seatpdf", seatpdf);
		return (M)this;
	}
	
	public java.lang.String getSeatpdf() {
		return getStr("seatpdf");
	}
	
	public M setAbstract(java.lang.String _abstract) {
		set("abstract", _abstract);
		return (M)this;
	}
	
	public java.lang.String getAbstract() {
		return getStr("abstract");
	}
	
	public M setLabelsText(java.lang.String labelsText) {
		set("labels_text", labelsText);
		return (M)this;
	}
	
	public java.lang.String getLabelsText() {
		return getStr("labels_text");
	}
	
	public M setLabelsValue(java.lang.String labelsValue) {
		set("labels_value", labelsValue);
		return (M)this;
	}
	
	public java.lang.String getLabelsValue() {
		return getStr("labels_value");
	}
	
	public M setTypeText(java.lang.String typeText) {
		set("type_text", typeText);
		return (M)this;
	}
	
	public java.lang.String getTypeText() {
		return getStr("type_text");
	}
	
	public M setTypeValue(java.lang.String typeValue) {
		set("type_value", typeValue);
		return (M)this;
	}
	
	public java.lang.String getTypeValue() {
		return getStr("type_value");
	}
	
	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	public M setCover(java.lang.String cover) {
		set("cover", cover);
		return (M)this;
	}
	
	public java.lang.String getCover() {
		return getStr("cover");
	}
	
	public M setDingIsgroupchatText(java.lang.String dingIsgroupchatText) {
		set("ding_isgroupchat_text", dingIsgroupchatText);
		return (M)this;
	}
	
	public java.lang.String getDingIsgroupchatText() {
		return getStr("ding_isgroupchat_text");
	}
	
	public M setDingIsgroupchatValue(java.lang.String dingIsgroupchatValue) {
		set("ding_isgroupchat_value", dingIsgroupchatValue);
		return (M)this;
	}
	
	public java.lang.String getDingIsgroupchatValue() {
		return getStr("ding_isgroupchat_value");
	}
	
	public M setDingIsscheduleText(java.lang.String dingIsscheduleText) {
		set("ding_isschedule_text", dingIsscheduleText);
		return (M)this;
	}
	
	public java.lang.String getDingIsscheduleText() {
		return getStr("ding_isschedule_text");
	}
	
	public M setDingIsscheduleValue(java.lang.String dingIsscheduleValue) {
		set("ding_isschedule_value", dingIsscheduleValue);
		return (M)this;
	}
	
	public java.lang.String getDingIsscheduleValue() {
		return getStr("ding_isschedule_value");
	}
	
	public M setDingIsbacklogText(java.lang.String dingIsbacklogText) {
		set("ding_isbacklog_text", dingIsbacklogText);
		return (M)this;
	}
	
	public java.lang.String getDingIsbacklogText() {
		return getStr("ding_isbacklog_text");
	}
	
	public M setDingChatname(java.lang.String dingChatname) {
		set("ding_chatName", dingChatname);
		return (M)this;
	}
	
	public java.lang.String getDingChatname() {
		return getStr("ding_chatName");
	}
	
	public M setDingIsbacklogValue(java.lang.String dingIsbacklogValue) {
		set("ding_isbacklog_value", dingIsbacklogValue);
		return (M)this;
	}
	
	public java.lang.String getDingIsbacklogValue() {
		return getStr("ding_isbacklog_value");
	}
	
	public M setBxryxs(java.lang.String bxryxs) {
		set("bxryxs", bxryxs);
		return (M)this;
	}
	
	public java.lang.String getBxryxs() {
		return getStr("bxryxs");
	}
	
	public M setXxryms(java.lang.String xxryms) {
		set("xxryms", xxryms);
		return (M)this;
	}
	
	public java.lang.String getXxryms() {
		return getStr("xxryms");
	}
	
	public M setXxryxs(java.lang.String xxryxs) {
		set("xxryxs", xxryxs);
		return (M)this;
	}
	
	public java.lang.String getXxryxs() {
		return getStr("xxryxs");
	}
	
	public M setBxryms(java.lang.String bxryms) {
		set("bxryms", bxryms);
		return (M)this;
	}
	
	public java.lang.String getBxryms() {
		return getStr("bxryms");
	}
	
	public M setCdpkText(java.lang.String cdpkText) {
		set("cdpk_text", cdpkText);
		return (M)this;
	}
	
	public java.lang.String getCdpkText() {
		return getStr("cdpk_text");
	}
	
	public M setCdpkValue(java.lang.String cdpkValue) {
		set("cdpk_value", cdpkValue);
		return (M)this;
	}
	
	public java.lang.String getCdpkValue() {
		return getStr("cdpk_value");
	}
	
	public M setJcapText(java.lang.String jcapText) {
		set("jcap_text", jcapText);
		return (M)this;
	}
	
	public java.lang.String getJcapText() {
		return getStr("jcap_text");
	}
	
	public M setJcapValue(java.lang.String jcapValue) {
		set("jcap_value", jcapValue);
		return (M)this;
	}
	
	public java.lang.String getJcapValue() {
		return getStr("jcap_value");
	}
	
	public M setJtlx(java.lang.String jtlx) {
		set("jtlx", jtlx);
		return (M)this;
	}
	
	public java.lang.String getJtlx() {
		return getStr("jtlx");
	}
	
	public M setZsapText(java.lang.String zsapText) {
		set("zsap_text", zsapText);
		return (M)this;
	}
	
	public java.lang.String getZsapText() {
		return getStr("zsap_text");
	}
	
	public M setZsapValue(java.lang.String zsapValue) {
		set("zsap_value", zsapValue);
		return (M)this;
	}
	
	public java.lang.String getZsapValue() {
		return getStr("zsap_value");
	}
	
	public M setSszcbm(java.lang.String sszcbm) {
		set("sszcbm", sszcbm);
		return (M)this;
	}
	
	public java.lang.String getSszcbm() {
		return getStr("sszcbm");
	}
	
	public M setCoverPhoto(java.lang.String coverPhoto) {
		set("cover_photo", coverPhoto);
		return (M)this;
	}
	
	public java.lang.String getCoverPhoto() {
		return getStr("cover_photo");
	}
	
	public M setCoverConver(java.lang.String coverConver) {
		set("cover_conver", coverConver);
		return (M)this;
	}
	
	public java.lang.String getCoverConver() {
		return getStr("cover_conver");
	}
	
	public M setApplyAuditValue(java.lang.String applyAuditValue) {
		set("apply_audit_value", applyAuditValue);
		return (M)this;
	}
	
	public java.lang.String getApplyAuditValue() {
		return getStr("apply_audit_value");
	}
	
	public M setApplyAuditText(java.lang.String applyAuditText) {
		set("apply_audit_text", applyAuditText);
		return (M)this;
	}
	
	public java.lang.String getApplyAuditText() {
		return getStr("apply_audit_text");
	}
	
	public M setSxBj(java.math.BigDecimal sxBj) {
		set("sx_bj", sxBj);
		return (M)this;
	}
	
	public java.math.BigDecimal getSxBj() {
		return get("sx_bj");
	}
	
	public M setSkdd2Text(java.lang.String skdd2Text) {
		set("skdd2_text", skdd2Text);
		return (M)this;
	}
	
	public java.lang.String getSkdd2Text() {
		return getStr("skdd2_text");
	}
	
	public M setFilledDate(java.util.Date filledDate) {
		set("filled_date", filledDate);
		return (M)this;
	}
	
	public java.util.Date getFilledDate() {
		return getDate("filled_date");
	}
	
	public M setSxHhtf(java.math.BigDecimal sxHhtf) {
		set("sx_hhtf", sxHhtf);
		return (M)this;
	}
	
	public java.math.BigDecimal getSxHhtf() {
		return get("sx_hhtf");
	}
	
	public M setPmStart(java.sql.Time pmStart) {
		set("pm_start", pmStart);
		return (M)this;
	}
	
	public java.sql.Time getPmStart() {
		return get("pm_start");
	}
	
	public M setWsNlbj(java.math.BigDecimal wsNlbj) {
		set("ws_nlbj", wsNlbj);
		return (M)this;
	}
	
	public java.math.BigDecimal getWsNlbj() {
		return get("ws_nlbj");
	}
	
	public M setWsTj(java.math.BigDecimal wsTj) {
		set("ws_tj", wsTj);
		return (M)this;
	}
	
	public java.math.BigDecimal getWsTj() {
		return get("ws_tj");
	}
	
	public M setBaseCost(java.math.BigDecimal baseCost) {
		set("base_cost", baseCost);
		return (M)this;
	}
	
	public java.math.BigDecimal getBaseCost() {
		return get("base_cost");
	}
	
	public M setWsDj(java.math.BigDecimal wsDj) {
		set("ws_dj", wsDj);
		return (M)this;
	}
	
	public java.math.BigDecimal getWsDj() {
		return get("ws_dj");
	}
	
	public M setWxTjone(java.math.BigDecimal wxTjone) {
		set("wx_tjone", wxTjone);
		return (M)this;
	}
	
	public java.math.BigDecimal getWxTjone() {
		return get("wx_tjone");
	}
	
	public M setWxBjtwo(java.math.BigDecimal wxBjtwo) {
		set("wx_bjtwo", wxBjtwo);
		return (M)this;
	}
	
	public java.math.BigDecimal getWxBjtwo() {
		return get("wx_bjtwo");
	}
	
	public M setAmStart(java.sql.Time amStart) {
		set("am_start", amStart);
		return (M)this;
	}
	
	public java.sql.Time getAmStart() {
		return get("am_start");
	}
	
	public M setXsBj(java.math.BigDecimal xsBj) {
		set("xs_bj", xsBj);
		return (M)this;
	}
	
	public java.math.BigDecimal getXsBj() {
		return get("xs_bj");
	}
	
	public M setWxDjone(java.math.BigDecimal wxDjone) {
		set("wx_djone", wxDjone);
		return (M)this;
	}
	
	public java.math.BigDecimal getWxDjone() {
		return get("wx_djone");
	}
	
	public M setSxDj(java.math.BigDecimal sxDj) {
		set("sx_dj", sxDj);
		return (M)this;
	}
	
	public java.math.BigDecimal getSxDj() {
		return get("sx_dj");
	}
	
}

