package com.dsfa.nc.web.pd.domain.courses.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBjglFlowTest<M extends BaseBjglFlowTest<M>> extends Model<M> implements IBean {

	public M setTeasJwglBjglFlowTestId(java.lang.String teasJwglBjglFlowTestId) {
		set("teas_jwgl_bjgl_flow_test_id", teasJwglBjglFlowTestId);
		return (M)this;
	}
	
	public java.lang.String getTeasJwglBjglFlowTestId() {
		return getStr("teas_jwgl_bjgl_flow_test_id");
	}
	
	public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsDeptId(java.lang.String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public java.lang.String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
	public M setDsCreateUserName(java.lang.String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsCreateUserId(java.lang.String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsDeleted(java.lang.String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public java.lang.String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsOrder(java.lang.Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public java.lang.Integer getDsOrder() {
		return getInt("ds_order");
	}
	
	public M setDsUnitId(java.lang.String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public java.lang.String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setWfinfoWfId(java.lang.String wfinfoWfId) {
		set("wfinfo_wf_id", wfinfoWfId);
		return (M)this;
	}
	
	public java.lang.String getWfinfoWfId() {
		return getStr("wfinfo_wf_id");
	}
	
	public M setWfinfoWfName(java.lang.String wfinfoWfName) {
		set("wfinfo_wf_name", wfinfoWfName);
		return (M)this;
	}
	
	public java.lang.String getWfinfoWfName() {
		return getStr("wfinfo_wf_name");
	}
	
	public M setObjectname(java.lang.String objectname) {
		set("objectname", objectname);
		return (M)this;
	}
	
	public java.lang.String getObjectname() {
		return getStr("objectname");
	}
	
	public M setPoint(java.lang.String point) {
		set("point", point);
		return (M)this;
	}
	
	public java.lang.String getPoint() {
		return getStr("point");
	}
	
}

