package com.dsfa.nc.pd.lesson.specialClass.persistence;

import com.dsfa.nc.pd.lesson.specialClass.persistence.base.BaseBjglZjswdxOutSub;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglZjswdxOutSub extends BaseBjglZjswdxOutSub<BjglZjswdxOutSub> {
	public static final BjglZjswdxOutSub dao = new BjglZjswdxOutSub().dao();
}

