package com.dsfa.nc.pd.lesson.specialClass.persistence;

import com.dsfa.nc.pd.lesson.specialClass.persistence.base.BaseBjglXyxx;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglXyxx extends BaseBjglXyxx<BjglXyxx> {
	public static final BjglXyxx dao = new BjglXyxx().dao();
}

