package com.dsfa.nc.pd.lesson.specialClass.persistence;

import com.dsfa.nc.pd.lesson.specialClass.persistence.base.BaseBjglZbgl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglZbgl extends BaseBjglZbgl<BjglZbgl> {
	public static final BjglZbgl dao = new BjglZbgl().dao();
}

