package com.dsfa.nc.pd.lesson.specialClass.persistence;

import com.dsfa.nc.pd.lesson.specialClass.persistence.base.BaseBjglTreegl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglTreegl extends BaseBjglTreegl<BjglTreegl> {
	public static final BjglTreegl dao = new BjglTreegl().dao();
}

