package com.dsfa.nc.pd.lesson.specialClass.persistence;

import com.dsfa.nc.pd.lesson.specialClass.persistence.base.BaseBjglLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglLog extends BaseBjglLog<BjglLog> {
	public static final BjglLog dao = new BjglLog().dao();
}

