package com.dsfa.nc.pd.lesson.specialClass.persistence;

import com.dsfa.nc.pd.lesson.specialClass.persistence.base.BaseBjglMealDemand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglMealDemand extends BaseBjglMealDemand<BjglMealDemand> {
	public static final BjglMealDemand dao = new BjglMealDemand().dao();
}

