package com.dsfa.nc.pd.lesson.specialClass.persistence;

import com.dsfa.nc.pd.lesson.specialClass.persistence.base.BaseBjglRoomOccupy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglRoomOccupy extends BaseBjglRoomOccupy<BjglRoomOccupy> {
	public static final BjglRoomOccupy dao = new BjglRoomOccupy().dao();
}

