package com.dsfa.nc.pd.lesson.specialClass.persistence;

import com.dsfa.nc.pd.lesson.specialClass.persistence.base.BaseBjglZjswdxOut;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglZjswdxOut extends BaseBjglZjswdxOut<BjglZjswdxOut> {
	public static final BjglZjswdxOut dao = new BjglZjswdxOut().dao();
}

