package com.dsfa.nc.pd.lesson.specialClass.persistence;

import com.dsfa.nc.pd.lesson.specialClass.persistence.base.BaseBjglZjswdxOutAdd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglZjswdxOutAdd extends BaseBjglZjswdxOutAdd<BjglZjswdxOutAdd> {
	public static final BjglZjswdxOutAdd dao = new BjglZjswdxOutAdd().dao();
}

