package com.dsfa.nc.pd.lesson.specialClass.persistence;

import com.dsfa.nc.pd.lesson.specialClass.persistence.base.BaseBjglGbjs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglGbjs extends BaseBjglGbjs<BjglGbjs> {
	public static final BjglGbjs dao = new BjglGbjs().dao();
}

