package com.dsfa.nc.pd.lesson.specialClass.persistence;

import com.dsfa.nc.pd.lesson.specialClass.persistence.base.BaseBjglOutClassFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BjglOutClassFlow extends BaseBjglOutClassFlow<BjglOutClassFlow> {
	public static final BjglOutClassFlow dao = new BjglOutClassFlow().dao();
}

