package com.dsfa.nc.pd.lesson.specialClass.persistence;

import com.dsfa.nc.pd.lesson.specialClass.persistence.base.BaseStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Student extends BaseStudent<Student> {
	public static final Student dao = new Student().dao();
}

