package com.dsfa.nc.web.pd.specialClass.persistence.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBjglBjwbdwedit<M extends BaseBjglBjwbdwedit<M>> extends Model<M> implements IBean {

	public M setTeasJwglBjglBjwbdweditId(String teasJwglBjglBjwbdweditId) {
		set("teas_jwgl_bjgl_bjwbdwEdit_id", teasJwglBjglBjwbdweditId);
		return (M)this;
	}

	public String getTeasJwglBjglBjwbdweditId() {
		return getStr("teas_jwgl_bjgl_bjwbdwEdit_id");
	}

	public M setDsUpdateUserId(String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}

	public String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}

	public M setDsCreateUserName(String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}

	public String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}

	public M setDsCreateUserId(String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}

	public String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}

	public M setDsUpdateUserName(String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}

	public String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}

	public M setDsDeleted(String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}

	public String getDsDeleted() {
		return getStr("ds_deleted");
	}

	public M setDsOrder(Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}

	public Integer getDsOrder() {
		return getInt("ds_order");
	}

	public M setDsUnitId(String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}

	public String getDsUnitId() {
		return getStr("ds_unit_id");
	}

	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}

	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}

	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}

	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}

	public M setTeasJwglBjglId(String teasJwglBjglId) {
		set("teas_jwgl_bjgl_id", teasJwglBjglId);
		return (M)this;
	}

	public String getTeasJwglBjglId() {
		return getStr("teas_jwgl_bjgl_id");
	}

	public M setWbdwryText(String wbdwryText) {
		set("wbdwry_text", wbdwryText);
		return (M)this;
	}

	public String getWbdwryText() {
		return getStr("wbdwry_text");
	}

	public M setWbdwryValue(String wbdwryValue) {
		set("wbdwry_value", wbdwryValue);
		return (M)this;
	}

	public String getWbdwryValue() {
		return getStr("wbdwry_value");
	}

	public M setWbdwrysl(String wbdwrysl) {
		set("wbdwrysl", wbdwrysl);
		return (M)this;
	}

	public String getWbdwrysl() {
		return getStr("wbdwrysl");
	}

	public M setBz(String bz) {
		set("bz", bz);
		return (M)this;
	}

	public String getBz() {
		return getStr("bz");
	}

	public M setDsDeptId(String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}

	public String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
}

