package com.dsfa.nc.web.pd.specialClass.persistence.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBjglRoomOccupy<M extends BaseBjglRoomOccupy<M>> extends Model<M> implements IBean {

	public M setTeasJwglBjglRoomOccupyId(String teasJwglBjglRoomOccupyId) {
		set("teas_jwgl_bjgl_room_occupy_id", teasJwglBjglRoomOccupyId);
		return (M)this;
	}

	public String getTeasJwglBjglRoomOccupyId() {
		return getStr("teas_jwgl_bjgl_room_occupy_id");
	}

	public M setDsUpdateUserId(String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}

	public String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}

	public M setDsDeptId(String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}

	public String getDsDeptId() {
		return getStr("ds_dept_id");
	}

	public M setDsCreateUserName(String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}

	public String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}

	public M setDsCreateUserId(String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}

	public String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}

	public M setDsUpdateUserName(String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}

	public String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}

	public M setDsDeleted(String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}

	public String getDsDeleted() {
		return getStr("ds_deleted");
	}

	public M setDsOrder(Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}

	public Integer getDsOrder() {
		return getInt("ds_order");
	}

	public M setDsUnitId(String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}

	public String getDsUnitId() {
		return getStr("ds_unit_id");
	}

	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}

	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}

	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}

	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}

	public M setTeasJwglBjglId(String teasJwglBjglId) {
		set("teas_jwgl_bjgl_id", teasJwglBjglId);
		return (M)this;
	}

	public String getTeasJwglBjglId() {
		return getStr("teas_jwgl_bjgl_id");
	}

	public M setOccupyLocationText(String occupyLocationText) {
		set("occupy_location_text", occupyLocationText);
		return (M)this;
	}

	public String getOccupyLocationText() {
		return getStr("occupy_location_text");
	}

	public M setOccupyLocationValue(String occupyLocationValue) {
		set("occupy_location_value", occupyLocationValue);
		return (M)this;
	}

	public String getOccupyLocationValue() {
		return getStr("occupy_location_value");
	}

	public M setPmStart(java.sql.Time pmStart) {
		set("pm_start", pmStart);
		return (M)this;
	}

	public java.sql.Time getPmStart() {
		return get("pm_start");
	}

	public M setAmEnd(java.sql.Time amEnd) {
		set("am_end", amEnd);
		return (M)this;
	}

	public java.sql.Time getAmEnd() {
		return get("am_end");
	}

	public M setOccupyDate(java.util.Date occupyDate) {
		set("occupy_date", occupyDate);
		return (M)this;
	}

	public java.util.Date getOccupyDate() {
		return getDate("occupy_date");
	}

	public M setAmText(String amText) {
		set("am_text", amText);
		return (M)this;
	}

	public String getAmText() {
		return getStr("am_text");
	}

	public M setAmValue(String amValue) {
		set("am_value", amValue);
		return (M)this;
	}

	public String getAmValue() {
		return getStr("am_value");
	}

	public M setNightText(String nightText) {
		set("night_text", nightText);
		return (M)this;
	}

	public String getNightText() {
		return getStr("night_text");
	}

	public M setNightValue(String nightValue) {
		set("night_value", nightValue);
		return (M)this;
	}

	public String getNightValue() {
		return getStr("night_value");
	}

	public M setAmStart(java.sql.Time amStart) {
		set("am_start", amStart);
		return (M)this;
	}

	public java.sql.Time getAmStart() {
		return get("am_start");
	}

	public M setPmEnd(java.sql.Time pmEnd) {
		set("pm_end", pmEnd);
		return (M)this;
	}

	public java.sql.Time getPmEnd() {
		return get("pm_end");
	}

	public M setPmText(String pmText) {
		set("pm_text", pmText);
		return (M)this;
	}

	public String getPmText() {
		return getStr("pm_text");
	}

	public M setPmValue(String pmValue) {
		set("pm_value", pmValue);
		return (M)this;
	}

	public String getPmValue() {
		return getStr("pm_value");
	}
	
}

