package com.dsfa.nc.pd.lesson.Do.base;

import com.dsfa.platform.starter.meta.base.DsfaBaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCoursewareLog<M extends BaseCoursewareLog<M>> extends DsfaBaseModel<M> implements IBean {

	public M setNcCoursesCoursewareLogId(String ncCoursesCoursewareLogId) {
		set("nc_courses_courseware_log_id", ncCoursesCoursewareLogId);
		return (M)this;
	}
	
	public String getNcCoursesCoursewareLogId() {
		return getStr("nc_courses_courseware_log_id");
	}
	
	public M setDsUpdateUserId(String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsDeptId(String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
	public M setDsCreateUserName(String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsCreateUserId(String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserName(String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsDeleted(String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsOrder(Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public Integer getDsOrder() {
		return getInt("ds_order");
	}
	
	public M setDsUnitId(String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setDsfaOuaUserId(String dsfaOuaUserId) {
		set("dsfa_oua_user_id", dsfaOuaUserId);
		return (M)this;
	}
	
	public String getDsfaOuaUserId() {
		return getStr("dsfa_oua_user_id");
	}
	
	public M setRelationTypeValue(String relationTypeValue) {
		set("relation_type_value", relationTypeValue);
		return (M)this;
	}
	
	public String getRelationTypeValue() {
		return getStr("relation_type_value");
	}
	
	public M setRelationTypeText(String relationTypeText) {
		set("relation_type_text", relationTypeText);
		return (M)this;
	}
	
	public String getRelationTypeText() {
		return getStr("relation_type_text");
	}
	
	public M setOnceWatchTimespan(String onceWatchTimespan) {
		set("once_watch_timespan", onceWatchTimespan);
		return (M)this;
	}
	
	public String getOnceWatchTimespan() {
		return getStr("once_watch_timespan");
	}
	
	public M setRelationId(String relationId) {
		set("relation_id", relationId);
		return (M)this;
	}
	
	public String getRelationId() {
		return getStr("relation_id");
	}
	
	public M setOnceWatchTimeSdate(java.util.Date onceWatchTimeSdate) {
		set("once_watch_time_sdate", onceWatchTimeSdate);
		return (M)this;
	}
	
	public java.util.Date getOnceWatchTimeSdate() {
		return getDate("once_watch_time_sdate");
	}
	
	public M setOnceWatchTimeEdate(java.util.Date onceWatchTimeEdate) {
		set("once_watch_time_edate", onceWatchTimeEdate);
		return (M)this;
	}
	
	public java.util.Date getOnceWatchTimeEdate() {
		return getDate("once_watch_time_edate");
	}
	
}

