package com.dsfa.nc.pd.learn.Do;


import com.dsfa.nc.pd.learn.Do.base.BaseRecordCourseware;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "nc_record_courseware",
		pkName = "nc_record_courseware_id"
)
public class RecordCoursewareDO extends BaseRecordCourseware<RecordCoursewareDO> {
}

