package com.dsfa.nc.pd.lesson.Do;

import com.dsfa.nc.pd.lesson.Do.base.BaseAccess;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "csml_lsf_access",
		pkName = "csml_lsf_access_id"
)
public class CourseAccessItemDO extends BaseAccess<CourseAccessItemDO> {
	public CourseAccessItemDO() {
	}
}

