package com.dsfa.nc.pd.lesson.Do;

import com.dsfa.nc.pd.lesson.Do.base.BaseAppraise;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "csml_lsf_assess",
		pkName = "csml_lsf_assess_id"
)
public class CourseAssessItemDO extends BaseAppraise<CourseAssessItemDO> {
	public CourseAssessItemDO() {
	}
}

