package com.dsfa.nc.pd.lesson.Do;

import com.dsfa.nc.pd.lesson.Do.base.BaseCourseInfoAuth;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "nc_courses_info_auth",
		pkName = "nc_courses_info_auth_id"
)
public class CourseInfoAuthDO extends BaseCourseInfoAuth<CourseInfoAuthDO> {
	public CourseInfoAuthDO() {
	}
}

