package com.dsfa.nc.web.pd.domain.courses.Do;

import com.dsfa.nc.web.pd.domain.courses.Do.base.BaseCourseInfoSub;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "nc_courses_info_sub",
		pkName = "nc_courses_info_sub_id"
)
public class CourseInfoSubDO extends BaseCourseInfoSub<CourseInfoSubDO> {
	public CourseInfoSubDO() {
	}
}

