package com.dsfa.nc.web.pd.Do.base;

import com.dsfa.platform.starter.meta.base.DsfaBaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCourseInfo<M extends BaseCourseInfo<M>> extends DsfaBaseModel<M> implements IBean {

	public M setNcCoursesInfoId(String ncCoursesInfoId) {
		set("nc_courses_info_id", ncCoursesInfoId);
		return (M)this;
	}
	
	public String getNcCoursesInfoId() {
		return getStr("nc_courses_info_id");
	}

	public M setTeacherValue(String teacherValue) {
		set("teacher_value", teacherValue);
		return (M)this;
	}
	
	public String getTeacherValue() {
		return getStr("teacher_value");
	}
	
	public M setTeacherText(String teacherText) {
		set("teacher_text", teacherText);
		return (M)this;
	}
	
	public String getTeacherText() {
		return getStr("teacher_text");
	}
	
	public M setCover(String cover) {
		set("cover", cover);
		return (M)this;
	}
	
	public String getCover() {
		return getStr("cover");
	}
	
	public M setClassificationValue(String classificationValue) {
		set("classification_value", classificationValue);
		return (M)this;
	}
	
	public String getClassificationValue() {
		return getStr("classification_value");
	}
	
	public M setClassificationText(String classificationText) {
		set("classification_text", classificationText);
		return (M)this;
	}
	
	public String getClassificationText() {
		return getStr("classification_text");
	}
	
	public M setTitle(String title) {
		set("title", title);
		return (M)this;
	}
	
	public String getTitle() {
		return getStr("title");
	}
	
	public M setContent(String content) {
		set("content", content);
		return (M)this;
	}
	
	public String getContent() {
		return getStr("content");
	}
	
	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}
	
	public M setDuration(String duration) {
		set("duration", duration);
		return (M)this;
	}
	
	public String getDuration() {
		return getStr("duration");
	}
	
	public M setPeriod(String period) {
		set("period", period);
		return (M)this;
	}
	
	public String getPeriod() {
		return getStr("period");
	}
	
	public M setRCode(String rCode) {
		set("r_code", rCode);
		return (M)this;
	}
	
	public String getRCode() {
		return getStr("r_code");
	}
	
	public M setIsPublicValue(String isPublicValue) {
		set("is_public_value", isPublicValue);
		return (M)this;
	}
	
	public String getIsPublicValue() {
		return getStr("is_public_value");
	}
	
	public M setIsPublicText(String isPublicText) {
		set("is_public_text", isPublicText);
		return (M)this;
	}
	
	public String getIsPublicText() {
		return getStr("is_public_text");
	}
	
	public M setRLabelValue(String rLabelValue) {
		set("r_label_value", rLabelValue);
		return (M)this;
	}
	
	public String getRLabelValue() {
		return getStr("r_label_value");
	}
	
	public M setRLabelText(String rLabelText) {
		set("r_label_text", rLabelText);
		return (M)this;
	}
	
	public String getRLabelText() {
		return getStr("r_label_text");
	}
	
	public M setStateValue(String stateValue) {
		set("state_value", stateValue);
		return (M)this;
	}
	
	public String getStateValue() {
		return getStr("state_value");
	}
	
	public M setStateText(String stateText) {
		set("state_text", stateText);
		return (M)this;
	}
	
	public String getStateText() {
		return getStr("state_text");
	}
	
	public M setIsPublishValue(String isPublishValue) {
		set("is_publish_value", isPublishValue);
		return (M)this;
	}
	
	public String getIsPublishValue() {
		return getStr("is_publish_value");
	}
	
	public M setIsPublishText(String isPublishText) {
		set("is_publish_text", isPublishText);
		return (M)this;
	}
	
	public String getIsPublishText() {
		return getStr("is_publish_text");
	}
	
	public M setIsTopValue(String isTopValue) {
		set("is_top_value", isTopValue);
		return (M)this;
	}
	
	public String getIsTopValue() {
		return getStr("is_top_value");
	}
	
	public M setIsTopText(String isTopText) {
		set("is_top_text", isTopText);
		return (M)this;
	}
	
	public String getIsTopText() {
		return getStr("is_top_text");
	}
	
	public M setRTypeValue(String rTypeValue) {
		set("r_type_value", rTypeValue);
		return (M)this;
	}
	
	public String getRTypeValue() {
		return getStr("r_type_value");
	}
	
	public M setRTypeText(String rTypeText) {
		set("r_type_text", rTypeText);
		return (M)this;
	}
	
	public String getRTypeText() {
		return getStr("r_type_text");
	}
	
	public M setTeacherAuto(String teacherAuto) {
		set("teacher_auto", teacherAuto);
		return (M)this;
	}
	
	public String getTeacherAuto() {
		return getStr("teacher_auto");
	}
	
	public M setTeacherShowUnitJob(String teacherShowUnitJob) {
		set("teacher_show_unit_job", teacherShowUnitJob);
		return (M)this;
	}
	
	public String getTeacherShowUnitJob() {
		return getStr("teacher_show_unit_job");
	}
	
	public M setTeacherShowValue(String teacherShowValue) {
		set("teacher_show_value", teacherShowValue);
		return (M)this;
	}
	
	public String getTeacherShowValue() {
		return getStr("teacher_show_value");
	}
	
	public M setTeacherShowText(String teacherShowText) {
		set("teacher_show_text", teacherShowText);
		return (M)this;
	}
	
	public String getTeacherShowText() {
		return getStr("teacher_show_text");
	}
	
	public M setViewTotle(String viewTotle) {
		set("view_totle", viewTotle);
		return (M)this;
	}
	
	public String getViewTotle() {
		return getStr("view_totle");
	}
	
	public M setResolution(String resolution) {
		set("resolution", resolution);
		return (M)this;
	}
	
	public String getResolution() {
		return getStr("resolution");
	}
	
	public M setWfinfoWfId(String wfinfoWfId) {
		set("wfinfo_wf_id", wfinfoWfId);
		return (M)this;
	}
	
	public String getWfinfoWfId() {
		return getStr("wfinfo_wf_id");
	}
	
	public M setWfinfoWfName(String wfinfoWfName) {
		set("wfinfo_wf_name", wfinfoWfName);
		return (M)this;
	}
	
	public String getWfinfoWfName() {
		return getStr("wfinfo_wf_name");
	}
	
	public M setFlowTitle(String flowTitle) {
		set("flow_title", flowTitle);
		return (M)this;
	}
	
	public String getFlowTitle() {
		return getStr("flow_title");
	}
	
	public M setFlowStateValue(String flowStateValue) {
		set("flow_state_value", flowStateValue);
		return (M)this;
	}
	
	public String getFlowStateValue() {
		return getStr("flow_state_value");
	}
	
	public M setFlowStateText(String flowStateText) {
		set("flow_state_text", flowStateText);
		return (M)this;
	}
	
	public String getFlowStateText() {
		return getStr("flow_state_text");
	}
	
}

