package com.dsfa.nc.web.pd.Do.base;

import com.dsfa.platform.starter.meta.base.DsfaBaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCourseware<M extends BaseCourseware<M>> extends DsfaBaseModel<M> implements IBean {

	public M setNcCoursesCoursewareId(String ncCoursesCoursewareId) {
		set("nc_courses_courseware_id", ncCoursesCoursewareId);
		return (M)this;
	}
	
	public String getNcCoursesCoursewareId() {
		return getStr("nc_courses_courseware_id");
	}

	public M setFileUrl(String fileUrl) {
		set("file_url", fileUrl);
		return (M)this;
	}
	
	public String getFileUrl() {
		return getStr("file_url");
	}
	
	public M setLinkPcUrl(String linkPcUrl) {
		set("link_pc_url", linkPcUrl);
		return (M)this;
	}
	
	public String getLinkPcUrl() {
		return getStr("link_pc_url");
	}
	
	public M setFileAdditionUrl(String fileAdditionUrl) {
		set("file_addition_url", fileAdditionUrl);
		return (M)this;
	}
	
	public String getFileAdditionUrl() {
		return getStr("file_addition_url");
	}
	
	public M setLinkMobileUrl(String linkMobileUrl) {
		set("link_mobile_url", linkMobileUrl);
		return (M)this;
	}
	
	public String getLinkMobileUrl() {
		return getStr("link_mobile_url");
	}
	
	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}
	
	public M setDuration(String duration) {
		set("duration", duration);
		return (M)this;
	}
	
	public String getDuration() {
		return getStr("duration");
	}
	
	public M setTitle(String title) {
		set("title", title);
		return (M)this;
	}
	
	public String getTitle() {
		return getStr("title");
	}
	
	public M setRSize(String rSize) {
		set("r_size", rSize);
		return (M)this;
	}
	
	public String getRSize() {
		return getStr("r_size");
	}
	
	public M setRCode(String rCode) {
		set("r_code", rCode);
		return (M)this;
	}
	
	public String getRCode() {
		return getStr("r_code");
	}
	
	public M setRTypeValue(String rTypeValue) {
		set("r_type_value", rTypeValue);
		return (M)this;
	}
	
	public String getRTypeValue() {
		return getStr("r_type_value");
	}
	
	public M setRTypeText(String rTypeText) {
		set("r_type_text", rTypeText);
		return (M)this;
	}
	
	public String getRTypeText() {
		return getStr("r_type_text");
	}
	
	public M setStateValue(String stateValue) {
		set("state_value", stateValue);
		return (M)this;
	}
	
	public String getStateValue() {
		return getStr("state_value");
	}
	
	public M setStateText(String stateText) {
		set("state_text", stateText);
		return (M)this;
	}
	
	public String getStateText() {
		return getStr("state_text");
	}
	
	public M setSumDurationLong(String sumDurationLong) {
		set("sum_duration_long", sumDurationLong);
		return (M)this;
	}
	
	public String getSumDurationLong() {
		return getStr("sum_duration_long");
	}
	
	public M setIsSlicedValue(String isSlicedValue) {
		set("is_sliced_value", isSlicedValue);
		return (M)this;
	}
	
	public String getIsSlicedValue() {
		return getStr("is_sliced_value");
	}
	
	public M setIsSlicedText(String isSlicedText) {
		set("is_sliced_text", isSlicedText);
		return (M)this;
	}
	
	public String getIsSlicedText() {
		return getStr("is_sliced_text");
	}
	
}

