package com.dsfa.nc.web.pd.Do.base;

import com.dsfa.platform.starter.meta.base.DsfaBaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends DsfaBaseModel<M> implements IBean {

	public M setNcTeacherId(String ncTeacherId) {
		set("nc_teacher_id", ncTeacherId);
		return (M)this;
	}

	public String getNcTeacherId() {
		return getStr("nc_teacher_id");
	}

	public M setDsUpdateUserId(String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}

	public String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}

	public M setDsDeptId(String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}

	public String getDsDeptId() {
		return getStr("ds_dept_id");
	}

	public M setDsCreateUserName(String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}

	public String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}

	public M setDsCreateUserId(String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}

	public String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}

	public M setDsUpdateUserName(String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}

	public String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}

	public M setDsDeleted(String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}

	public String getDsDeleted() {
		return getStr("ds_deleted");
	}

	public M setDsOrder(Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}

	public Integer getDsOrder() {
		return getInt("ds_order");
	}

	public M setDsUnitId(String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}

	public String getDsUnitId() {
		return getStr("ds_unit_id");
	}

	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}

	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}

	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}

	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}

	public M setAbstract(String _abstract) {
		set("abstract", _abstract);
		return (M)this;
	}

	public String getAbstract() {
		return getStr("abstract");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setPhoto(String photo) {
		set("photo", photo);
		return (M)this;
	}

	public String getPhoto() {
		return getStr("photo");
	}

	public M setDeptValue(String deptValue) {
		set("dept_value", deptValue);
		return (M)this;
	}

	public String getDeptValue() {
		return getStr("dept_value");
	}

	public M setDeptText(String deptText) {
		set("dept_text", deptText);
		return (M)this;
	}

	public String getDeptText() {
		return getStr("dept_text");
	}

	public M setPhone(String phone) {
		set("phone", phone);
		return (M)this;
	}

	public String getPhone() {
		return getStr("phone");
	}

	public M setBirth(java.util.Date birth) {
		set("birth", birth);
		return (M)this;
	}

	public java.util.Date getBirth() {
		return getDate("birth");
	}

	public M setGenderValue(String genderValue) {
		set("gender_value", genderValue);
		return (M)this;
	}

	public String getGenderValue() {
		return getStr("gender_value");
	}

	public M setGenderText(String genderText) {
		set("gender_text", genderText);
		return (M)this;
	}

	public String getGenderText() {
		return getStr("gender_text");
	}

	public M setAwards(String awards) {
		set("awards", awards);
		return (M)this;
	}

	public String getAwards() {
		return getStr("awards");
	}

	public M setNativePlaceValue(String nativePlaceValue) {
		set("native_place_value", nativePlaceValue);
		return (M)this;
	}

	public String getNativePlaceValue() {
		return getStr("native_place_value");
	}

	public M setNativePlaceText(String nativePlaceText) {
		set("native_place_text", nativePlaceText);
		return (M)this;
	}

	public String getNativePlaceText() {
		return getStr("native_place_text");
	}

	public M setAdeptValue(String adeptValue) {
		set("adept_value", adeptValue);
		return (M)this;
	}

	public String getAdeptValue() {
		return getStr("adept_value");
	}

	public M setAdeptText(String adeptText) {
		set("adept_text", adeptText);
		return (M)this;
	}

	public String getAdeptText() {
		return getStr("adept_text");
	}

	public M setNationValue(String nationValue) {
		set("nation_value", nationValue);
		return (M)this;
	}

	public String getNationValue() {
		return getStr("nation_value");
	}

	public M setNationText(String nationText) {
		set("nation_text", nationText);
		return (M)this;
	}

	public String getNationText() {
		return getStr("nation_text");
	}

	public M setPosition(String position) {
		set("position", position);
		return (M)this;
	}

	public String getPosition() {
		return getStr("position");
	}

	public M setEnabledValue(String enabledValue) {
		set("enabled_value", enabledValue);
		return (M)this;
	}

	public String getEnabledValue() {
		return getStr("enabled_value");
	}

	public M setEnabledText(String enabledText) {
		set("enabled_text", enabledText);
		return (M)this;
	}

	public String getEnabledText() {
		return getStr("enabled_text");
	}

	public M setTopValue(String topValue) {
		set("top_value", topValue);
		return (M)this;
	}

	public String getTopValue() {
		return getStr("top_value");
	}

	public M setTopText(String topText) {
		set("top_text", topText);
		return (M)this;
	}

	public String getTopText() {
		return getStr("top_text");
	}

	public M setDsfaOuaUserId(String dsfaOuaUserId) {
		set("dsfa_oua_user_id", dsfaOuaUserId);
		return (M)this;
	}

	public String getDsfaOuaUserId() {
		return getStr("dsfa_oua_user_id");
	}

	public M setPinyin(String pinyin) {
		set("pinyin", pinyin);
		return (M)this;
	}

	public String getPinyin() {
		return getStr("pinyin");
	}

	public M setInitials(String initials) {
		set("initials", initials);
		return (M)this;
	}

	public String getInitials() {
		return getStr("initials");
	}
	
}

