server:
  port: 9081
  servlet:
    context-path: /${spring.application.name}
    session:
      timeout: 720m
spring:
  devMode: true
  datasource:
    monitor:
      loginUsername: _admin2
      loginPassword: dreamsoft
    druids:
      - url: jdbc:mysql://192.168.0.14:3141/dsfa_pdwlxy?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true&useSSL=false
        username: pdwlxy
        password: Study_111111
  redis:
    host: 192.168.0.21
    database: 1
    port: 6316
    password: DreamSoft_6316
    jedis:
      pool:
        max-idle: 200
        min-idle: 10
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
dsfa:
  meta:
    git:
      username: linsf@dreamdt.cn
      password: LSFlsf123
      enable: true
    file:
      path: /home/lsf/Projects/build-to-serve/WebBased/Git/pd-dsfa-web
  session:
    authIgnore: true
    rule:
      valiRepeat: true
dsf:
  file:
    upload-virtual-path: /home/lsf/Projects/build-to-serve/WebBased/Git/pd-dsfa-web/data/
    allow: txt,doc,docx,pdf,pptx,ppt,xls,xlsx,wps,jpg,png,gif,mp4,jpeg,mp3
  video:
    ffmpeg: D:/Tool/ffmpeg/bin
    output: /home/lsf/Projects/build-to-serve/WebBased/Git/pd-dsfa-web/data/
dubbo:
  scan:
    base-packages: com.dsfa
  protocol:
    name: dubbo
    port: -1  #自动寻找可用端口
  #  registry:
  #    address: nacos://${spring.cloud.nacos.server-addr}/
  cloud:
    subscribed-services: ${spring.application.name}}
rocketmq:
  nameServer: 192.168.0.79:9058
  producer:
    group: nc
polyv:
  live:
    appId: fqr4ef92nz
    appSecret: e86a8bfb27794a52b1b6844dca521d02
    userId: c018269167
    #分类id
    categoryId: 370836
    apiUrl:
  db:
    writetoken: f2af0cb9-d28c-4280-8aba-4fef1c0ae881
    readtoken: d4eb1afd-9e63-4007-a064-be7a4113f457
    secretkey: Xmcz1F3aY6

#下载资源网速大小  mb/s
download:
  resourse:
    speed: 2
request:
  header: http://192.168.0.58:9081/

examurl: http://192.168.0.36:8085
esurl: 192.168.0.36:9200
