package com.dsfa.nc.pd.lesson.model;

import com.dsfa.nc.pd.lesson.model.base.BaseNcCoursesInfo;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
    tableName = "nc_courses_info",
    pkName = "nc_courses_info_id"
)
public class NcCoursesInfo extends BaseNcCoursesInfo<NcCoursesInfo> {
	public static final NcCoursesInfo dao = new NcCoursesInfo().dao();
}