package com.dsfa.nc.pd.lesson.model;

import com.dsfa.nc.pd.lesson.model.base.BaseNcRecordCourse;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(
    tableName = "nc_record_course",
    pkName = "nc_record_course_id"
)
public class NcRecordCourse extends BaseNcRecordCourse<NcRecordCourse> {
	public static final NcRecordCourse dao = new NcRecordCourse().dao();
}